// Generated by gir_generator. Do not edit.
part of '../gdk4.dart';

/// Provides content for the clipboard or for drag-and-drop operations
/// in a number of formats.
///
/// To create a `GdkContentProvider`, use [ctor@Gdk.ContentProvider.new_for_value]
/// or [ctor@Gdk.ContentProvider.new_for_bytes].
///
/// GDK knows how to handle common text and image formats out-of-the-box. See
/// [class@Gdk.ContentSerializer] and [class@Gdk.ContentDeserializer] if you want
/// to add support for application-specific data formats.
class GdkContentProvider extends GObject {
  GdkContentProvider.fromPointer(super.handle, {super.owned})
    : super.fromPointer();

  /// Create a content provider that provides the given @bytes as data for
  /// the given @mime_type.
  static final _gdkContentProviderNewForBytes =
      gdk4Lookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(
                ffi.Pointer<Utf8>,
                ffi.Pointer<ffi.Void>,
              )
            >
          >('gdk_content_provider_new_for_bytes')
          .asFunction<
            ffi.Pointer<ffi.Void> Function(
              ffi.Pointer<Utf8>,
              ffi.Pointer<ffi.Void>,
            )
          >();
  factory GdkContentProvider.forBytes(String mimeType, GBytes bytes) {
    return withNativeString(mimeType, (nativeMimeType) {
      return GdkContentProvider.fromPointer(
        _gdkContentProviderNewForBytes(
          nativeMimeType.cast<Utf8>(),
          bytes.handle,
        ),
        owned: true,
      );
    });
  }

  /// Create a content provider that provides the given @value.
  static final _gdkContentProviderNewForValue =
      gdk4Lookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)
            >
          >('gdk_content_provider_new_for_value')
          .asFunction<ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)>();
  factory GdkContentProvider.forValue(GValue value) {
    return GdkContentProvider.fromPointer(
      _gdkContentProviderNewForValue(value.handle),
      owned: true,
    );
  }

  /// Emits the ::content-changed signal.
  static final _gdkContentProviderContentChanged =
      gdk4Lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'gdk_content_provider_content_changed',
      ).asFunction<void Function(ffi.Pointer<ffi.Void>)>();
  void contentChanged() {
    _gdkContentProviderContentChanged(this.handle);
  }

  /// Gets the formats that the provider can provide its current contents in.
  static final _gdkContentProviderRefFormats =
      gdk4Lookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)
            >
          >('gdk_content_provider_ref_formats')
          .asFunction<ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)>();
  GdkContentFormats refFormats() {
    return GdkContentFormats.fromPointer(
      _gdkContentProviderRefFormats(this.handle),
    );
  }

  /// Gets the formats that the provider suggests other applications to store
  /// the data in.
  ///
  /// An example of such an application would be a clipboard manager.
  ///
  /// This can be assumed to be a subset of [method@Gdk.ContentProvider.ref_formats].
  static final _gdkContentProviderRefStorableFormats =
      gdk4Lookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)
            >
          >('gdk_content_provider_ref_storable_formats')
          .asFunction<ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)>();
  GdkContentFormats refStorableFormats() {
    return GdkContentFormats.fromPointer(
      _gdkContentProviderRefStorableFormats(this.handle),
    );
  }

  /// Asynchronously writes the contents of @provider to @stream in the given
  /// @mime_type.
  ///
  /// The given mime type does not need to be listed in the formats returned by
  /// [method@Gdk.ContentProvider.ref_formats]. However, if the given `GType` is
  /// not supported, `G_IO_ERROR_NOT_SUPPORTED` will be reported.
  ///
  /// The given @stream will not be closed.
  static final _gdkContentProviderWriteMimeTypeAsync =
      gdk4Lookup<
            ffi.NativeFunction<
              ffi.Void Function(
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<Utf8>,
                ffi.Pointer<ffi.Void>,
                ffi.Int32,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<
                  ffi.NativeFunction<
                    ffi.Void Function(
                      ffi.Pointer<ffi.Void>,
                      ffi.Pointer<ffi.Void>,
                      ffi.Pointer<ffi.Void>,
                    )
                  >
                >,
                ffi.Pointer<ffi.Void>,
              )
            >
          >('gdk_content_provider_write_mime_type_async')
          .asFunction<
            void Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<Utf8>,
              ffi.Pointer<ffi.Void>,
              int,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<
                ffi.NativeFunction<
                  ffi.Void Function(
                    ffi.Pointer<ffi.Void>,
                    ffi.Pointer<ffi.Void>,
                    ffi.Pointer<ffi.Void>,
                  )
                >
              >,
              ffi.Pointer<ffi.Void>,
            )
          >();
  void writeMimeTypeAsync(
    String mimeType,
    GOutputStream stream,
    int ioPriority,
    GCancellable? cancellable,
    void Function(
      ffi.Pointer<ffi.Void>,
      ffi.Pointer<ffi.Void>,
      ffi.Pointer<ffi.Void>,
    )?
    callback,
    ffi.Pointer<ffi.Void> userData,
  ) {
    withNativeString(mimeType, (nativeMimeType) {
      final _nc5 = callback == null
          ? null
          : ffi.NativeCallable<
              ffi.Void Function(
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Void>,
              )
            >.isolateLocal(callback);
      try {
        _gdkContentProviderWriteMimeTypeAsync(
          this.handle,
          nativeMimeType.cast<Utf8>(),
          stream.handle,
          ioPriority,
          cancellable?.handle ?? ffi.nullptr,
          _nc5?.nativeFunction ?? ffi.nullptr,
          userData,
        );
      } finally {
        _nc5?.close();
      }
    });
  }

  /// Finishes an asynchronous write operation.
  ///
  /// See [method@Gdk.ContentProvider.write_mime_type_async].
  static final _gdkContentProviderWriteMimeTypeFinish =
      gdk4Lookup<
            ffi.NativeFunction<
              ffi.Int32 Function(
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Pointer<ffi.Void>>,
              )
            >
          >('gdk_content_provider_write_mime_type_finish')
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Pointer<ffi.Void>>,
            )
          >();
  bool writeMimeTypeFinish(GAsyncResult result) {
    final _error = calloc<ffi.Pointer<ffi.Void>>();
    try {
      final _ret = _gdkContentProviderWriteMimeTypeFinish(
        this.handle,
        result.handle,
        _error,
      );
      if (_error.value != ffi.nullptr) {
        throw GlibException.fromError(_error.value);
      }
      return (_ret) != 0;
    } finally {
      calloc.free(_error);
    }
  }

  /// Emitted whenever the content provided by this provider has changed.
  int onContentChanged(void Function() callback) {
    return _connectSignal_v_0(this.handle, 'content-changed', callback);
  }

  /// The notify signal is emitted on an object when one of its properties has
  /// its value set through g_object_set_property(), g_object_set(), et al.
  ///
  /// Note that getting this signal doesn’t itself guarantee that the value of
  /// the property has actually changed. When it is emitted is determined by the
  /// derived GObject class. If the implementor did not create the property with
  /// %G_PARAM_EXPLICIT_NOTIFY, then any call to g_object_set_property() results
  /// in ::notify being emitted, even if the new value is the same as the old.
  /// If they did pass %G_PARAM_EXPLICIT_NOTIFY, then this signal is emitted only
  /// when they explicitly call g_object_notify() or g_object_notify_by_pspec(),
  /// and common practice is to do that only when the value has actually changed.
  ///
  /// This signal is typically used to obtain change notification for a
  /// single property, by specifying the property name as a detail in the
  /// g_signal_connect() call, like this:
  ///
  /// |[<!-- language="C" -->
  /// g_signal_connect (text_view->buffer, "notify::paste-target-list",
  /// G_CALLBACK (gtk_text_view_target_list_notify),
  /// text_view)
  /// ]|
  ///
  /// It is important to note that you must use
  /// [canonical parameter names][class@GObject.ParamSpec#parameter-names] as
  /// detail strings for the notify signal.
  int onNotify(void Function(GParamSpec pspec) callback) {
    return _connectSignal_v_1_o_gparamspec(this.handle, 'notify', callback);
  }
}

/// Serializes content for inter-application data transfers.
///
/// The `GdkContentSerializer` transforms an object that is identified
/// by a GType into a serialized form (i.e. a byte stream) that is
/// identified by a mime type.
///
/// GTK provides serializers and deserializers for common data types
/// such as text, colors, images or file lists. To register your own
/// serialization functions, use [func@Gdk.content_register_serializer].
///
/// Also see [class@Gdk.ContentDeserializer].
class GdkContentSerializer extends GObject {
  GdkContentSerializer.fromPointer(super.handle, {super.owned})
    : super.fromPointer();

  /// Gets the cancellable for the current operation.
  ///
  /// This is the `GCancellable` that was passed to [func@content_serialize_async].
  static final _gdkContentSerializerGetCancellable =
      gdk4Lookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)
            >
          >('gdk_content_serializer_get_cancellable')
          .asFunction<ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)>();
  GCancellable? getCancellable() {
    return (_gdkContentSerializerGetCancellable(this.handle)) == ffi.nullptr
        ? null
        : GCancellable.fromPointer(
            _gdkContentSerializerGetCancellable(this.handle),
          );
  }

  /// Gets the `GType` to of the object to serialize.
  static final _gdkContentSerializerGetGtype =
      gdk4Lookup<ffi.NativeFunction<ffi.Size Function(ffi.Pointer<ffi.Void>)>>(
        'gdk_content_serializer_get_gtype',
      ).asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  int getGtype() {
    return _gdkContentSerializerGetGtype(this.handle);
  }

  /// Gets the mime type to serialize to.
  static final _gdkContentSerializerGetMimeType =
      gdk4Lookup<
            ffi.NativeFunction<
              ffi.Pointer<Utf8> Function(ffi.Pointer<ffi.Void>)
            >
          >('gdk_content_serializer_get_mime_type')
          .asFunction<ffi.Pointer<Utf8> Function(ffi.Pointer<ffi.Void>)>();
  String getMimeType() {
    return stringFromNative(
      (_gdkContentSerializerGetMimeType(this.handle)).cast(),
      free: false,
    )!;
  }

  /// Gets the output stream for the current operation.
  ///
  /// This is the stream that was passed to [func@content_serialize_async].
  static final _gdkContentSerializerGetOutputStream =
      gdk4Lookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)
            >
          >('gdk_content_serializer_get_output_stream')
          .asFunction<ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)>();
  GOutputStream getOutputStream() {
    return GOutputStream.fromPointer(
      _gdkContentSerializerGetOutputStream(this.handle),
    );
  }

  /// Gets the I/O priority for the current operation.
  ///
  /// This is the priority that was passed to [func@content_serialize_async].
  static final _gdkContentSerializerGetPriority =
      gdk4Lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Void>)>>(
        'gdk_content_serializer_get_priority',
      ).asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  int getPriority() {
    return _gdkContentSerializerGetPriority(this.handle);
  }

  /// Gets the data that was associated with the current operation.
  ///
  /// See [method@Gdk.ContentSerializer.set_task_data].
  static final _gdkContentSerializerGetTaskData =
      gdk4Lookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)
            >
          >('gdk_content_serializer_get_task_data')
          .asFunction<ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)>();
  ffi.Pointer<ffi.Void> getTaskData() {
    return _gdkContentSerializerGetTaskData(this.handle);
  }

  /// Gets the user data that was passed when the serializer was registered.
  static final _gdkContentSerializerGetUserData =
      gdk4Lookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)
            >
          >('gdk_content_serializer_get_user_data')
          .asFunction<ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)>();
  ffi.Pointer<ffi.Void> getUserData() {
    return _gdkContentSerializerGetUserData(this.handle);
  }

  /// Gets the `GValue` to read the object to serialize from.
  static final _gdkContentSerializerGetValue =
      gdk4Lookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)
            >
          >('gdk_content_serializer_get_value')
          .asFunction<ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)>();
  GValue getValue() {
    return GValue.fromPointer(_gdkContentSerializerGetValue(this.handle));
  }

  /// Indicate that the serialization has ended with an error.
  ///
  /// This function consumes @error.
  static final _gdkContentSerializerReturnError =
      gdk4Lookup<
            ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)
            >
          >('gdk_content_serializer_return_error')
          .asFunction<
            void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)
          >();
  void returnError(GError error) {
    _gdkContentSerializerReturnError(this.handle, error.handle);
  }

  /// Indicate that the serialization has been successfully completed.
  static final _gdkContentSerializerReturnSuccess =
      gdk4Lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'gdk_content_serializer_return_success',
      ).asFunction<void Function(ffi.Pointer<ffi.Void>)>();
  void returnSuccess() {
    _gdkContentSerializerReturnSuccess(this.handle);
  }

  /// Associate data with the current serialization operation.
  static final _gdkContentSerializerSetTaskData =
      gdk4Lookup<
            ffi.NativeFunction<
              ffi.Void Function(
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<
                  ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>
                >,
              )
            >
          >('gdk_content_serializer_set_task_data')
          .asFunction<
            void Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<
                ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>
              >,
            )
          >();
  void setTaskData(
    ffi.Pointer<ffi.Void> data,
    void Function(ffi.Pointer<ffi.Void>) notify,
  ) {
    final _nc2 =
        ffi.NativeCallable<
          ffi.Void Function(ffi.Pointer<ffi.Void>)
        >.isolateLocal(notify);
    try {
      _gdkContentSerializerSetTaskData(this.handle, data, _nc2.nativeFunction);
    } finally {
      _nc2.close();
    }
  }

  /// The notify signal is emitted on an object when one of its properties has
  /// its value set through g_object_set_property(), g_object_set(), et al.
  ///
  /// Note that getting this signal doesn’t itself guarantee that the value of
  /// the property has actually changed. When it is emitted is determined by the
  /// derived GObject class. If the implementor did not create the property with
  /// %G_PARAM_EXPLICIT_NOTIFY, then any call to g_object_set_property() results
  /// in ::notify being emitted, even if the new value is the same as the old.
  /// If they did pass %G_PARAM_EXPLICIT_NOTIFY, then this signal is emitted only
  /// when they explicitly call g_object_notify() or g_object_notify_by_pspec(),
  /// and common practice is to do that only when the value has actually changed.
  ///
  /// This signal is typically used to obtain change notification for a
  /// single property, by specifying the property name as a detail in the
  /// g_signal_connect() call, like this:
  ///
  /// |[<!-- language="C" -->
  /// g_signal_connect (text_view->buffer, "notify::paste-target-list",
  /// G_CALLBACK (gtk_text_view_target_list_notify),
  /// text_view)
  /// ]|
  ///
  /// It is important to note that you must use
  /// [canonical parameter names][class@GObject.ParamSpec#parameter-names] as
  /// detail strings for the notify signal.
  int onNotify(void Function(GParamSpec pspec) callback) {
    return _connectSignal_v_1_o_gparamspec(this.handle, 'notify', callback);
  }
}

/// An event caused by a pointing device moving between surfaces.
class GdkCrossingEvent extends GdkEvent {
  GdkCrossingEvent.fromPointer(super.handle, {super.owned})
    : super.fromPointer();

  /// Extracts the notify detail from a crossing event.
  static final _gdkCrossingEventGetDetail =
      gdk4Lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Void>)>>(
        'gdk_crossing_event_get_detail',
      ).asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  GdkNotifyType getDetail() {
    return GdkNotifyType.fromValue(_gdkCrossingEventGetDetail(this.handle));
  }

  /// Checks if the @event surface is the focus surface.
  static final _gdkCrossingEventGetFocus =
      gdk4Lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Void>)>>(
        'gdk_crossing_event_get_focus',
      ).asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  bool getFocus() {
    return (_gdkCrossingEventGetFocus(this.handle)) != 0;
  }

  /// Extracts the crossing mode from a crossing event.
  static final _gdkCrossingEventGetMode =
      gdk4Lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Void>)>>(
        'gdk_crossing_event_get_mode',
      ).asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  GdkCrossingMode getMode() {
    return GdkCrossingMode.fromValue(_gdkCrossingEventGetMode(this.handle));
  }
}
