// Generated by gir_generator. Do not edit.
part of '../gdk4.dart';

/// Defines how device axes are interpreted by GTK.
///
/// Note that the X and Y axes are not really needed; pointer devices
/// report their location via the x/y members of events regardless. Whether
/// X and Y are present as axes depends on the GDK backend.
enum GdkAxisUse {
  ignore(0),
  x(1),
  y(2),
  deltaX(3),
  deltaY(4),
  pressure(5),
  xtilt(6),
  ytilt(7),
  wheel(8),
  distance(9),
  rotation(10),
  slider(11),
  last(12);

  const GdkAxisUse(this.value);
  final int value;

  static GdkAxisUse fromValue(int value) => switch (value) {
    0 => ignore,
    1 => x,
    2 => y,
    3 => deltaX,
    4 => deltaY,
    5 => pressure,
    6 => xtilt,
    7 => ytilt,
    8 => wheel,
    9 => distance,
    10 => rotation,
    11 => slider,
    12 => last,
    _ => throw ArgumentError.value(value, 'value', 'Unknown GdkAxisUse value'),
  };
}

/// The values of this enumeration describe whether image data uses
/// the full range of 8-bit values.
///
/// In digital broadcasting, it is common to reserve the lowest and
/// highest values. Typically the allowed values for the narrow range
/// are 16-235 for Y and 16-240 for u,v (when dealing with YUV data).
enum GdkCicpRange {
  narrow(0),
  full(1);

  const GdkCicpRange(this.value);
  final int value;

  static GdkCicpRange fromValue(int value) => switch (value) {
    0 => narrow,
    1 => full,
    _ => throw ArgumentError.value(
      value,
      'value',
      'Unknown GdkCicpRange value',
    ),
  };
}

/// Enumerates the color channels of RGBA values as used in
/// `GdkColor` and OpenGL/Vulkan shaders.
///
/// Note that this is not the order of pixel values in Cairo
/// and `GdkMemoryFormat` can have many different orders.
enum GdkColorChannel {
  red(0),
  green(1),
  blue(2),
  alpha(3);

  const GdkColorChannel(this.value);
  final int value;

  static GdkColorChannel fromValue(int value) => switch (value) {
    0 => red,
    1 => green,
    2 => blue,
    3 => alpha,
    _ => throw ArgumentError.value(
      value,
      'value',
      'Unknown GdkColorChannel value',
    ),
  };
}

/// Specifies the crossing mode for enter and leave events.
enum GdkCrossingMode {
  normal(0),
  grab(1),
  ungrab(2),
  gtkGrab(3),
  gtkUngrab(4),
  stateChanged(5),
  touchBegin(6),
  touchEnd(7),
  deviceSwitch(8);

  const GdkCrossingMode(this.value);
  final int value;

  static GdkCrossingMode fromValue(int value) => switch (value) {
    0 => normal,
    1 => grab,
    2 => ungrab,
    3 => gtkGrab,
    4 => gtkUngrab,
    5 => stateChanged,
    6 => touchBegin,
    7 => touchEnd,
    8 => deviceSwitch,
    _ => throw ArgumentError.value(
      value,
      'value',
      'Unknown GdkCrossingMode value',
    ),
  };
}

/// A pad feature.
enum GdkDevicePadFeature {
  button(0),
  ring(1),
  strip(2);

  const GdkDevicePadFeature(this.value);
  final int value;

  static GdkDevicePadFeature fromValue(int value) => switch (value) {
    0 => button,
    1 => ring,
    2 => strip,
    _ => throw ArgumentError.value(
      value,
      'value',
      'Unknown GdkDevicePadFeature value',
    ),
  };
}

/// Indicates the specific type of tool being used being a tablet. Such as an
/// airbrush, pencil, etc.
enum GdkDeviceToolType {
  unknown(0),
  pen(1),
  eraser(2),
  brush(3),
  pencil(4),
  airbrush(5),
  mouse(6),
  lens(7);

  const GdkDeviceToolType(this.value);
  final int value;

  static GdkDeviceToolType fromValue(int value) => switch (value) {
    0 => unknown,
    1 => pen,
    2 => eraser,
    3 => brush,
    4 => pencil,
    5 => airbrush,
    6 => mouse,
    7 => lens,
    _ => throw ArgumentError.value(
      value,
      'value',
      'Unknown GdkDeviceToolType value',
    ),
  };
}

/// Error enumeration for `GdkDmabufTexture`.
enum GdkDmabufError {
  notAvailable(0),
  unsupportedFormat(1),
  creationFailed(2);

  const GdkDmabufError(this.value);
  final int value;

  static GdkDmabufError fromValue(int value) => switch (value) {
    0 => notAvailable,
    1 => unsupportedFormat,
    2 => creationFailed,
    _ => throw ArgumentError.value(
      value,
      'value',
      'Unknown GdkDmabufError value',
    ),
  };
}

/// Used in `GdkDrag` to the reason of a cancelled DND operation.
enum GdkDragCancelReason {
  noTarget(0),
  userCancelled(1),
  error(2);

  const GdkDragCancelReason(this.value);
  final int value;

  static GdkDragCancelReason fromValue(int value) => switch (value) {
    0 => noTarget,
    1 => userCancelled,
    2 => error,
    _ => throw ArgumentError.value(
      value,
      'value',
      'Unknown GdkDragCancelReason value',
    ),
  };
}

/// Specifies the type of the event.
enum GdkEventType {
  delete(0),
  motionNotify(1),
  buttonPress(2),
  buttonRelease(3),
  keyPress(4),
  keyRelease(5),
  enterNotify(6),
  leaveNotify(7),
  focusChange(8),
  proximityIn(9),
  proximityOut(10),
  dragEnter(11),
  dragLeave(12),
  dragMotion(13),
  dropStart(14),
  scroll(15),
  grabBroken(16),
  touchBegin(17),
  touchUpdate(18),
  touchEnd(19),
  touchCancel(20),
  touchpadSwipe(21),
  touchpadPinch(22),
  padButtonPress(23),
  padButtonRelease(24),
  padRing(25),
  padStrip(26),
  padGroupMode(27),
  touchpadHold(28),
  padDial(29),
  eventLast(30);

  const GdkEventType(this.value);
  final int value;

  static GdkEventType fromValue(int value) => switch (value) {
    0 => delete,
    1 => motionNotify,
    2 => buttonPress,
    3 => buttonRelease,
    4 => keyPress,
    5 => keyRelease,
    6 => enterNotify,
    7 => leaveNotify,
    8 => focusChange,
    9 => proximityIn,
    10 => proximityOut,
    11 => dragEnter,
    12 => dragLeave,
    13 => dragMotion,
    14 => dropStart,
    15 => scroll,
    16 => grabBroken,
    17 => touchBegin,
    18 => touchUpdate,
    19 => touchEnd,
    20 => touchCancel,
    21 => touchpadSwipe,
    22 => touchpadPinch,
    23 => padButtonPress,
    24 => padButtonRelease,
    25 => padRing,
    26 => padStrip,
    27 => padGroupMode,
    28 => touchpadHold,
    29 => padDial,
    30 => eventLast,
    _ => throw ArgumentError.value(
      value,
      'value',
      'Unknown GdkEventType value',
    ),
  };
}

/// Indicates which monitor a surface should span over when in fullscreen mode.
enum GdkFullscreenMode {
  currentMonitor(0),
  allMonitors(1);

  const GdkFullscreenMode(this.value);
  final int value;

  static GdkFullscreenMode fromValue(int value) => switch (value) {
    0 => currentMonitor,
    1 => allMonitors,
    _ => throw ArgumentError.value(
      value,
      'value',
      'Unknown GdkFullscreenMode value',
    ),
  };
}

/// Error enumeration for `GdkGLContext`.
enum GdkGLError {
  notAvailable(0),
  unsupportedFormat(1),
  unsupportedProfile(2),
  compilationFailed(3),
  linkFailed(4);

  const GdkGLError(this.value);
  final int value;

  static GdkGLError fromValue(int value) => switch (value) {
    0 => notAvailable,
    1 => unsupportedFormat,
    2 => unsupportedProfile,
    3 => compilationFailed,
    4 => linkFailed,
    _ => throw ArgumentError.value(value, 'value', 'Unknown GdkGLError value'),
  };
}

/// Defines the reference point of a surface and is used in `GdkPopupLayout`.
enum GdkGravity {
  northWest(1),
  north(2),
  northEast(3),
  west(4),
  center(5),
  east(6),
  southWest(7),
  south(8),
  southEast(9),
  static_(10);

  const GdkGravity(this.value);
  final int value;

  static GdkGravity fromValue(int value) => switch (value) {
    1 => northWest,
    2 => north,
    3 => northEast,
    4 => west,
    5 => center,
    6 => east,
    7 => southWest,
    8 => south,
    9 => southEast,
    10 => static_,
    _ => throw ArgumentError.value(value, 'value', 'Unknown GdkGravity value'),
  };
}

/// An enumeration describing the type of an input device in general terms.
enum GdkInputSource {
  mouse(0),
  pen(1),
  keyboard(2),
  touchscreen(3),
  touchpad(4),
  trackpoint(5),
  tabletPad(6);

  const GdkInputSource(this.value);
  final int value;

  static GdkInputSource fromValue(int value) => switch (value) {
    0 => mouse,
    1 => pen,
    2 => keyboard,
    3 => touchscreen,
    4 => touchpad,
    5 => trackpoint,
    6 => tabletPad,
    _ => throw ArgumentError.value(
      value,
      'value',
      'Unknown GdkInputSource value',
    ),
  };
}

/// Describes how well an event matches a given keyval and modifiers.
///
/// `GdkKeyMatch` values are returned by [method@Gdk.KeyEvent.matches].
enum GdkKeyMatch {
  none(0),
  partial(1),
  exact(2);

  const GdkKeyMatch(this.value);
  final int value;

  static GdkKeyMatch fromValue(int value) => switch (value) {
    0 => none,
    1 => partial,
    2 => exact,
    _ => throw ArgumentError.value(value, 'value', 'Unknown GdkKeyMatch value'),
  };
}
