// Generated by gir_generator. Do not edit.
part of '../gdk4.dart';

/// Class structure for `GdkContentProvider`.
final class GdkContentProviderClass {
  GdkContentProviderClass.fromPointer(this.handle, {bool owned = false});
  final ffi.Pointer<ffi.Void> handle;

  /// Re-wraps this wrapper's [handle] as [T] via [factory].
  ///
  /// Use this when another wrapper returns this class's
  /// instance but the caller needs the destination class's
  /// methods. Pass the destination class's `fromPointer` as
  /// the callback, e.g. `wrapper.cast<GFile>(GFile.fromPointer)`.
  /// The handle is forwarded as-is; the original wrapper
  /// (which produced this object) remains the owner.
  T cast<T extends Object>(T Function(ffi.Pointer<ffi.Void>) factory) {
    return factory(handle);
  }
}

final class GdkDevicePadInterface {
  GdkDevicePadInterface.fromPointer(this.handle, {bool owned = false});
  final ffi.Pointer<ffi.Void> handle;

  /// Re-wraps this wrapper's [handle] as [T] via [factory].
  ///
  /// Use this when another wrapper returns this class's
  /// instance but the caller needs the destination class's
  /// methods. Pass the destination class's `fromPointer` as
  /// the callback, e.g. `wrapper.cast<GFile>(GFile.fromPointer)`.
  /// The handle is forwarded as-is; the original wrapper
  /// (which produced this object) remains the owner.
  T cast<T extends Object>(T Function(ffi.Pointer<ffi.Void>) factory) {
    return factory(handle);
  }
}

/// Provides information about supported DMA buffer formats.
///
/// You can query whether a given format is supported with
/// [method@Gdk.DmabufFormats.contains] and you can iterate
/// over the list of all supported formats with
/// [method@Gdk.DmabufFormats.get_n_formats] and
/// [method@Gdk.DmabufFormats.get_format].
///
/// The list of supported formats is sorted by preference,
/// with the best formats coming first.
///
/// The list may contains (format, modifier) pairs where the modifier
/// is `DMA_FORMAT_MOD_INVALID`, indicating that **_implicit modifiers_**
/// may be used with this format.
///
/// See [class@Gdk.DmabufTextureBuilder] for more information
/// about DMA buffers.
///
/// Note that DMA buffers only exist on Linux.
final class GdkDmabufFormats {
  GdkDmabufFormats.fromPointer(this.handle, {bool owned = false});
  final ffi.Pointer<ffi.Void> handle;

  /// Re-wraps this wrapper's [handle] as [T] via [factory].
  ///
  /// Use this when another wrapper returns this class's
  /// instance but the caller needs the destination class's
  /// methods. Pass the destination class's `fromPointer` as
  /// the callback, e.g. `wrapper.cast<GFile>(GFile.fromPointer)`.
  /// The handle is forwarded as-is; the original wrapper
  /// (which produced this object) remains the owner.
  T cast<T extends Object>(T Function(ffi.Pointer<ffi.Void>) factory) {
    return factory(handle);
  }

  /// Returns whether a given format is contained in @formats.
  static final _gdkDmabufFormatsContains =
      gdk4Lookup<
            ffi.NativeFunction<
              ffi.Int32 Function(ffi.Pointer<ffi.Void>, ffi.Uint32, ffi.Uint64)
            >
          >('gdk_dmabuf_formats_contains')
          .asFunction<int Function(ffi.Pointer<ffi.Void>, int, int)>();
  bool contains(int fourcc, int modifier) {
    return (_gdkDmabufFormatsContains(this.handle, fourcc, modifier)) != 0;
  }

  /// Returns whether @formats1 and @formats2 contain the
  /// same dmabuf formats, in the same order.
  static final _gdkDmabufFormatsEqual =
      gdk4Lookup<
            ffi.NativeFunction<
              ffi.Int32 Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)
            >
          >('gdk_dmabuf_formats_equal')
          .asFunction<
            int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)
          >();
  bool equal([GdkDmabufFormats? formats2]) {
    return (_gdkDmabufFormatsEqual(
          this.handle,
          formats2?.handle ?? ffi.nullptr,
        )) !=
        0;
  }

  /// Gets the fourcc code and modifier for a format
  /// that is contained in @formats.
  static final _gdkDmabufFormatsGetFormat =
      gdk4Lookup<
            ffi.NativeFunction<
              ffi.Void Function(
                ffi.Pointer<ffi.Void>,
                ffi.Size,
                ffi.Pointer<ffi.Uint32>,
                ffi.Pointer<ffi.Uint64>,
              )
            >
          >('gdk_dmabuf_formats_get_format')
          .asFunction<
            void Function(
              ffi.Pointer<ffi.Void>,
              int,
              ffi.Pointer<ffi.Uint32>,
              ffi.Pointer<ffi.Uint64>,
            )
          >();
  (int, int) getFormat(int idx) {
    final _out0 = malloc<ffi.Uint32>();
    final _out1 = malloc<ffi.Uint64>();
    try {
      _gdkDmabufFormatsGetFormat(this.handle, idx, _out0, _out1);
      return (_out0.value, _out1.value);
    } finally {
      malloc.free(_out0);
      malloc.free(_out1);
    }
  }

  /// Returns the number of formats that the @formats object
  /// contains.
  ///
  /// Note that DMA buffers are a Linux concept, so on other
  /// platforms, [method@Gdk.DmabufFormats.get_n_formats] will
  /// always return zero.
  static final _gdkDmabufFormatsGetNFormats =
      gdk4Lookup<ffi.NativeFunction<ffi.Size Function(ffi.Pointer<ffi.Void>)>>(
        'gdk_dmabuf_formats_get_n_formats',
      ).asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  int getNFormats() {
    return _gdkDmabufFormatsGetNFormats(this.handle);
  }

  /// Increases the reference count of @formats.
  static final _gdkDmabufFormatsRef =
      gdk4Lookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)
            >
          >('gdk_dmabuf_formats_ref')
          .asFunction<ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)>();
  GdkDmabufFormats ref() {
    return GdkDmabufFormats.fromPointer(_gdkDmabufFormatsRef(this.handle));
  }

  /// Decreases the reference count of @formats.
  ///
  /// When the reference count reaches zero,
  /// the object is freed.
  static final _gdkDmabufFormatsUnref =
      gdk4Lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'gdk_dmabuf_formats_unref',
      ).asFunction<void Function(ffi.Pointer<ffi.Void>)>();
  void unref() {
    _gdkDmabufFormatsUnref(this.handle);
  }
}

final class GdkDmabufTextureBuilderClass {
  GdkDmabufTextureBuilderClass.fromPointer(this.handle, {bool owned = false});
  final ffi.Pointer<ffi.Void> handle;

  /// Re-wraps this wrapper's [handle] as [T] via [factory].
  ///
  /// Use this when another wrapper returns this class's
  /// instance but the caller needs the destination class's
  /// methods. Pass the destination class's `fromPointer` as
  /// the callback, e.g. `wrapper.cast<GFile>(GFile.fromPointer)`.
  /// The handle is forwarded as-is; the original wrapper
  /// (which produced this object) remains the owner.
  T cast<T extends Object>(T Function(ffi.Pointer<ffi.Void>) factory) {
    return factory(handle);
  }
}

final class GdkDmabufTextureClass {
  GdkDmabufTextureClass.fromPointer(this.handle, {bool owned = false});
  final ffi.Pointer<ffi.Void> handle;

  /// Re-wraps this wrapper's [handle] as [T] via [factory].
  ///
  /// Use this when another wrapper returns this class's
  /// instance but the caller needs the destination class's
  /// methods. Pass the destination class's `fromPointer` as
  /// the callback, e.g. `wrapper.cast<GFile>(GFile.fromPointer)`.
  /// The handle is forwarded as-is; the original wrapper
  /// (which produced this object) remains the owner.
  T cast<T extends Object>(T Function(ffi.Pointer<ffi.Void>) factory) {
    return factory(handle);
  }
}

/// The `GdkDragSurfaceInterface` implementation is private to GDK.
final class GdkDragSurfaceInterface {
  GdkDragSurfaceInterface.fromPointer(this.handle, {bool owned = false});
  final ffi.Pointer<ffi.Void> handle;

  /// Re-wraps this wrapper's [handle] as [T] via [factory].
  ///
  /// Use this when another wrapper returns this class's
  /// instance but the caller needs the destination class's
  /// methods. Pass the destination class's `fromPointer` as
  /// the callback, e.g. `wrapper.cast<GFile>(GFile.fromPointer)`.
  /// The handle is forwarded as-is; the original wrapper
  /// (which produced this object) remains the owner.
  T cast<T extends Object>(T Function(ffi.Pointer<ffi.Void>) factory) {
    return factory(handle);
  }
}

/// Contains information that is useful to compute the size of a drag surface.
final class GdkDragSurfaceSize {
  GdkDragSurfaceSize.fromPointer(this.handle, {bool owned = false});
  final ffi.Pointer<ffi.Void> handle;

  /// Re-wraps this wrapper's [handle] as [T] via [factory].
  ///
  /// Use this when another wrapper returns this class's
  /// instance but the caller needs the destination class's
  /// methods. Pass the destination class's `fromPointer` as
  /// the callback, e.g. `wrapper.cast<GFile>(GFile.fromPointer)`.
  /// The handle is forwarded as-is; the original wrapper
  /// (which produced this object) remains the owner.
  T cast<T extends Object>(T Function(ffi.Pointer<ffi.Void>) factory) {
    return factory(handle);
  }

  /// Sets the size the drag surface prefers to be resized to.
  static final _gdkDragSurfaceSizeSetSize =
      gdk4Lookup<
            ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Int32, ffi.Int32)
            >
          >('gdk_drag_surface_size_set_size')
          .asFunction<void Function(ffi.Pointer<ffi.Void>, int, int)>();
  void setSize(int width, int height) {
    _gdkDragSurfaceSizeSetSize(this.handle, width, height);
  }
}

/// An opaque type representing a sequence of related events.
final class GdkEventSequence {
  GdkEventSequence.fromPointer(this.handle, {bool owned = false});
  final ffi.Pointer<ffi.Void> handle;

  /// Re-wraps this wrapper's [handle] as [T] via [factory].
  ///
  /// Use this when another wrapper returns this class's
  /// instance but the caller needs the destination class's
  /// methods. Pass the destination class's `fromPointer` as
  /// the callback, e.g. `wrapper.cast<GFile>(GFile.fromPointer)`.
  /// The handle is forwarded as-is; the original wrapper
  /// (which produced this object) remains the owner.
  T cast<T extends Object>(T Function(ffi.Pointer<ffi.Void>) factory) {
    return factory(handle);
  }
}

/// An opaque type representing a list of files.
final class GdkFileList {
  GdkFileList.fromPointer(this.handle, {bool owned = false});
  final ffi.Pointer<ffi.Void> handle;

  /// Re-wraps this wrapper's [handle] as [T] via [factory].
  ///
  /// Use this when another wrapper returns this class's
  /// instance but the caller needs the destination class's
  /// methods. Pass the destination class's `fromPointer` as
  /// the callback, e.g. `wrapper.cast<GFile>(GFile.fromPointer)`.
  /// The handle is forwarded as-is; the original wrapper
  /// (which produced this object) remains the owner.
  T cast<T extends Object>(T Function(ffi.Pointer<ffi.Void>) factory) {
    return factory(handle);
  }

  /// Creates a new `GdkFileList` for the given array of files.
  ///
  /// This function is meant to be used by language bindings.
  static final _gdkFileListNewFromArray =
      gdk4Lookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>, ffi.Size)
            >
          >('gdk_file_list_new_from_array')
          .asFunction<
            ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>, int)
          >();
  GdkFileList.fromArray(ffi.Pointer<ffi.Void> files, int nFiles)
    : this.fromPointer(_gdkFileListNewFromArray(files, nFiles));

  /// Creates a new files list container from a singly linked list of
  /// `GFile` instances.
  ///
  /// This function is meant to be used by language bindings
  static final _gdkFileListNewFromList =
      gdk4Lookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)
            >
          >('gdk_file_list_new_from_list')
          .asFunction<ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)>();
  GdkFileList.fromList(GSList files)
    : this.fromPointer(_gdkFileListNewFromList(files.handle));

  /// Retrieves the list of files inside a `GdkFileList`.
  ///
  /// This function is meant for language bindings.
  static final _gdkFileListGetFiles =
      gdk4Lookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)
            >
          >('gdk_file_list_get_files')
          .asFunction<ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)>();
  GSList getFiles() {
    return GSList.fromPointer(_gdkFileListGetFiles(this.handle));
  }
}

final class GdkFrameClockClass {
  GdkFrameClockClass.fromPointer(this.handle, {bool owned = false});
  final ffi.Pointer<ffi.Void> handle;

  /// Re-wraps this wrapper's [handle] as [T] via [factory].
  ///
  /// Use this when another wrapper returns this class's
  /// instance but the caller needs the destination class's
  /// methods. Pass the destination class's `fromPointer` as
  /// the callback, e.g. `wrapper.cast<GFile>(GFile.fromPointer)`.
  /// The handle is forwarded as-is; the original wrapper
  /// (which produced this object) remains the owner.
  T cast<T extends Object>(T Function(ffi.Pointer<ffi.Void>) factory) {
    return factory(handle);
  }
}

final class GdkFrameClockPrivate {
  GdkFrameClockPrivate.fromPointer(this.handle, {bool owned = false});
  final ffi.Pointer<ffi.Void> handle;

  /// Re-wraps this wrapper's [handle] as [T] via [factory].
  ///
  /// Use this when another wrapper returns this class's
  /// instance but the caller needs the destination class's
  /// methods. Pass the destination class's `fromPointer` as
  /// the callback, e.g. `wrapper.cast<GFile>(GFile.fromPointer)`.
  /// The handle is forwarded as-is; the original wrapper
  /// (which produced this object) remains the owner.
  T cast<T extends Object>(T Function(ffi.Pointer<ffi.Void>) factory) {
    return factory(handle);
  }
}
