// Generated by gir_generator. Do not edit.
part of '../gtk_source5.dart';

/// PyGObject-style typed property accessor. Each getter
/// and setter delegates to the existing typed
/// `get<Name>` / `set<Name>` methods on [GtkSourceSpaceDrawer].
///
/// Skipped properties (unsupported type, missing getter
/// or setter) are recorded in the generation report.
class GtkSourceSpaceDrawerProps {
  GtkSourceSpaceDrawerProps(this._self);
  final GtkSourceSpaceDrawer _self;

  bool get enableMatrix => _self.getEnableMatrix();
  set enableMatrix(bool value) {
    _self.setEnableMatrix(value);
  }

  GVariant get matrix => _self.getMatrix();
  set matrix(GVariant? value) {
    _self.setMatrix(value);
  }
}
