name: gtk4_counter
description: A simple GTK4 counter app built with the gir_bindings workspace.
publish_to: none
resolution: workspace

environment:
  sdk: ^3.13.4

dev_dependencies:
  test: ^1.25.6

dependencies:
  adw:
    path: ../packages/adw
  ffi: ^2.1.3
  gio:
    path: ../packages/gio
  gobject:
    path: ../packages/gobject
  gtk4:
    path: ../packages/gtk4
