name: dart_gir
publish_to: none
description: GIR-based Dart FFI bindings for GObject libraries (GLib, GTK4, Libadwaita, etc.).

environment:
  sdk: ^3.13.4

workspace:
  - example
  - generator
  - packages/adw
  - packages/cairo
  - packages/gdk4
  - packages/gdk_pixbuf
  - packages/gi_repository3
  - packages/gio
  - packages/gir_ffi
  - packages/glib
  - packages/gobject
  - packages/graphene
  - packages/gsk4
  - packages/gtk4
  - packages/gtk_source5
  - packages/pango

dev_dependencies:
  lints: ^6.0.0
  test: ^1.32.0
  vendor: ^0.9.8
  yaml: ^3.1.2
