// Generated by gir_generator. Do not edit.
part of '../glib.dart';

final class GHmac {
  GHmac.fromPointer(this.handle, {bool owned = false});
  final ffi.Pointer<ffi.Void> handle;

  /// Re-wraps this wrapper's [handle] as [T] via [factory].
  ///
  /// Use this when another wrapper returns this class's
  /// instance but the caller needs the destination class's
  /// methods. Pass the destination class's `fromPointer` as
  /// the callback, e.g. `wrapper.cast<GFile>(GFile.fromPointer)`.
  /// The handle is forwarded as-is; the original wrapper
  /// (which produced this object) remains the owner.
  T cast<T extends Object>(T Function(ffi.Pointer<ffi.Void>) factory) {
    return factory(handle);
  }

  static final _gHmacNew =
      glibLookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(ffi.Int32, ffi.Uint8, ffi.Size)
            >
          >('g_hmac_new')
          .asFunction<ffi.Pointer<ffi.Void> Function(int, int, int)>();
  GHmac(GChecksumType digestType, int key, int keyLen)
    : this.fromPointer(_gHmacNew(digestType.value, key, keyLen));

  static final _gHmacCopy =
      glibLookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)
            >
          >('g_hmac_copy')
          .asFunction<ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)>();
  GHmac copy() {
    return GHmac.fromPointer(_gHmacCopy(this.handle));
  }

  static final _gHmacGetDigest =
      glibLookup<
            ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Uint8, ffi.Size)
            >
          >('g_hmac_get_digest')
          .asFunction<void Function(ffi.Pointer<ffi.Void>, int, int)>();
  void getDigest(int buffer, int digestLen) {
    _gHmacGetDigest(this.handle, buffer, digestLen);
  }

  static final _gHmacGetString =
      glibLookup<
            ffi.NativeFunction<
              ffi.Pointer<Utf8> Function(ffi.Pointer<ffi.Void>)
            >
          >('g_hmac_get_string')
          .asFunction<ffi.Pointer<Utf8> Function(ffi.Pointer<ffi.Void>)>();
  String getString() {
    return stringFromNative(
      (_gHmacGetString(this.handle)).cast(),
      free: false,
    )!;
  }

  static final _gHmacRef =
      glibLookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)
            >
          >('g_hmac_ref')
          .asFunction<ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)>();
  GHmac ref() {
    return GHmac.fromPointer(_gHmacRef(this.handle));
  }

  static final _gHmacUnref =
      glibLookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'g_hmac_unref',
      ).asFunction<void Function(ffi.Pointer<ffi.Void>)>();
  void unref() {
    _gHmacUnref(this.handle);
  }

  static final _gHmacUpdate =
      glibLookup<
            ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Uint8, ffi.IntPtr)
            >
          >('g_hmac_update')
          .asFunction<void Function(ffi.Pointer<ffi.Void>, int, int)>();
  void update(int data, int length) {
    _gHmacUpdate(this.handle, data, length);
  }
}

/// The #GHook struct represents a single hook function in a #GHookList.
final class GHook {
  GHook.fromPointer(this.handle, {bool owned = false});
  final ffi.Pointer<ffi.Void> handle;

  /// Re-wraps this wrapper's [handle] as [T] via [factory].
  ///
  /// Use this when another wrapper returns this class's
  /// instance but the caller needs the destination class's
  /// methods. Pass the destination class's `fromPointer` as
  /// the callback, e.g. `wrapper.cast<GFile>(GFile.fromPointer)`.
  /// The handle is forwarded as-is; the original wrapper
  /// (which produced this object) remains the owner.
  T cast<T extends Object>(T Function(ffi.Pointer<ffi.Void>) factory) {
    return factory(handle);
  }

  /// Compares the ids of two #GHook elements, returning a negative value
  /// if the second id is greater than the first.
  static final _gHookCompareIds =
      glibLookup<
            ffi.NativeFunction<
              ffi.Int32 Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)
            >
          >('g_hook_compare_ids')
          .asFunction<
            int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)
          >();
  int compareIds(GHook sibling) {
    return _gHookCompareIds(this.handle, sibling.handle);
  }

  /// Destroys a #GHook, given its ID.
  static final _gHookDestroy =
      glibLookup<
            ffi.NativeFunction<
              ffi.Int32 Function(ffi.Pointer<ffi.Void>, ffi.UnsignedLong)
            >
          >('g_hook_destroy')
          .asFunction<int Function(ffi.Pointer<ffi.Void>, int)>();
  static bool destroy(GHookList hookList, int hookId) {
    return (_gHookDestroy(hookList.handle, hookId)) != 0;
  }

  /// Removes one #GHook from a #GHookList, marking it
  /// inactive and calling g_hook_unref() on it.
  static final _gHookDestroyLink =
      glibLookup<
            ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)
            >
          >('g_hook_destroy_link')
          .asFunction<
            void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)
          >();
  static void destroyLink(GHookList hookList, GHook hook) {
    _gHookDestroyLink(hookList.handle, hook.handle);
  }

  /// Calls the #GHookList @finalize_hook function if it exists,
  /// and frees the memory allocated for the #GHook.
  static final _gHookFree =
      glibLookup<
            ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)
            >
          >('g_hook_free')
          .asFunction<
            void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)
          >();
  static void free(GHookList hookList, GHook hook) {
    _gHookFree(hookList.handle, hook.handle);
  }

  /// Inserts a #GHook into a #GHookList, before a given #GHook.
  static final _gHookInsertBefore =
      glibLookup<
            ffi.NativeFunction<
              ffi.Void Function(
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Void>,
              )
            >
          >('g_hook_insert_before')
          .asFunction<
            void Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Void>,
            )
          >();
  static void insertBefore(GHookList hookList, GHook? sibling, GHook hook) {
    _gHookInsertBefore(
      hookList.handle,
      sibling?.handle ?? ffi.nullptr,
      hook.handle,
    );
  }

  /// Inserts a #GHook into a #GHookList, sorted by the given function.
  static final _gHookInsertSorted =
      glibLookup<
            ffi.NativeFunction<
              ffi.Void Function(
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<
                  ffi.NativeFunction<
                    ffi.Int32 Function(
                      ffi.Pointer<ffi.Void>,
                      ffi.Pointer<ffi.Void>,
                    )
                  >
                >,
              )
            >
          >('g_hook_insert_sorted')
          .asFunction<
            void Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<
                ffi.NativeFunction<
                  ffi.Int32 Function(
                    ffi.Pointer<ffi.Void>,
                    ffi.Pointer<ffi.Void>,
                  )
                >
              >,
            )
          >();
  static void insertSorted(
    GHookList hookList,
    GHook hook,
    int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>) func,
  ) {
    final _nc3 =
        ffi.NativeCallable<
          ffi.Int32 Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)
        >.isolateLocal(func, exceptionalReturn: 0);
    try {
      _gHookInsertSorted(hookList.handle, hook.handle, _nc3.nativeFunction);
    } finally {
      _nc3.close();
    }
  }

  /// Prepends a #GHook on the start of a #GHookList.
  static final _gHookPrepend =
      glibLookup<
            ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)
            >
          >('g_hook_prepend')
          .asFunction<
            void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)
          >();
  static void prepend(GHookList hookList, GHook hook) {
    _gHookPrepend(hookList.handle, hook.handle);
  }

  /// Decrements the reference count of a #GHook.
  /// If the reference count falls to 0, the #GHook is removed
  /// from the #GHookList and g_hook_free() is called to free it.
  static final _gHookUnref =
      glibLookup<
            ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)
            >
          >('g_hook_unref')
          .asFunction<
            void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)
          >();
  static void unref(GHookList hookList, GHook hook) {
    _gHookUnref(hookList.handle, hook.handle);
  }
}

/// The #GHookList struct represents a list of hook functions.
final class GHookList {
  GHookList.fromPointer(this.handle, {bool owned = false});
  final ffi.Pointer<ffi.Void> handle;

  /// Re-wraps this wrapper's [handle] as [T] via [factory].
  ///
  /// Use this when another wrapper returns this class's
  /// instance but the caller needs the destination class's
  /// methods. Pass the destination class's `fromPointer` as
  /// the callback, e.g. `wrapper.cast<GFile>(GFile.fromPointer)`.
  /// The handle is forwarded as-is; the original wrapper
  /// (which produced this object) remains the owner.
  T cast<T extends Object>(T Function(ffi.Pointer<ffi.Void>) factory) {
    return factory(handle);
  }

  /// Removes all the #GHook elements from a #GHookList.
  static final _gHookListClear =
      glibLookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'g_hook_list_clear',
      ).asFunction<void Function(ffi.Pointer<ffi.Void>)>();
  void clear() {
    _gHookListClear(this.handle);
  }

  /// Initializes a #GHookList.
  /// This must be called before the #GHookList is used.
  static final _gHookListInit =
      glibLookup<
            ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Uint32)
            >
          >('g_hook_list_init')
          .asFunction<void Function(ffi.Pointer<ffi.Void>, int)>();
  void init(int hookSize) {
    _gHookListInit(this.handle, hookSize);
  }

  /// Calls all of the #GHook functions in a #GHookList.
  static final _gHookListInvoke =
      glibLookup<
            ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Int32)
            >
          >('g_hook_list_invoke')
          .asFunction<void Function(ffi.Pointer<ffi.Void>, int)>();
  void invoke(bool mayRecurse) {
    _gHookListInvoke(this.handle, mayRecurse ? 1 : 0);
  }

  /// Calls all of the #GHook functions in a #GHookList.
  /// Any function which returns %FALSE is removed from the #GHookList.
  static final _gHookListInvokeCheck =
      glibLookup<
            ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Int32)
            >
          >('g_hook_list_invoke_check')
          .asFunction<void Function(ffi.Pointer<ffi.Void>, int)>();
  void invokeCheck(bool mayRecurse) {
    _gHookListInvokeCheck(this.handle, mayRecurse ? 1 : 0);
  }

  /// Calls a function on each valid #GHook.
  static final _gHookListMarshal =
      glibLookup<
            ffi.NativeFunction<
              ffi.Void Function(
                ffi.Pointer<ffi.Void>,
                ffi.Int32,
                ffi.Pointer<
                  ffi.NativeFunction<
                    ffi.Void Function(
                      ffi.Pointer<ffi.Void>,
                      ffi.Pointer<ffi.Void>,
                    )
                  >
                >,
                ffi.Pointer<ffi.Void>,
              )
            >
          >('g_hook_list_marshal')
          .asFunction<
            void Function(
              ffi.Pointer<ffi.Void>,
              int,
              ffi.Pointer<
                ffi.NativeFunction<
                  ffi.Void Function(
                    ffi.Pointer<ffi.Void>,
                    ffi.Pointer<ffi.Void>,
                  )
                >
              >,
              ffi.Pointer<ffi.Void>,
            )
          >();
  void marshal(
    bool mayRecurse,
    void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>) marshaller, [
    ffi.Pointer<ffi.Void>? marshalData,
  ]) {
    final _nc2 =
        ffi.NativeCallable<
          ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)
        >.isolateLocal(marshaller);
    try {
      _gHookListMarshal(
        this.handle,
        mayRecurse ? 1 : 0,
        _nc2.nativeFunction,
        marshalData ?? ffi.nullptr,
      );
    } finally {
      _nc2.close();
    }
  }

  /// Calls a function on each valid #GHook and destroys it if the
  /// function returns %FALSE.
  static final _gHookListMarshalCheck =
      glibLookup<
            ffi.NativeFunction<
              ffi.Void Function(
                ffi.Pointer<ffi.Void>,
                ffi.Int32,
                ffi.Pointer<
                  ffi.NativeFunction<
                    ffi.Int32 Function(
                      ffi.Pointer<ffi.Void>,
                      ffi.Pointer<ffi.Void>,
                    )
                  >
                >,
                ffi.Pointer<ffi.Void>,
              )
            >
          >('g_hook_list_marshal_check')
          .asFunction<
            void Function(
              ffi.Pointer<ffi.Void>,
              int,
              ffi.Pointer<
                ffi.NativeFunction<
                  ffi.Int32 Function(
                    ffi.Pointer<ffi.Void>,
                    ffi.Pointer<ffi.Void>,
                  )
                >
              >,
              ffi.Pointer<ffi.Void>,
            )
          >();
  void marshalCheck(
    bool mayRecurse,
    int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>) marshaller, [
    ffi.Pointer<ffi.Void>? marshalData,
  ]) {
    final _nc2 =
        ffi.NativeCallable<
          ffi.Int32 Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)
        >.isolateLocal(marshaller, exceptionalReturn: 0);
    try {
      _gHookListMarshalCheck(
        this.handle,
        mayRecurse ? 1 : 0,
        _nc2.nativeFunction,
        marshalData ?? ffi.nullptr,
      );
    } finally {
      _nc2.close();
    }
  }
}
