// Generated by gir_generator. Do not edit.
part of '../glib.dart';

/// The #GList struct is used for each element in a doubly-linked list.
final class GList {
  GList.fromPointer(this.handle);
  final ffi.Pointer<ffi.Void> handle;
  static final _gListPopAllocator =
      glibLookup<ffi.NativeFunction<ffi.Void Function()>>(
        'g_list_pop_allocator',
      ).asFunction<void Function()>();
  static void popAllocator() {
    _gListPopAllocator();
  }

  static final _gListPushAllocator =
      glibLookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'g_list_push_allocator',
      ).asFunction<void Function(ffi.Pointer<ffi.Void>)>();
  static void pushAllocator(GAllocator allocator) {
    _gListPushAllocator(allocator.handle);
  }
}

/// Structure representing a single field in a structured log entry. See
/// g_log_structured() for details.
///
/// Log fields may contain arbitrary values, including binary with embedded nul
/// bytes. If the field contains a string, the string must be UTF-8 encoded and
/// have a trailing nul byte. Otherwise, @length must be set to a non-negative
/// value.
final class GLogField {
  GLogField.fromPointer(this.handle);
  final ffi.Pointer<ffi.Void> handle;
}

/// The `GMainContext` struct is an opaque data
/// type representing a set of sources to be handled in a main loop.
final class GMainContext {
  GMainContext.fromPointer(this.handle);
  final ffi.Pointer<ffi.Void> handle;

  /// Creates a new [struct@GLib.MainContext] structure.
  static final _gMainContextNew =
      glibLookup<ffi.NativeFunction<ffi.Pointer<ffi.Void> Function()>>(
        'g_main_context_new',
      ).asFunction<ffi.Pointer<ffi.Void> Function()>();
  GMainContext() : this.fromPointer(_gMainContextNew());

  /// Creates a new [struct@GLib.MainContext] structure.
  static final _gMainContextNewWithFlags =
      glibLookup<
            ffi.NativeFunction<ffi.Pointer<ffi.Void> Function(ffi.Uint32)>
          >('g_main_context_new_with_flags')
          .asFunction<ffi.Pointer<ffi.Void> Function(int)>();
  GMainContext.withFlags(GMainContextFlags flags)
    : this.fromPointer(_gMainContextNewWithFlags(flags.value));

  /// Tries to become the owner of the specified context.
  ///
  /// If some other thread is the owner of the context,
  /// returns false immediately. Ownership is properly
  /// recursive: the owner can require ownership again
  /// and will release ownership when [method@GLib.MainContext.release]
  /// is called as many times as [method@GLib.MainContext.acquire].
  ///
  /// You must be the owner of a context before you
  /// can call [method@GLib.MainContext.prepare], [method@GLib.MainContext.query],
  /// [method@GLib.MainContext.check], [method@GLib.MainContext.dispatch],
  /// [method@GLib.MainContext.release].
  ///
  /// Since 2.76 @context can be `NULL` to use the global-default
  /// main context.
  static final _gMainContextAcquire =
      glibLookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Void>)>>(
        'g_main_context_acquire',
      ).asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  bool acquire() {
    return (_gMainContextAcquire(this.handle)) != 0;
  }

  /// Adds a file descriptor to the set of file descriptors polled for
  /// this context.
  ///
  /// This will very seldom be used directly. Instead
  /// a typical event source will use `g_source_add_unix_fd()` instead.
  static final _gMainContextAddPoll =
      glibLookup<
            ffi.NativeFunction<
              ffi.Void Function(
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Void>,
                ffi.Int32,
              )
            >
          >('g_main_context_add_poll')
          .asFunction<
            void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>, int)
          >();
  void addPoll(GPollFD fd, int priority) {
    _gMainContextAddPoll(this.handle, fd.handle, priority);
  }

  /// Dispatches all pending sources.
  ///
  /// You must have successfully acquired the context with
  /// [method@GLib.MainContext.acquire] before you may call this function.
  ///
  /// Since 2.76 @context can be `NULL` to use the global-default
  /// main context.
  static final _gMainContextDispatch =
      glibLookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'g_main_context_dispatch',
      ).asFunction<void Function(ffi.Pointer<ffi.Void>)>();
  void dispatch() {
    _gMainContextDispatch(this.handle);
  }

  /// Finds a source with the given source functions and user data.
  ///
  /// If multiple sources exist with the same source function and user data,
  /// the first one found will be returned.
  static final _gMainContextFindSourceByFuncsUserData =
      glibLookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Void>,
              )
            >
          >('g_main_context_find_source_by_funcs_user_data')
          .asFunction<
            ffi.Pointer<ffi.Void> Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Void>,
            )
          >();
  GSource? findSourceByFuncsUserData(
    GSourceFuncs funcs,
    ffi.Pointer<ffi.Void> userData,
  ) {
    return (_gMainContextFindSourceByFuncsUserData(
              this.handle,
              funcs.handle,
              userData,
            )) ==
            ffi.nullptr
        ? null
        : GSource.fromPointer(
            _gMainContextFindSourceByFuncsUserData(
              this.handle,
              funcs.handle,
              userData,
            ),
          );
  }

  /// Finds a [struct@GLib.Source] given a pair of context and ID.
  ///
  /// It is a programmer error to attempt to look up a non-existent source.
  ///
  /// More specifically: source IDs can be reissued after a source has been
  /// destroyed and therefore it is never valid to use this function with a
  /// source ID which may have already been removed.  An example is when
  /// scheduling an idle to run in another thread with [func@GLib.idle_add]: the
  /// idle may already have run and been removed by the time this function
  /// is called on its (now invalid) source ID.  This source ID may have
  /// been reissued, leading to the operation being performed against the
  /// wrong source.
  static final _gMainContextFindSourceById =
      glibLookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>, ffi.Uint32)
            >
          >('g_main_context_find_source_by_id')
          .asFunction<
            ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>, int)
          >();
  GSource findSourceById(int sourceId) {
    return GSource.fromPointer(
      _gMainContextFindSourceById(this.handle, sourceId),
    );
  }

  /// Finds a source with the given user data for the callback.
  ///
  /// If multiple sources exist with the same user data, the first
  /// one found will be returned.
  static final _gMainContextFindSourceByUserData =
      glibLookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Void>,
              )
            >
          >('g_main_context_find_source_by_user_data')
          .asFunction<
            ffi.Pointer<ffi.Void> Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Void>,
            )
          >();
  GSource? findSourceByUserData(ffi.Pointer<ffi.Void> userData) {
    return (_gMainContextFindSourceByUserData(this.handle, userData)) ==
            ffi.nullptr
        ? null
        : GSource.fromPointer(
            _gMainContextFindSourceByUserData(this.handle, userData),
          );
  }

  /// Invokes a function in such a way that @context is owned during the
  /// invocation of @function.
  ///
  /// This function is the same as [method@GLib.MainContext.invoke] except that it
  /// lets you specify the priority in case @function ends up being
  /// scheduled as an idle and also lets you give a [callback@GLib.DestroyNotify]
  /// for @data.
  ///
  /// The @notify function should not assume that it is called from any particular
  /// thread or with any particular context acquired.
  static final _gMainContextInvokeFull =
      glibLookup<
            ffi.NativeFunction<
              ffi.Void Function(
                ffi.Pointer<ffi.Void>,
                ffi.Int32,
                ffi.Pointer<
                  ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Void>)>
                >,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<
                  ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>
                >,
              )
            >
          >('g_main_context_invoke_full')
          .asFunction<
            void Function(
              ffi.Pointer<ffi.Void>,
              int,
              ffi.Pointer<
                ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Void>)>
              >,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<
                ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>
              >,
            )
          >();
  void invokeFull(
    int priority,
    int Function(ffi.Pointer<ffi.Void>) function_,
    ffi.Pointer<ffi.Void> data, [
    void Function(ffi.Pointer<ffi.Void>)? notify,
  ]) {
    final _nc2 =
        ffi.NativeCallable<
          ffi.Int32 Function(ffi.Pointer<ffi.Void>)
        >.isolateLocal(function_, exceptionalReturn: 0);
    final _nc4 = notify == null
        ? null
        : ffi.NativeCallable<
            ffi.Void Function(ffi.Pointer<ffi.Void>)
          >.isolateLocal(notify);
    try {
      _gMainContextInvokeFull(
        this.handle,
        priority,
        _nc2.nativeFunction,
        data,
        _nc4?.nativeFunction ?? ffi.nullptr,
      );
    } finally {
      _nc2.close();
      _nc4?.close();
    }
  }

  /// Determines whether this thread holds the (recursive)
  /// ownership of this [struct@GLib.MainContext].
  ///
  /// This is useful to
  /// know before waiting on another thread that may be
  /// blocking to get ownership of @context.
  static final _gMainContextIsOwner =
      glibLookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Void>)>>(
        'g_main_context_is_owner',
      ).asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  bool isOwner() {
    return (_gMainContextIsOwner(this.handle)) != 0;
  }

  /// Runs a single iteration for the given main loop.
  ///
  /// This involves
  /// checking to see if any event sources are ready to be processed,
  /// then if no events sources are ready and @may_block is true, waiting
  /// for a source to become ready, then dispatching the highest priority
  /// events sources that are ready. Otherwise, if @may_block is false,
  /// this function does not wait for sources to become ready, and only the highest
  /// priority sources which are already ready (if any) will be dispatched.
  ///
  /// Note that even when @may_block is true, it is still possible for
  /// [method@GLib.MainContext.iteration] to return false, since the wait may
  /// be interrupted for other reasons than an event source becoming ready.
  static final _gMainContextIteration =
      glibLookup<
            ffi.NativeFunction<
              ffi.Int32 Function(ffi.Pointer<ffi.Void>, ffi.Int32)
            >
          >('g_main_context_iteration')
          .asFunction<int Function(ffi.Pointer<ffi.Void>, int)>();
  bool iteration(bool mayBlock) {
    return (_gMainContextIteration(this.handle, mayBlock ? 1 : 0)) != 0;
  }

  /// Checks if any sources have pending events for the given context.
  static final _gMainContextPending =
      glibLookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Void>)>>(
        'g_main_context_pending',
      ).asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  bool pending() {
    return (_gMainContextPending(this.handle)) != 0;
  }

  /// Pops @context off the thread-default context stack (verifying that
  /// it was on the top of the stack).
  static final _gMainContextPopThreadDefault =
      glibLookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'g_main_context_pop_thread_default',
      ).asFunction<void Function(ffi.Pointer<ffi.Void>)>();
  void popThreadDefault() {
    _gMainContextPopThreadDefault(this.handle);
  }

  /// Acquires @context and sets it as the thread-default context for the
  /// current thread. This will cause certain asynchronous operations
  /// (such as most [Gio](../gio/index.html)-based I/O) which are
  /// started in this thread to run under @context and deliver their
  /// results to its main loop, rather than running under the global
  /// default main context in the main thread. Note that calling this function
  /// changes the context returned by [func@GLib.MainContext.get_thread_default],
  /// not the one returned by [func@GLib.MainContext.default], so it does not
  /// affect the context used by functions like [func@GLib.idle_add].
  ///
  /// Normally you would call this function shortly after creating a new
  /// thread, passing it a [struct@GLib.MainContext] which will be run by a
  /// [struct@GLib.MainLoop] in that thread, to set a new default context for all
  /// async operations in that thread. In this case you may not need to
  /// ever call [method@GLib.MainContext.pop_thread_default], assuming you want
  /// the new [struct@GLib.MainContext] to be the default for the whole lifecycle
  /// of the thread.
  ///
  /// If you don’t have control over how the new thread was created (e.g.
  /// in the new thread isn’t newly created, or if the thread life
  /// cycle is managed by a #GThreadPool), it is always suggested to wrap
  /// the logic that needs to use the new [struct@GLib.MainContext] inside a
  /// [method@GLib.MainContext.push_thread_default] /
  /// [method@GLib.MainContext.pop_thread_default] pair, otherwise threads that
  /// are re-used will end up never explicitly releasing the
  /// [struct@GLib.MainContext] reference they hold.
  ///
  /// In some cases you may want to schedule a single operation in a
  /// non-default context, or temporarily use a non-default context in
  /// the main thread. In that case, you can wrap the call to the
  /// asynchronous operation inside a
  /// [method@GLib.MainContext.push_thread_default] /
  /// [method@GLib.MainContext.pop_thread_default] pair, but it is up to you to
  /// ensure that no other asynchronous operations accidentally get
  /// started while the non-default context is active.
  ///
  /// Beware that libraries that predate this function may not correctly
  /// handle being used from a thread with a thread-default context. For example,
  /// see `g_file_supports_thread_contexts()`.
  static final _gMainContextPushThreadDefault =
      glibLookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'g_main_context_push_thread_default',
      ).asFunction<void Function(ffi.Pointer<ffi.Void>)>();
  void pushThreadDefault() {
    _gMainContextPushThreadDefault(this.handle);
  }

  /// Push @main_context as the new thread-default main context for the current
  /// thread, using [method@GLib.MainContext.push_thread_default], and return a
  /// new [alias@GLib.MainContextPusher]. Pop with g_main_context_pusher_free().
  /// Using [method@GLib.MainContext.pop_thread_default] on @main_context while a
  /// [alias@GLib.MainContextPusher] exists for it can lead to undefined behaviour.
  ///
  /// Using two [alias@GLib.MainContextPusher]s in the same scope is not allowed,
  /// as it leads to an undefined pop order.
  ///
  /// This is intended to be used with g_autoptr().  Note that g_autoptr()
  /// is only available when using GCC or clang, so the following example
  /// will only work with those compilers:
  /// |[
  /// typedef struct
  /// {
  /// ...
  /// GMainContext *context;
  /// ...
  /// } MyObject;
  ///
  /// static void
  /// my_object_do_stuff (MyObject *self)
  /// {
  /// g_autoptr(GMainContextPusher) pusher = g_main_context_pusher_new (self->context);
  ///
  /// // Code with main context as the thread default here
  ///
  /// if (cond)
  /// // No need to pop
  /// return;
  ///
  /// // Optionally early pop
  /// g_clear_pointer (&pusher, g_main_context_pusher_free);
  ///
  /// // Code with main context no longer the thread default here
  /// }
  /// ]|
  static final _gMainContextPusherNew =
      glibLookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'g_main_context_pusher_new',
      ).asFunction<void Function(ffi.Pointer<ffi.Void>)>();
  void pusherNew() {
    _gMainContextPusherNew(this.handle);
  }

  /// Increases the reference count on a [struct@GLib.MainContext] object by one.
  static final _gMainContextRef =
      glibLookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)
            >
          >('g_main_context_ref')
          .asFunction<ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)>();
  GMainContext ref() {
    return GMainContext.fromPointer(_gMainContextRef(this.handle));
  }

  /// Releases ownership of a context previously acquired by this thread
  /// with [method@GLib.MainContext.acquire].
  ///
  /// If the context was acquired multiple
  /// times, the ownership will be released only when [method@GLib.MainContext.release]
  /// is called as many times as it was acquired.
  ///
  /// You must have successfully acquired the context with
  /// [method@GLib.MainContext.acquire] before you may call this function.
  static final _gMainContextRelease =
      glibLookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'g_main_context_release',
      ).asFunction<void Function(ffi.Pointer<ffi.Void>)>();
  void release() {
    _gMainContextRelease(this.handle);
  }

  /// Removes file descriptor from the set of file descriptors to be
  /// polled for a particular context.
  static final _gMainContextRemovePoll =
      glibLookup<
            ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)
            >
          >('g_main_context_remove_poll')
          .asFunction<
            void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)
          >();
  void removePoll(GPollFD fd) {
    _gMainContextRemovePoll(this.handle, fd.handle);
  }

  /// Decreases the reference count on a [struct@GLib.MainContext] object by one.
  /// If
  /// the result is zero, free the context and free all associated memory.
  static final _gMainContextUnref =
      glibLookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'g_main_context_unref',
      ).asFunction<void Function(ffi.Pointer<ffi.Void>)>();
  void unref() {
    _gMainContextUnref(this.handle);
  }

  /// Tries to become the owner of the specified context, and waits on @cond if
  /// another thread is the owner.
  ///
  /// This is the same as [method@GLib.MainContext.acquire], but if another thread
  /// is the owner, atomically drop @mutex and wait on @cond until
  /// that owner releases ownership or until @cond is signaled, then
  /// try again (once) to become the owner.
  static final _gMainContextWait =
      glibLookup<
            ffi.NativeFunction<
              ffi.Int32 Function(
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Void>,
              )
            >
          >('g_main_context_wait')
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Void>,
            )
          >();
  bool wait(GCond cond, GMutex mutex) {
    return (_gMainContextWait(this.handle, cond.handle, mutex.handle)) != 0;
  }

  /// Wake up @context if it’s currently blocking in
  /// [method@GLib.MainContext.iteration], causing it to stop blocking.
  ///
  /// The @context could be blocking waiting for a source to become ready.
  /// Otherwise, if @context is not currently blocking, this function causes the
  /// next invocation of [method@GLib.MainContext.iteration] to return without
  /// blocking.
  ///
  /// This API is useful for low-level control over [struct@GLib.MainContext]; for
  /// example, integrating it with main loop implementations such as
  /// [struct@GLib.MainLoop].
  ///
  /// Another related use for this function is when implementing a main
  /// loop with a termination condition, computed from multiple threads:
  ///
  /// ```c
  /// #define NUM_TASKS 10
  /// static gint tasks_remaining = NUM_TASKS;  // (atomic)
  /// ...
  ///
  /// while (g_atomic_int_get (&tasks_remaining) != 0)
  /// g_main_context_iteration (NULL, TRUE);
  /// ```
  ///
  /// Then in a thread:
  /// ```c
  /// perform_work ();
  ///
  /// if (g_atomic_int_dec_and_test (&tasks_remaining))
  /// g_main_context_wakeup (NULL);
  /// ```
  static final _gMainContextWakeup =
      glibLookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'g_main_context_wakeup',
      ).asFunction<void Function(ffi.Pointer<ffi.Void>)>();
  void wakeup() {
    _gMainContextWakeup(this.handle);
  }

  /// Returns the global-default main context.
  ///
  /// This is the main context
  /// used for main loop functions when a main loop is not explicitly
  /// specified, and corresponds to the ‘main’ main loop. See also
  /// [func@GLib.MainContext.get_thread_default].
  static final _gMainContextDefault =
      glibLookup<ffi.NativeFunction<ffi.Pointer<ffi.Void> Function()>>(
        'g_main_context_default',
      ).asFunction<ffi.Pointer<ffi.Void> Function()>();
  static GMainContext default_() {
    return GMainContext.fromPointer(_gMainContextDefault());
  }

  /// Gets the thread-default main context for this thread.
  ///
  /// Asynchronous operations that want to be able to be run in contexts other than
  /// the default one should call this method or
  /// [func@GLib.MainContext.ref_thread_default] to get a
  /// [struct@GLib.MainContext] to add their [struct@GLib.Source]s to. (Note that
  /// even in single-threaded programs applications may sometimes want to
  /// temporarily push a non-default context, so it is not safe to assume that
  /// this will always return `NULL` if you are running in the default thread.)
  ///
  /// If you need to hold a reference on the context, use
  /// [func@GLib.MainContext.ref_thread_default] instead.
  static final _gMainContextGetThreadDefault =
      glibLookup<ffi.NativeFunction<ffi.Pointer<ffi.Void> Function()>>(
        'g_main_context_get_thread_default',
      ).asFunction<ffi.Pointer<ffi.Void> Function()>();
  static GMainContext? getThreadDefault() {
    return (_gMainContextGetThreadDefault()) == ffi.nullptr
        ? null
        : GMainContext.fromPointer(_gMainContextGetThreadDefault());
  }

  /// Gets a reference to the thread-default [struct@GLib.MainContext] for this
  /// thread
  ///
  /// This is the same as [func@GLib.MainContext.get_thread_default], but it also
  /// adds a reference to the returned main context with [method@GLib.MainContext.ref].
  /// In addition, unlike
  /// [func@GLib.MainContext.get_thread_default], if the thread-default context
  /// is the global-default context, this will return that
  /// [struct@GLib.MainContext] (with a ref added to it) rather than returning
  /// `NULL`.
  static final _gMainContextRefThreadDefault =
      glibLookup<ffi.NativeFunction<ffi.Pointer<ffi.Void> Function()>>(
        'g_main_context_ref_thread_default',
      ).asFunction<ffi.Pointer<ffi.Void> Function()>();
  static GMainContext refThreadDefault() {
    return GMainContext.fromPointer(_gMainContextRefThreadDefault());
  }
}
