// Generated by gir_generator. Do not edit.
part of '../gsk4.dart';

/// A render node using a GL shader when drawing its children nodes.
class GskGLShaderNode extends GskRenderNode {
  GskGLShaderNode.fromPointer(super.handle, {super.owned})
    : super.fromPointer();

  /// Re-wraps this wrapper's [handle] as [T] via [factory].
  ///
  /// Use this when another wrapper returns this class's
  /// instance but the caller needs the destination class's
  /// methods. Pass the destination class's `fromPointer` as
  /// the callback, e.g. `wrapper.cast<GFile>(GFile.fromPointer)`.
  /// The handle is forwarded as-is; the original wrapper
  /// (which produced this object) remains the owner.
  T cast<T extends Object>(T Function(ffi.Pointer<ffi.Void>) factory) {
    return factory(handle);
  }

  /// Creates a `GskRenderNode` that will render the given @shader into the
  /// area given by @bounds.
  ///
  /// The @args is a block of data to use for uniform input, as per types and
  /// offsets defined by the @shader. Normally this is generated by
  /// [method@Gsk.GLShader.format_args] or [struct@Gsk.ShaderArgsBuilder].
  ///
  /// See [class@Gsk.GLShader] for details about how the shader should be written.
  ///
  /// All the children will be rendered into textures (if they aren't already
  /// `GskTextureNodes`, which will be used directly). These textures will be
  /// sent as input to the shader.
  ///
  /// If the renderer doesn't support GL shaders, or if there is any problem
  /// when compiling the shader, then the node will draw pink. You should use
  /// [method@Gsk.GLShader.compile] to ensure the @shader will work for the
  /// renderer before using it.
  static final _gskGlShaderNodeNew =
      gsk4Lookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Void>,
                ffi.Uint32,
              )
            >
          >('gsk_gl_shader_node_new')
          .asFunction<
            ffi.Pointer<ffi.Void> Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Void>,
              int,
            )
          >();
  GskGLShaderNode(
    GskGLShader shader,
    GrapheneRect bounds,
    GBytes args,
    ffi.Pointer<ffi.Void> children,
    int nChildren,
  ) : this.fromPointer(
        _gskGlShaderNodeNew(
          shader.handle,
          bounds.handle,
          args.handle,
          children,
          nChildren,
        ),
        owned: true,
      );

  /// Gets args for the node.
  static final _gskGlShaderNodeGetArgs =
      gsk4Lookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)
            >
          >('gsk_gl_shader_node_get_args')
          .asFunction<ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)>();
  GBytes getArgs() {
    return GBytes.fromPointer(_gskGlShaderNodeGetArgs(this.handle));
  }

  /// Gets one of the children.
  static final _gskGlShaderNodeGetChild =
      gsk4Lookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>, ffi.Uint32)
            >
          >('gsk_gl_shader_node_get_child')
          .asFunction<
            ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>, int)
          >();
  GskRenderNode getChild(int idx) {
    return GskRenderNode.fromPointer(
      _gskGlShaderNodeGetChild(this.handle, idx),
    );
  }

  /// Returns the number of children
  static final _gskGlShaderNodeGetNChildren =
      gsk4Lookup<
            ffi.NativeFunction<ffi.Uint32 Function(ffi.Pointer<ffi.Void>)>
          >('gsk_gl_shader_node_get_n_children')
          .asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  int getNChildren() {
    return _gskGlShaderNodeGetNChildren(this.handle);
  }

  /// Gets shader code for the node.
  static final _gskGlShaderNodeGetShader =
      gsk4Lookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)
            >
          >('gsk_gl_shader_node_get_shader')
          .asFunction<ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)>();
  GskGLShader getShader() {
    return GskGLShader.fromPointer(_gskGlShaderNodeGetShader(this.handle));
  }
}
