// Generated by gir_generator. Do not edit.
part of '../gsk4.dart';

/// A render node for a linear gradient.
class GskLinearGradientNode extends GskRenderNode {
  GskLinearGradientNode.fromPointer(super.handle, {super.owned})
    : super.fromPointer();

  /// Creates a `GskRenderNode` that will create a linear gradient from the given
  /// points and color stops, and render that into the area given by @bounds.
  static final _gskLinearGradientNodeNew =
      gsk4Lookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Void>,
                ffi.Size,
              )
            >
          >('gsk_linear_gradient_node_new')
          .asFunction<
            ffi.Pointer<ffi.Void> Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Void>,
              int,
            )
          >();
  factory GskLinearGradientNode(
    GrapheneRect bounds,
    GraphenePoint start,
    GraphenePoint end,
    ffi.Pointer<ffi.Void> colorStops,
    int nColorStops,
  ) {
    return GskLinearGradientNode.fromPointer(
      _gskLinearGradientNodeNew(
        bounds.handle,
        start.handle,
        end.handle,
        colorStops,
        nColorStops,
      ),
      owned: true,
    );
  }

  /// Retrieves the final point of the linear gradient.
  static final _gskLinearGradientNodeGetEnd =
      gsk4Lookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)
            >
          >('gsk_linear_gradient_node_get_end')
          .asFunction<ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)>();
  GraphenePoint getEnd() {
    return GraphenePoint.fromPointer(_gskLinearGradientNodeGetEnd(this.handle));
  }

  /// Retrieves the number of color stops in the gradient.
  static final _gskLinearGradientNodeGetNColorStops =
      gsk4Lookup<ffi.NativeFunction<ffi.Size Function(ffi.Pointer<ffi.Void>)>>(
        'gsk_linear_gradient_node_get_n_color_stops',
      ).asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  int getNColorStops() {
    return _gskLinearGradientNodeGetNColorStops(this.handle);
  }

  /// Retrieves the initial point of the linear gradient.
  static final _gskLinearGradientNodeGetStart =
      gsk4Lookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)
            >
          >('gsk_linear_gradient_node_get_start')
          .asFunction<ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)>();
  GraphenePoint getStart() {
    return GraphenePoint.fromPointer(
      _gskLinearGradientNodeGetStart(this.handle),
    );
  }
}
