// Generated by gir_generator. Do not edit.
part of '../gsk4.dart';

/// A render node for a paste.
class GskPasteNode extends GskRenderNode {
  GskPasteNode.fromPointer(super.handle, {super.owned}) : super.fromPointer();

  /// Creates a `GskRenderNode` that will paste copied contents.
  static final _gskPasteNodeNew =
      gsk4Lookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>, ffi.Size)
            >
          >('gsk_paste_node_new')
          .asFunction<
            ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>, int)
          >();
  GskPasteNode(GrapheneRect bounds, int depth)
    : super.fromPointer(_gskPasteNodeNew(bounds.handle, depth), owned: true);

  /// Retrieves the index of the copy that should be pasted.
  static final _gskPasteNodeGetDepth =
      gsk4Lookup<ffi.NativeFunction<ffi.Size Function(ffi.Pointer<ffi.Void>)>>(
        'gsk_paste_node_get_depth',
      ).asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  int getDepth() {
    return _gskPasteNodeGetDepth(this.handle);
  }
}
