// Generated by gir_generator. Do not edit.
part of '../adw.dart';

/// PyGObject-style typed property accessor. Each getter
/// and setter delegates to the existing typed
/// `get<Name>` / `set<Name>` methods on [AdwStyleManager].
///
/// Skipped properties (unsupported type, missing getter
/// or setter) are recorded in the generation report.
class AdwStyleManagerProps {
  AdwStyleManagerProps(this._self);
  final AdwStyleManager _self;

  AdwAccentColor get accentColor => _self.getAccentColor();

  GdkRGBA get accentColorRgba => _self.getAccentColorRgba();

  AdwColorScheme get colorScheme => _self.getColorScheme();
  set colorScheme(AdwColorScheme value) {
    _self.setColorScheme(value);
  }

  bool get dark => _self.getDark();

  GdkDisplay? get display => _self.getDisplay();

  String get documentFontName => _self.getDocumentFontName();

  bool get highContrast => _self.getHighContrast();

  String get monospaceFontName => _self.getMonospaceFontName();

  bool get systemSupportsAccentColors => _self.getSystemSupportsAccentColors();

  bool get systemSupportsColorSchemes => _self.getSystemSupportsColorSchemes();
}
