// Generated by gir_generator. Do not edit.
part of '../adw.dart';

/// A page-based navigation container.
///
/// <picture>
/// <source srcset="navigation-view-dark.png" media="(prefers-color-scheme: dark)">
/// <img src="navigation-view.png" alt="navigation-view">
/// </picture>
///
/// `AdwNavigationView` presents one child at a time, similar to
/// [class@Gtk.Stack].
///
/// `AdwNavigationView` can only contain [class@NavigationPage] children.
///
/// It maintains a navigation stack that can be controlled with
/// [method@NavigationView.push] and [method@NavigationView.pop]. The whole
/// navigation stack can also be replaced using [method@NavigationView.replace].
///
/// `AdwNavigationView` allows to manage pages statically or dynamically.
///
/// Static pages can be added using the [method@NavigationView.add] method. The
/// `AdwNavigationView` will keep a reference to these pages, but they aren't
/// accessible to the user until [method@NavigationView.push] is called (except
/// for the first page, which is pushed automatically). Use the
/// [method@NavigationView.remove] method to remove them. This is useful for
/// applications that have a small number of unique pages and just need
/// navigation between them.
///
/// Dynamic pages are automatically destroyed once they are popped off the
/// navigation stack. To add a page like this, push it using the
/// [method@NavigationView.push] method without calling
/// [method@NavigationView.add] first.
///
/// ## Tags
///
/// Static pages, as well as any pages in the navigation stack, can be accessed
/// by their [property@NavigationPage:tag]. For example,
/// [method@NavigationView.push_by_tag] can be used to push a static page that's
/// not in the navigation stack without having to keep a reference to it manually.
///
/// ## Header Bar Integration
///
/// When used inside `AdwNavigationView`, [class@HeaderBar] will automatically
/// display a back button that can be used to go back to the previous page when
/// possible. The button also has a context menu, allowing to pop multiple pages
/// at once, potentially across multiple navigation views.
///
/// Set [property@HeaderBar:show-back-button] to `FALSE` to disable this behavior
/// in rare scenarios where it's unwanted.
///
/// `AdwHeaderBar` will also display the title of the `AdwNavigationPage` it's
/// placed into, so most applications shouldn't need to customize it at all.
///
/// ## Shortcuts and Gestures
///
/// `AdwNavigationView` supports the following shortcuts for going to the
/// previous page:
///
/// - <kbd>Escape</kbd> (unless [property@NavigationView:pop-on-escape] is set to
/// `FALSE`)
/// - <kbd>Alt</kbd>+<kbd>←</kbd>
/// - Back mouse button
///
/// Additionally, it supports interactive gestures:
///
/// - One-finger swipe towards the right on touchscreens
/// - Scrolling towards the right on touchpads (usually two-finger swipe)
///
/// These gestures have transitions enabled regardless of the
/// [property@NavigationView:animate-transitions] value.
///
/// Applications can also enable shortcuts for pushing another page onto the
/// navigation stack via connecting to the [signal@NavigationView::get-next-page]
/// signal, in that case the following shortcuts are supported:
///
/// - <kbd>Alt</kbd>+<kbd>→</kbd>
/// - Forward mouse button
/// - Swipe/scrolling towards the left
///
/// For right-to-left locales, the gestures and shortcuts are reversed.
///
/// [property@NavigationPage:can-pop] can be used to disable them, along with the
/// header bar back buttons.
///
/// ## Actions
///
/// `AdwNavigationView` defines actions for controlling the navigation stack.
/// actions for controlling the navigation stack:
///
/// - `navigation.push` takes a string parameter specifying the tag of the page to
/// push, and is equivalent to calling [method@NavigationView.push_by_tag].
///
/// - `navigation.pop` doesn't take any parameters and pops the current page from
/// the navigation stack, equivalent to calling [method@NavigationView.pop].
///
/// ## `AdwNavigationView` as `GtkBuildable`
///
/// `AdwNavigationView` allows to add pages as children, equivalent to using the
/// [method@NavigationView.add] method.
///
/// Example of an `AdwNavigationView` UI definition:
///
/// ```xml
/// <object class="AdwNavigationView">
/// <child>
/// <object class="AdwNavigationPage">
/// <property name="title" translatable="yes">Page 1</property>
/// <property name="child">
/// <object class="AdwToolbarView">
/// <child type="top">
/// <object class="AdwHeaderBar"/>
/// </child>
/// <property name="content">
/// <object class="GtkButton">
/// <property name="label" translatable="yes">Open Page 2</property>
/// <property name="halign">center</property>
/// <property name="valign">center</property>
/// <property name="action-name">navigation.push</property>
/// <property name="action-target">'page-2'</property>
/// <style>
/// <class name="pill"/>
/// </style>
/// </object>
/// </property>
/// </object>
/// </property>
/// </object>
/// </child>
/// <child>
/// <object class="AdwNavigationPage">
/// <property name="title" translatable="yes">Page 2</property>
/// <property name="tag">page-2</property>
/// <property name="child">
/// <object class="AdwToolbarView">
/// <child type="top">
/// <object class="AdwHeaderBar"/>
/// </child>
/// <property name="content">
/// <!-- ... -->
/// </property>
/// </object>
/// </property>
/// </object>
/// </child>
/// </object>
/// ```
///
/// <picture>
/// <source srcset="navigation-view-example-dark.png" media="(prefers-color-scheme: dark)">
/// <img src="navigation-view-example.png" alt="navigation-view-example">
/// </picture>
///
/// ## CSS nodes
///
/// `AdwNavigationView` has a single CSS node with the name `navigation-view`.
///
/// ## Accessibility
///
/// `AdwNavigationView` uses the [enum@Gtk.AccessibleRole.group] role.
class AdwNavigationView extends GtkWidget {
  AdwNavigationView.fromPointer(super.handle, {super.owned})
    : super.fromPointer();

  /// Creates a new `AdwNavigationView`.
  static final _adwNavigationViewNew =
      adwLookup<ffi.NativeFunction<ffi.Pointer<ffi.Void> Function()>>(
        'adw_navigation_view_new',
      ).asFunction<ffi.Pointer<ffi.Void> Function()>();
  factory AdwNavigationView() {
    return AdwNavigationView.fromPointer(
      gObjectRefSink(_adwNavigationViewNew()),
      owned: true,
    );
  }

  /// Permanently adds @page to @self.
  ///
  /// Any page that has been added will stay in @self even after being popped from
  /// the navigation stack.
  ///
  /// Adding a page while no page is visible will automatically push it to the
  /// navigation stack.
  ///
  /// See [method@NavigationView.remove].
  static final _adwNavigationViewAdd =
      adwLookup<
            ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)
            >
          >('adw_navigation_view_add')
          .asFunction<
            void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)
          >();
  void add(AdwNavigationPage page) {
    _adwNavigationViewAdd(this.handle, page.handle);
  }

  /// Finds a page in @self by its tag.
  ///
  /// See [property@NavigationPage:tag].
  static final _adwNavigationViewFindPage =
      adwLookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<Utf8>,
              )
            >
          >('adw_navigation_view_find_page')
          .asFunction<
            ffi.Pointer<ffi.Void> Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<Utf8>,
            )
          >();
  AdwNavigationPage? findPage(String tag) {
    return withNativeString(tag, (nativeTag) {
      return (_adwNavigationViewFindPage(
                this.handle,
                nativeTag.cast<Utf8>(),
              )) ==
              ffi.nullptr
          ? null
          : AdwNavigationPage.fromPointer(
              _adwNavigationViewFindPage(this.handle, nativeTag.cast<Utf8>()),
            );
    });
  }

  /// Gets whether @self animates page transitions.
  static final _adwNavigationViewGetAnimateTransitions =
      adwLookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Void>)>>(
        'adw_navigation_view_get_animate_transitions',
      ).asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  bool getAnimateTransitions() {
    return (_adwNavigationViewGetAnimateTransitions(this.handle)) != 0;
  }

  /// Gets whether @self is horizontally homogeneous.
  static final _adwNavigationViewGetHhomogeneous =
      adwLookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Void>)>>(
        'adw_navigation_view_get_hhomogeneous',
      ).asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  bool getHhomogeneous() {
    return (_adwNavigationViewGetHhomogeneous(this.handle)) != 0;
  }

  /// Returns a [iface@Gio.ListModel] that contains the pages in navigation stack.
  ///
  /// The pages are sorted from root page to visible page.
  ///
  /// This can be used to keep an up-to-date view.
  static final _adwNavigationViewGetNavigationStack =
      adwLookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)
            >
          >('adw_navigation_view_get_navigation_stack')
          .asFunction<ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)>();
  GListModel getNavigationStack() {
    return GListModel.fromPointer(
      _adwNavigationViewGetNavigationStack(this.handle),
    );
  }

  /// Gets whether pressing Escape pops the current page on @self.
  static final _adwNavigationViewGetPopOnEscape =
      adwLookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Void>)>>(
        'adw_navigation_view_get_pop_on_escape',
      ).asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  bool getPopOnEscape() {
    return (_adwNavigationViewGetPopOnEscape(this.handle)) != 0;
  }

  /// Gets the previous page for @page.
  ///
  /// If @page is in the navigation stack, returns the page popping @page will
  /// reveal.
  ///
  /// If @page is the root page or is not in the navigation stack, returns `NULL`.
  static final _adwNavigationViewGetPreviousPage =
      adwLookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Void>,
              )
            >
          >('adw_navigation_view_get_previous_page')
          .asFunction<
            ffi.Pointer<ffi.Void> Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Void>,
            )
          >();
  AdwNavigationPage? getPreviousPage(AdwNavigationPage page) {
    return (_adwNavigationViewGetPreviousPage(this.handle, page.handle)) ==
            ffi.nullptr
        ? null
        : AdwNavigationPage.fromPointer(
            _adwNavigationViewGetPreviousPage(this.handle, page.handle),
          );
  }

  /// Gets whether @self is vertically homogeneous.
  static final _adwNavigationViewGetVhomogeneous =
      adwLookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Void>)>>(
        'adw_navigation_view_get_vhomogeneous',
      ).asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  bool getVhomogeneous() {
    return (_adwNavigationViewGetVhomogeneous(this.handle)) != 0;
  }

  /// Gets the currently visible page in @self.
  static final _adwNavigationViewGetVisiblePage =
      adwLookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)
            >
          >('adw_navigation_view_get_visible_page')
          .asFunction<ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)>();
  AdwNavigationPage? getVisiblePage() {
    return (_adwNavigationViewGetVisiblePage(this.handle)) == ffi.nullptr
        ? null
        : AdwNavigationPage.fromPointer(
            _adwNavigationViewGetVisiblePage(this.handle),
          );
  }

  /// Gets the tag of the currently visible page in @self.
  static final _adwNavigationViewGetVisiblePageTag =
      adwLookup<
            ffi.NativeFunction<
              ffi.Pointer<Utf8> Function(ffi.Pointer<ffi.Void>)
            >
          >('adw_navigation_view_get_visible_page_tag')
          .asFunction<ffi.Pointer<Utf8> Function(ffi.Pointer<ffi.Void>)>();
  String? getVisiblePageTag() {
    return stringFromNative(
      (_adwNavigationViewGetVisiblePageTag(this.handle)).cast(),
      free: false,
    );
  }

  /// Pops the visible page from the navigation stack.
  ///
  /// Does nothing if the navigation stack contains less than two pages.
  ///
  /// If [method@NavigationView.add] hasn't been called, the page is automatically
  /// removed.
  ///
  /// [signal@NavigationView::popped] will be emitted for the current visible page.
  ///
  /// See [method@NavigationView.pop_to_page] and
  /// [method@NavigationView.pop_to_tag].
  static final _adwNavigationViewPop =
      adwLookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Void>)>>(
        'adw_navigation_view_pop',
      ).asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  bool pop() {
    return (_adwNavigationViewPop(this.handle)) != 0;
  }

  /// Pops pages from the navigation stack until @page is visible.
  ///
  /// @page must be in the navigation stack.
  ///
  /// If [method@NavigationView.add] hasn't been called for any of the popped pages,
  /// they are automatically removed.
  ///
  /// [signal@NavigationView::popped] will be be emitted for each of the popped
  /// pages.
  ///
  /// See [method@NavigationView.pop] and [method@NavigationView.pop_to_tag].
  static final _adwNavigationViewPopToPage =
      adwLookup<
            ffi.NativeFunction<
              ffi.Int32 Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)
            >
          >('adw_navigation_view_pop_to_page')
          .asFunction<
            int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)
          >();
  bool popToPage(AdwNavigationPage page) {
    return (_adwNavigationViewPopToPage(this.handle, page.handle)) != 0;
  }

  /// Pops pages from the navigation stack until page with the tag @tag is visible.
  ///
  /// The page must be in the navigation stack.
  ///
  /// If [method@NavigationView.add] hasn't been called for any of the popped pages,
  /// they are automatically removed.
  ///
  /// [signal@NavigationView::popped] will be emitted for each of the popped pages.
  ///
  /// See [method@NavigationView.pop_to_page] and [property@NavigationPage:tag].
  static final _adwNavigationViewPopToTag =
      adwLookup<
            ffi.NativeFunction<
              ffi.Int32 Function(ffi.Pointer<ffi.Void>, ffi.Pointer<Utf8>)
            >
          >('adw_navigation_view_pop_to_tag')
          .asFunction<int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<Utf8>)>();
  bool popToTag(String tag) {
    return withNativeString(tag, (nativeTag) {
      return (_adwNavigationViewPopToTag(
            this.handle,
            nativeTag.cast<Utf8>(),
          )) !=
          0;
    });
  }

  /// Pushes @page onto the navigation stack.
  ///
  /// If [method@NavigationView.add] hasn't been called, the page is automatically
  /// removed once it's popped.
  ///
  /// [signal@NavigationView::pushed] will be emitted for @page.
  ///
  /// See [method@NavigationView.push_by_tag].
  static final _adwNavigationViewPush =
      adwLookup<
            ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)
            >
          >('adw_navigation_view_push')
          .asFunction<
            void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)
          >();
  void push(AdwNavigationPage page) {
    _adwNavigationViewPush(this.handle, page.handle);
  }

  /// Pushes the page with the tag @tag onto the navigation stack.
  ///
  /// If [method@NavigationView.add] hasn't been called, the page is automatically
  /// removed once it's popped.
  ///
  /// [signal@NavigationView::pushed] will be emitted for the page.
  ///
  /// See [method@NavigationView.push] and [property@NavigationPage:tag].
  static final _adwNavigationViewPushByTag =
      adwLookup<
            ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<Utf8>)
            >
          >('adw_navigation_view_push_by_tag')
          .asFunction<
            void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<Utf8>)
          >();
  void pushByTag(String tag) {
    withNativeString(tag, (nativeTag) {
      _adwNavigationViewPushByTag(this.handle, nativeTag.cast<Utf8>());
    });
  }

  /// Removes @page from @self.
  ///
  /// If @page is currently in the navigation stack, it will be removed once it's
  /// popped. Otherwise, it's removed immediately.
  ///
  /// See [method@NavigationView.add].
  static final _adwNavigationViewRemove =
      adwLookup<
            ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)
            >
          >('adw_navigation_view_remove')
          .asFunction<
            void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)
          >();
  void remove(AdwNavigationPage page) {
    _adwNavigationViewRemove(this.handle, page.handle);
  }

  /// Sets whether @self should animate page transitions.
  ///
  /// Gesture-based transitions are always animated.
  static final _adwNavigationViewSetAnimateTransitions =
      adwLookup<
            ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Int32)
            >
          >('adw_navigation_view_set_animate_transitions')
          .asFunction<void Function(ffi.Pointer<ffi.Void>, int)>();
  void setAnimateTransitions(bool animateTransitions) {
    _adwNavigationViewSetAnimateTransitions(
      this.handle,
      animateTransitions ? 1 : 0,
    );
  }

  /// Sets @self to be horizontally homogeneous or not.
  ///
  /// If the view is horizontally homogeneous, it allocates the same width for
  /// all pages.
  ///
  /// If it's not, the view may change width when a different page becomes visible.
  static final _adwNavigationViewSetHhomogeneous =
      adwLookup<
            ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Int32)
            >
          >('adw_navigation_view_set_hhomogeneous')
          .asFunction<void Function(ffi.Pointer<ffi.Void>, int)>();
  void setHhomogeneous(bool hhomogeneous) {
    _adwNavigationViewSetHhomogeneous(this.handle, hhomogeneous ? 1 : 0);
  }

  /// Sets whether pressing Escape pops the current page on @self.
  ///
  /// Applications using `AdwNavigationView` to implement a browser may want to
  /// disable it.
  static final _adwNavigationViewSetPopOnEscape =
      adwLookup<
            ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Int32)
            >
          >('adw_navigation_view_set_pop_on_escape')
          .asFunction<void Function(ffi.Pointer<ffi.Void>, int)>();
  void setPopOnEscape(bool popOnEscape) {
    _adwNavigationViewSetPopOnEscape(this.handle, popOnEscape ? 1 : 0);
  }

  /// Sets @self to be vertically homogeneous or not.
  ///
  /// If the view is vertically homogeneous, it allocates the same height for
  /// all pages.
  ///
  /// If it's not, the view may change height when a different page becomes
  /// visible.
  static final _adwNavigationViewSetVhomogeneous =
      adwLookup<
            ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Int32)
            >
          >('adw_navigation_view_set_vhomogeneous')
          .asFunction<void Function(ffi.Pointer<ffi.Void>, int)>();
  void setVhomogeneous(bool vhomogeneous) {
    _adwNavigationViewSetVhomogeneous(this.handle, vhomogeneous ? 1 : 0);
  }
}

/// An [class@AnimationTarget] that doesn't do anything.
class AdwNoneAnimationTarget extends AdwAnimationTarget {
  AdwNoneAnimationTarget.fromPointer(super.handle, {super.owned})
    : super.fromPointer();

  /// Creates a new `AdwAnimationTarget` that doesn't do anything.
  static final _adwNoneAnimationTargetNew =
      adwLookup<ffi.NativeFunction<ffi.Pointer<ffi.Void> Function()>>(
        'adw_none_animation_target_new',
      ).asFunction<ffi.Pointer<ffi.Void> Function()>();
  factory AdwNoneAnimationTarget() {
    return AdwNoneAnimationTarget.fromPointer(
      _adwNoneAnimationTargetNew(),
      owned: true,
    );
  }
}
