// Generated by gir_generator. Do not edit.
part of '../adw.dart';

/// A widget containing a page, as well as top and/or bottom bars.
///
/// <picture>
/// <source srcset="toolbar-view-dark.png" media="(prefers-color-scheme: dark)">
/// <img src="toolbar-view.png" alt="toolbar-view">
/// </picture>
///
/// `AdwToolbarView` has a single content widget and one or multiple top and
/// bottom bars, shown at the top and bottom sides respectively.
///
/// Example of an `AdwToolbarView` UI definition:
/// ```xml
/// <object class="AdwToolbarView">
/// <child type="top">
/// <object class="AdwHeaderBar"/>
/// </child>
/// <property name="content">
/// <object class="AdwPreferencesPage">
/// <!-- ... -->
/// </object>
/// </property>
/// </object>
/// ```
///
/// The following kinds of top and bottom bars are supported:
///
/// - [class@HeaderBar]
/// - [class@TabBar]
/// - [class@ViewSwitcherBar]
/// - [class@Gtk.ActionBar]
/// - [class@Gtk.HeaderBar]
/// - [class@Gtk.PopoverMenuBar]
/// - [class@Gtk.SearchBar]
/// - Any [class@Gtk.Box] or a similar widget with the
/// [`.toolbar`](style-classes.html#toolbars) style class
///
/// By default, top and bottom bars are flat and scrolling content has a subtle
/// undershoot shadow, same as when using the
/// [`.undershoot-top`](style-classes.html#undershoot-indicators) and
/// [`.undershoot-bottom`](style-classes.html#undershoot-indicators) style
/// classes. This works well in most cases, e.g. with [class@StatusPage] or
/// [class@PreferencesPage], where the background at the top and bottom parts of
/// the page is uniform. Additionally, windows with sidebars should always use
/// this style.
///
/// [property@ToolbarView:top-bar-style] and
/// [property@ToolbarView:bottom-bar-style] properties can be used add an opaque
/// background and a persistent shadow to top and bottom bars, this can be useful
/// for content such as [utility panes](https://developer.gnome.org/hig/patterns/containers/utility-panes.html),
/// where some elements are adjacent to the top/bottom bars, or [class@TabView],
/// where each page can have a different background.
///
/// <picture style="min-width: 33%; display: inline-block;">
/// <source srcset="toolbar-view-flat-1-dark.png" media="(prefers-color-scheme: dark)">
/// <img src="toolbar-view-flat-1.png" alt="toolbar-view-flat-1">
/// </picture>
/// <picture style="min-width: 33%; display: inline-block;">
/// <source srcset="toolbar-view-flat-2-dark.png" media="(prefers-color-scheme: dark)">
/// <img src="toolbar-view-flat-2.png" alt="toolbar-view-flat-2">
/// </picture>
/// <picture style="min-width: 33%; display: inline-block;">
/// <source srcset="toolbar-view-raised-dark.png" media="(prefers-color-scheme: dark)">
/// <img src="toolbar-view-raised.png" alt="toolbar-view-raised">
/// </picture>
///
/// `AdwToolbarView` ensures the top and bottom bars have consistent backdrop
/// styles and vertical spacing. For comparison:
///
/// <picture style="min-width: 40%; display: inline-block;">
/// <source srcset="toolbar-view-spacing-dark.png" media="(prefers-color-scheme: dark)">
/// <img src="toolbar-view-spacing.png" alt="toolbar-view-spacing">
/// </picture>
/// <picture style="min-width: 40%; display: inline-block;">
/// <source srcset="toolbar-view-spacing-box-dark.png" media="(prefers-color-scheme: dark)">
/// <img src="toolbar-view-spacing-box.png" alt="toolbar-view-spacing-box">
/// </picture>
///
/// Any top and bottom bars can also be dragged to move the window, equivalent
/// to putting them into a [class@Gtk.WindowHandle].
///
/// Content is typically place between top and bottom bars, but can also extend
/// behind them. This is controlled with the
/// [property@ToolbarView:extend-content-to-top-edge] and
/// [property@ToolbarView:extend-content-to-bottom-edge] properties.
///
/// Top and bottom bars can be hidden and revealed with an animation using the
/// [property@ToolbarView:reveal-top-bars] and
/// [property@ToolbarView:reveal-bottom-bars] properties.
///
/// ## `AdwToolbarView` as `GtkBuildable`
///
/// The `AdwToolbarView` implementation of the [iface@Gtk.Buildable] interface
/// supports adding a top bar by specifying “top” as the “type” attribute of a
/// `<child>` element, or adding a bottom bar by specifying “bottom”.
///
/// ## Accessibility
///
/// `AdwToolbarView` uses the [enum@Gtk.AccessibleRole.group] role.
class AdwToolbarView extends GtkWidget {
  AdwToolbarView.fromPointer(super.handle, {super.owned}) : super.fromPointer();

  /// Creates a new `AdwToolbarView`.
  static final _adwToolbarViewNew =
      adwLookup<ffi.NativeFunction<ffi.Pointer<ffi.Void> Function()>>(
        'adw_toolbar_view_new',
      ).asFunction<ffi.Pointer<ffi.Void> Function()>();
  factory AdwToolbarView() {
    return AdwToolbarView.fromPointer(
      gObjectRefSink(_adwToolbarViewNew()),
      owned: true,
    );
  }

  /// Adds a bottom bar to @self.
  static final _adwToolbarViewAddBottomBar =
      adwLookup<
            ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)
            >
          >('adw_toolbar_view_add_bottom_bar')
          .asFunction<
            void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)
          >();
  void addBottomBar(GtkWidget widget) {
    _adwToolbarViewAddBottomBar(this.handle, widget.handle);
  }

  /// Adds a top bar to @self.
  static final _adwToolbarViewAddTopBar =
      adwLookup<
            ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)
            >
          >('adw_toolbar_view_add_top_bar')
          .asFunction<
            void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)
          >();
  void addTopBar(GtkWidget widget) {
    _adwToolbarViewAddTopBar(this.handle, widget.handle);
  }

  /// Gets the current bottom bar height for @self.
  ///
  /// Bottom bar height does change depending on
  /// [property@ToolbarView:reveal-bottom-bars], including during the transition.
  ///
  /// See [method@ToolbarView.get_top_bar_height].
  static final _adwToolbarViewGetBottomBarHeight =
      adwLookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Void>)>>(
        'adw_toolbar_view_get_bottom_bar_height',
      ).asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  int getBottomBarHeight() {
    return _adwToolbarViewGetBottomBarHeight(this.handle);
  }

  /// Gets appearance of the bottom bars for @self.
  static final _adwToolbarViewGetBottomBarStyle =
      adwLookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Void>)>>(
        'adw_toolbar_view_get_bottom_bar_style',
      ).asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  AdwToolbarStyle getBottomBarStyle() {
    return AdwToolbarStyle.fromValue(
      _adwToolbarViewGetBottomBarStyle(this.handle),
    );
  }

  /// Gets the content widget for @self.
  static final _adwToolbarViewGetContent =
      adwLookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)
            >
          >('adw_toolbar_view_get_content')
          .asFunction<ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)>();
  GtkWidget? getContent() {
    return (_adwToolbarViewGetContent(this.handle)) == ffi.nullptr
        ? null
        : GtkWidget.fromPointer(_adwToolbarViewGetContent(this.handle));
  }

  /// Gets whether the content widget can extend behind bottom bars.
  static final _adwToolbarViewGetExtendContentToBottomEdge =
      adwLookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Void>)>>(
        'adw_toolbar_view_get_extend_content_to_bottom_edge',
      ).asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  bool getExtendContentToBottomEdge() {
    return (_adwToolbarViewGetExtendContentToBottomEdge(this.handle)) != 0;
  }

  /// Gets whether the content widget can extend behind top bars.
  static final _adwToolbarViewGetExtendContentToTopEdge =
      adwLookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Void>)>>(
        'adw_toolbar_view_get_extend_content_to_top_edge',
      ).asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  bool getExtendContentToTopEdge() {
    return (_adwToolbarViewGetExtendContentToTopEdge(this.handle)) != 0;
  }

  /// Gets whether bottom bars are revealed for @self.
  static final _adwToolbarViewGetRevealBottomBars =
      adwLookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Void>)>>(
        'adw_toolbar_view_get_reveal_bottom_bars',
      ).asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  bool getRevealBottomBars() {
    return (_adwToolbarViewGetRevealBottomBars(this.handle)) != 0;
  }

  /// Gets whether top bars are revealed for @self.
  static final _adwToolbarViewGetRevealTopBars =
      adwLookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Void>)>>(
        'adw_toolbar_view_get_reveal_top_bars',
      ).asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  bool getRevealTopBars() {
    return (_adwToolbarViewGetRevealTopBars(this.handle)) != 0;
  }

  /// Gets the current top bar height for @self.
  ///
  /// Top bar height does change depending on
  /// [property@ToolbarView:reveal-top-bars], including during the transition.
  ///
  /// See [method@ToolbarView.get_bottom_bar_height].
  static final _adwToolbarViewGetTopBarHeight =
      adwLookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Void>)>>(
        'adw_toolbar_view_get_top_bar_height',
      ).asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  int getTopBarHeight() {
    return _adwToolbarViewGetTopBarHeight(this.handle);
  }

  /// Gets appearance of the top bars for @self.
  static final _adwToolbarViewGetTopBarStyle =
      adwLookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Void>)>>(
        'adw_toolbar_view_get_top_bar_style',
      ).asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  AdwToolbarStyle getTopBarStyle() {
    return AdwToolbarStyle.fromValue(
      _adwToolbarViewGetTopBarStyle(this.handle),
    );
  }

  /// Removes a child from @self.
  static final _adwToolbarViewRemove =
      adwLookup<
            ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)
            >
          >('adw_toolbar_view_remove')
          .asFunction<
            void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)
          >();
  void remove(GtkWidget widget) {
    _adwToolbarViewRemove(this.handle, widget.handle);
  }

  /// Sets appearance of the bottom bars for @self.
  ///
  /// If set to [enum@Adw.ToolbarStyle.flat], bottom bars are flat and scrolling
  /// content has a subtle undershoot shadow when touching them, same as the
  /// [`.undershoot-bottom`](style-classes.html#undershoot-indicators)
  /// style class. This works well for simple content, e.g. [class@StatusPage] or
  /// [class@PreferencesPage], where the background at the bottom of the page is
  /// uniform. Additionally, windows with sidebars should always use this style.
  ///
  /// Undershoot shadow is only present if a bottom bar is actually present and
  /// visible. It is also never present if
  /// [property@ToolbarView:extend-content-to-bottom-edge] is set to `TRUE`.
  ///
  /// If set to [enum@Adw.ToolbarStyle.raised], bottom bars have an opaque
  /// background and a persistent shadow, this is suitable for content such as
  /// [utility panes](https://developer.gnome.org/hig/patterns/containers/utility-panes.html),
  /// where some elements are directly adjacent to the bottom bars, or
  /// [class@TabView], where each page can have a different background.
  ///
  /// [enum@Adw.ToolbarStyle.raised-border] is similar to
  /// [enum@Adw.ToolbarStyle.raised], but the shadow is replaced with a more subtle
  /// border. This can be useful for applications like image viewers.
  ///
  /// See also [method@ToolbarView.set_top_bar_style].
  static final _adwToolbarViewSetBottomBarStyle =
      adwLookup<
            ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Int32)
            >
          >('adw_toolbar_view_set_bottom_bar_style')
          .asFunction<void Function(ffi.Pointer<ffi.Void>, int)>();
  void setBottomBarStyle(AdwToolbarStyle style) {
    _adwToolbarViewSetBottomBarStyle(this.handle, style.value);
  }

  /// Sets the content widget for @self.
  static final _adwToolbarViewSetContent =
      adwLookup<
            ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)
            >
          >('adw_toolbar_view_set_content')
          .asFunction<
            void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)
          >();
  void setContent([GtkWidget? content]) {
    _adwToolbarViewSetContent(this.handle, content?.handle ?? ffi.nullptr);
  }

  /// Sets whether the content widget can extend behind bottom bars.
  ///
  /// This can be used in combination with [property@ToolbarView:reveal-bottom-bars]
  /// to show and hide toolbars in fullscreen.
  ///
  /// See [method@ToolbarView.set_extend_content_to_top_edge].
  static final _adwToolbarViewSetExtendContentToBottomEdge =
      adwLookup<
            ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Int32)
            >
          >('adw_toolbar_view_set_extend_content_to_bottom_edge')
          .asFunction<void Function(ffi.Pointer<ffi.Void>, int)>();
  void setExtendContentToBottomEdge(bool extend) {
    _adwToolbarViewSetExtendContentToBottomEdge(this.handle, extend ? 1 : 0);
  }

  /// Sets whether the content widget can extend behind top bars.
  ///
  /// This can be used in combination with [property@ToolbarView:reveal-top-bars]
  /// to show and hide toolbars in fullscreen.
  ///
  /// See [method@ToolbarView.set_extend_content_to_bottom_edge].
  static final _adwToolbarViewSetExtendContentToTopEdge =
      adwLookup<
            ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Int32)
            >
          >('adw_toolbar_view_set_extend_content_to_top_edge')
          .asFunction<void Function(ffi.Pointer<ffi.Void>, int)>();
  void setExtendContentToTopEdge(bool extend) {
    _adwToolbarViewSetExtendContentToTopEdge(this.handle, extend ? 1 : 0);
  }

  /// Sets whether bottom bars are revealed for @self.
  ///
  /// The transition will be animated.
  ///
  /// This can be used in combination with
  /// [property@ToolbarView:extend-content-to-bottom-edge] to show and hide
  /// toolbars in fullscreen.
  ///
  /// See [method@ToolbarView.set_reveal_top_bars].
  static final _adwToolbarViewSetRevealBottomBars =
      adwLookup<
            ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Int32)
            >
          >('adw_toolbar_view_set_reveal_bottom_bars')
          .asFunction<void Function(ffi.Pointer<ffi.Void>, int)>();
  void setRevealBottomBars(bool reveal) {
    _adwToolbarViewSetRevealBottomBars(this.handle, reveal ? 1 : 0);
  }

  /// Sets whether top bars are revealed for @self.
  ///
  /// The transition will be animated.
  ///
  /// This can be used in combination with
  /// [property@ToolbarView:extend-content-to-top-edge] to show and hide toolbars
  /// in fullscreen.
  ///
  /// See [method@ToolbarView.set_reveal_bottom_bars].
  static final _adwToolbarViewSetRevealTopBars =
      adwLookup<
            ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Int32)
            >
          >('adw_toolbar_view_set_reveal_top_bars')
          .asFunction<void Function(ffi.Pointer<ffi.Void>, int)>();
  void setRevealTopBars(bool reveal) {
    _adwToolbarViewSetRevealTopBars(this.handle, reveal ? 1 : 0);
  }

  /// Sets appearance of the top bars for @self.
  ///
  /// If set to [enum@Adw.ToolbarStyle.flat], top bars are flat and scrolling
  /// content has a subtle undershoot shadow when touching them, same as the
  /// [`.undershoot-top`](style-classes.html#undershoot-indicators)
  /// style class. This works well for simple content, e.g. [class@StatusPage] or
  /// [class@PreferencesPage], where the background at the top of the page is
  /// uniform. Additionally, windows with sidebars should always use this style.
  ///
  /// Undershoot shadow is only present if a top bar is actually present and
  /// visible. It is also never present if
  /// [property@ToolbarView:extend-content-to-top-edge] is set to `TRUE`.
  ///
  /// If set to [enum@Adw.ToolbarStyle.raised], top bars have an opaque background
  /// and a persistent shadow, this is suitable for content such as
  /// [utility panes](https://developer.gnome.org/hig/patterns/containers/utility-panes.html),
  /// where some elements are directly adjacent to the top bars, or
  /// [class@TabView], where each page can have a different background.
  ///
  /// [enum@Adw.ToolbarStyle.raised-border] is similar to
  /// [enum@Adw.ToolbarStyle.raised], but the shadow is replaced with a more subtle
  /// border. This can be useful for applications like image viewers.
  ///
  /// See also [method@ToolbarView.set_bottom_bar_style].
  static final _adwToolbarViewSetTopBarStyle =
      adwLookup<
            ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Int32)
            >
          >('adw_toolbar_view_set_top_bar_style')
          .asFunction<void Function(ffi.Pointer<ffi.Void>, int)>();
  void setTopBarStyle(AdwToolbarStyle style) {
    _adwToolbarViewSetTopBarStyle(this.handle, style.value);
  }

  /// Signals that all holders of a reference to the widget should release
  /// the reference that they hold.
  ///
  /// May result in finalization of the widget if all references are released.
  ///
  /// This signal is not suitable for saving widget state.
  int onDestroy(void Function() callback) {
    return _connectSignal_v_0(this.handle, 'destroy', callback);
  }

  /// Emitted when the text direction of a widget changes.
  int onDirectionChanged(
    void Function(GtkTextDirection previousDirection) callback,
  ) {
    return _connectSignal_v_1_i_gtktextdirection(
      this.handle,
      'direction-changed',
      callback,
    );
  }

  /// Emitted when @widget is hidden.
  int onHide(void Function() callback) {
    return _connectSignal_v_0(this.handle, 'hide', callback);
  }

  /// Emitted if keyboard navigation fails.
  ///
  /// See [method@Gtk.Widget.keynav_failed] for details.
  int onKeynavFailed(bool Function(GtkDirectionType direction) callback) {
    return _connectSignal_b_1_i_gtkdirectiontype(
      this.handle,
      'keynav-failed',
      callback,
    );
  }

  /// Emitted when @widget is going to be mapped.
  ///
  /// A widget is mapped when the widget is visible (which is controlled with
  /// [property@Gtk.Widget:visible]) and all its parents up to the toplevel widget
  /// are also visible.
  ///
  /// The `::map` signal can be used to determine whether a widget will be drawn,
  /// for instance it can resume an animation that was stopped during the
  /// emission of [signal@Gtk.Widget::unmap].
  int onMap(void Function() callback) {
    return _connectSignal_v_0(this.handle, 'map', callback);
  }

  /// Emitted when a widget is activated via a mnemonic.
  ///
  /// The default handler for this signal activates @widget if @group_cycling
  /// is false, or just makes @widget grab focus if @group_cycling is true.
  int onMnemonicActivate(bool Function(bool groupCycling) callback) {
    return _connectSignal_b_1_b_bool(
      this.handle,
      'mnemonic-activate',
      callback,
    );
  }

  /// Emitted when the focus is moved.
  ///
  /// The `::move-focus` signal is a [keybinding signal](class.SignalAction.html).
  ///
  /// The default bindings for this signal are <kbd>Tab</kbd> to move forward,
  /// and <kbd>Shift</kbd>+<kbd>Tab</kbd> to move backward.
  int onMoveFocus(void Function(GtkDirectionType direction) callback) {
    return _connectSignal_v_1_i_gtkdirectiontype(
      this.handle,
      'move-focus',
      callback,
    );
  }

  /// Emitted when the widget’s tooltip is about to be shown.
  ///
  /// This happens when the [property@Gtk.Widget:has-tooltip] property
  /// is true and the hover timeout has expired with the cursor hovering
  /// above @widget; or emitted when @widget got focus in keyboard mode.
  ///
  /// Using the given coordinates, the signal handler should determine
  /// whether a tooltip should be shown for @widget. If this is the case
  /// true should be returned, false otherwise. Note that if @keyboard_mode
  /// is true, the values of @x and @y are undefined and should not be used.
  ///
  /// The signal handler is free to manipulate @tooltip with the therefore
  /// destined function calls.
  int onQueryTooltip(
    bool Function(int x, int y, bool keyboardMode, GtkTooltip tooltip) callback,
  ) {
    return _connectSignal_b_4_i_i_b_o_int_int_bool_gtktooltip(
      this.handle,
      'query-tooltip',
      callback,
    );
  }

  /// Emitted when @widget is associated with a `GdkSurface`.
  ///
  /// This means that [method@Gtk.Widget.realize] has been called
  /// or the widget has been mapped (that is, it is going to be drawn).
  int onRealize(void Function() callback) {
    return _connectSignal_v_0(this.handle, 'realize', callback);
  }

  /// Emitted when @widget is shown.
  int onShow(void Function() callback) {
    return _connectSignal_v_0(this.handle, 'show', callback);
  }

  /// Emitted when the widget state changes.
  ///
  /// See [method@Gtk.Widget.get_state_flags].
  int onStateFlagsChanged(void Function(GtkStateFlags flags) callback) {
    return _connectSignal_v_1_u_gtkstateflags(
      this.handle,
      'state-flags-changed',
      callback,
    );
  }

  /// Emitted when @widget is going to be unmapped.
  ///
  /// A widget is unmapped when either it or any of its parents up to the
  /// toplevel widget have been set as hidden.
  ///
  /// As `::unmap` indicates that a widget will not be shown any longer,
  /// it can be used to, for example, stop an animation on the widget.
  int onUnmap(void Function() callback) {
    return _connectSignal_v_0(this.handle, 'unmap', callback);
  }

  /// Emitted when the `GdkSurface` associated with @widget is destroyed.
  ///
  /// This means that [method@Gtk.Widget.unrealize] has been called
  /// or the widget has been unmapped (that is, it is going to be hidden).
  int onUnrealize(void Function() callback) {
    return _connectSignal_v_0(this.handle, 'unrealize', callback);
  }

  /// The notify signal is emitted on an object when one of its properties has
  /// its value set through g_object_set_property(), g_object_set(), et al.
  ///
  /// Note that getting this signal doesn’t itself guarantee that the value of
  /// the property has actually changed. When it is emitted is determined by the
  /// derived GObject class. If the implementor did not create the property with
  /// %G_PARAM_EXPLICIT_NOTIFY, then any call to g_object_set_property() results
  /// in ::notify being emitted, even if the new value is the same as the old.
  /// If they did pass %G_PARAM_EXPLICIT_NOTIFY, then this signal is emitted only
  /// when they explicitly call g_object_notify() or g_object_notify_by_pspec(),
  /// and common practice is to do that only when the value has actually changed.
  ///
  /// This signal is typically used to obtain change notification for a
  /// single property, by specifying the property name as a detail in the
  /// g_signal_connect() call, like this:
  ///
  /// |[<!-- language="C" -->
  /// g_signal_connect (text_view->buffer, "notify::paste-target-list",
  /// G_CALLBACK (gtk_text_view_target_list_notify),
  /// text_view)
  /// ]|
  ///
  /// It is important to note that you must use
  /// [canonical parameter names][class@GObject.ParamSpec#parameter-names] as
  /// detail strings for the notify signal.
  int onNotify(void Function(GParamSpec pspec) callback) {
    return _connectSignal_v_1_o_gparamspec(this.handle, 'notify', callback);
  }
}
