// Generated by gir_generator. Do not edit.
part of '../gio.dart';

/// A `GPropertyAction` is a way to get a [iface@Gio.Action] with a state value
/// reflecting and controlling the value of a [class@GObject.Object] property.
///
/// The state of the action will correspond to the value of the property.
/// Changing it will change the property (assuming the requested value
/// matches the requirements as specified in the [type@GObject.ParamSpec]).
///
/// Only the most common types are presently supported.  Booleans are
/// mapped to booleans, strings to strings, signed/unsigned integers to
/// int32/uint32 and floats and doubles to doubles.
///
/// If the property is an enum then the state will be string-typed and
/// conversion will automatically be performed between the enum value and
/// ‘nick’ string as per the [type@GObject.EnumValue] table.
///
/// Flags types are not currently supported.
///
/// Properties of object types, boxed types and pointer types are not
/// supported and probably never will be.
///
/// Properties of [type@GLib.Variant] types are not currently supported.
///
/// If the property is boolean-valued then the action will have a `NULL`
/// parameter type, and activating the action (with no parameter) will
/// toggle the value of the property.
///
/// In all other cases, the parameter type will correspond to the type of
/// the property.
///
/// The general idea here is to reduce the number of locations where a
/// particular piece of state is kept (and therefore has to be synchronised
/// between). `GPropertyAction` does not have a separate state that is kept
/// in sync with the property value — its state is the property value.
///
/// For example, it might be useful to create a [iface@Gio.Action] corresponding
/// to the `visible-child-name` property of a [`GtkStack`](https://docs.gtk.org/gtk4/class.Stack.html)
/// so that the current page can be switched from a menu.  The active radio
/// indication in the menu is then directly determined from the active page of
/// the `GtkStack`.
///
/// An anti-example would be binding the `active-id` property on a
/// [`GtkComboBox`](https://docs.gtk.org/gtk4/class.ComboBox.html). This is
/// because the state of the combo box itself is probably uninteresting and is
/// actually being used to control something else.
///
/// Another anti-example would be to bind to the `visible-child-name`
/// property of a [`GtkStack`](https://docs.gtk.org/gtk4/class.Stack.html) if
/// this value is actually stored in [class@Gio.Settings].  In that case, the
/// real source of the value is* [class@Gio.Settings].  If you want
/// a [iface@Gio.Action] to control a setting stored in [class@Gio.Settings],
/// see [method@Gio.Settings.create_action] instead, and possibly combine its
/// use with [method@Gio.Settings.bind].
class GPropertyAction implements ffi.Finalizable {
  GPropertyAction.fromPointer(this.handle, {this.owned = false}) {
    if (owned) {
      _attachFinalizer();
    }
  }
  final ffi.Pointer<ffi.Void> handle;
  final bool owned;
  void _attachFinalizer() =>
      gobjectFinalizer.attach(this, handle, detach: this);

  /// Creates a #GAction corresponding to the value of property
  /// @property_name on @object.
  ///
  /// The property must be existent and readable and writable (and not
  /// construct-only).
  ///
  /// This function takes a reference on @object and doesn't release it
  /// until the action is destroyed.
  static final _gPropertyActionNew =
      gioLookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(
                ffi.Pointer<Utf8>,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<Utf8>,
              )
            >
          >('g_property_action_new')
          .asFunction<
            ffi.Pointer<ffi.Void> Function(
              ffi.Pointer<Utf8>,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<Utf8>,
            )
          >();
  factory GPropertyAction(
    String name,
    ffi.Pointer<ffi.Void> object,
    String propertyName,
  ) {
    return withNativeString(name, (nativeName) {
      return withNativeString(propertyName, (nativePropertyName) {
        return GPropertyAction.fromPointer(
          _gPropertyActionNew(
            nativeName.cast<Utf8>(),
            object,
            nativePropertyName.cast<Utf8>(),
          ),
          owned: true,
        );
      });
    });
  }
}

/// A [class@Gio.InetSocketAddress] representing a connection via a proxy server.
class GProxyAddress extends GInetSocketAddress {
  GProxyAddress.fromPointer(super.handle, {super.owned}) : super.fromPointer();

  /// Creates a new #GProxyAddress for @inetaddr with @protocol that should
  /// tunnel through @dest_hostname and @dest_port.
  ///
  /// (Note that this method doesn't set the #GProxyAddress:uri or
  /// #GProxyAddress:destination-protocol fields; use g_object_new()
  /// directly if you want to set those.)
  static final _gProxyAddressNew =
      gioLookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(
                ffi.Pointer<ffi.Void>,
                ffi.Uint16,
                ffi.Pointer<Utf8>,
                ffi.Pointer<Utf8>,
                ffi.Uint16,
                ffi.Pointer<Utf8>,
                ffi.Pointer<Utf8>,
              )
            >
          >('g_proxy_address_new')
          .asFunction<
            ffi.Pointer<ffi.Void> Function(
              ffi.Pointer<ffi.Void>,
              int,
              ffi.Pointer<Utf8>,
              ffi.Pointer<Utf8>,
              int,
              ffi.Pointer<Utf8>,
              ffi.Pointer<Utf8>,
            )
          >();
  factory GProxyAddress(
    GInetAddress inetaddr,
    int port,
    String protocol,
    String destHostname,
    int destPort, [
    String? username,
    String? password,
  ]) {
    return withNativeString(protocol, (nativeProtocol) {
      return withNativeString(destHostname, (nativeDestHostname) {
        return withNativeString(username, (nativeUsername) {
          return withNativeString(password, (nativePassword) {
            return GProxyAddress.fromPointer(
              _gProxyAddressNew(
                inetaddr.handle,
                port,
                nativeProtocol.cast<Utf8>(),
                nativeDestHostname.cast<Utf8>(),
                destPort,
                nativeUsername.cast<Utf8>(),
                nativePassword.cast<Utf8>(),
              ),
              owned: true,
            );
          });
        });
      });
    });
  }

  /// Gets @proxy's destination hostname; that is, the name of the host
  /// that will be connected to via the proxy, not the name of the proxy
  /// itself.
  static final _gProxyAddressGetDestinationHostname =
      gioLookup<
            ffi.NativeFunction<
              ffi.Pointer<Utf8> Function(ffi.Pointer<ffi.Void>)
            >
          >('g_proxy_address_get_destination_hostname')
          .asFunction<ffi.Pointer<Utf8> Function(ffi.Pointer<ffi.Void>)>();
  String getDestinationHostname() {
    return stringFromNative(
      (_gProxyAddressGetDestinationHostname(this.handle)).cast(),
      free: false,
    )!;
  }

  /// Gets @proxy's destination port; that is, the port on the
  /// destination host that will be connected to via the proxy, not the
  /// port number of the proxy itself.
  static final _gProxyAddressGetDestinationPort =
      gioLookup<ffi.NativeFunction<ffi.Uint16 Function(ffi.Pointer<ffi.Void>)>>(
        'g_proxy_address_get_destination_port',
      ).asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  int getDestinationPort() {
    return _gProxyAddressGetDestinationPort(this.handle);
  }

  /// Gets the protocol that is being spoken to the destination
  /// server; eg, "http" or "ftp".
  static final _gProxyAddressGetDestinationProtocol =
      gioLookup<
            ffi.NativeFunction<
              ffi.Pointer<Utf8> Function(ffi.Pointer<ffi.Void>)
            >
          >('g_proxy_address_get_destination_protocol')
          .asFunction<ffi.Pointer<Utf8> Function(ffi.Pointer<ffi.Void>)>();
  String getDestinationProtocol() {
    return stringFromNative(
      (_gProxyAddressGetDestinationProtocol(this.handle)).cast(),
      free: false,
    )!;
  }

  /// Gets @proxy's password.
  static final _gProxyAddressGetPassword =
      gioLookup<
            ffi.NativeFunction<
              ffi.Pointer<Utf8> Function(ffi.Pointer<ffi.Void>)
            >
          >('g_proxy_address_get_password')
          .asFunction<ffi.Pointer<Utf8> Function(ffi.Pointer<ffi.Void>)>();
  String? getPassword() {
    return stringFromNative(
      (_gProxyAddressGetPassword(this.handle)).cast(),
      free: false,
    );
  }

  /// Gets @proxy's protocol. eg, "socks" or "http"
  static final _gProxyAddressGetProtocol =
      gioLookup<
            ffi.NativeFunction<
              ffi.Pointer<Utf8> Function(ffi.Pointer<ffi.Void>)
            >
          >('g_proxy_address_get_protocol')
          .asFunction<ffi.Pointer<Utf8> Function(ffi.Pointer<ffi.Void>)>();
  String getProtocol() {
    return stringFromNative(
      (_gProxyAddressGetProtocol(this.handle)).cast(),
      free: false,
    )!;
  }

  /// Gets the proxy URI that @proxy was constructed from.
  static final _gProxyAddressGetUri =
      gioLookup<
            ffi.NativeFunction<
              ffi.Pointer<Utf8> Function(ffi.Pointer<ffi.Void>)
            >
          >('g_proxy_address_get_uri')
          .asFunction<ffi.Pointer<Utf8> Function(ffi.Pointer<ffi.Void>)>();
  String? getUri() {
    return stringFromNative(
      (_gProxyAddressGetUri(this.handle)).cast(),
      free: false,
    );
  }

  /// Gets @proxy's username.
  static final _gProxyAddressGetUsername =
      gioLookup<
            ffi.NativeFunction<
              ffi.Pointer<Utf8> Function(ffi.Pointer<ffi.Void>)
            >
          >('g_proxy_address_get_username')
          .asFunction<ffi.Pointer<Utf8> Function(ffi.Pointer<ffi.Void>)>();
  String? getUsername() {
    return stringFromNative(
      (_gProxyAddressGetUsername(this.handle)).cast(),
      free: false,
    );
  }
}

/// `GProxyAddressEnumerator` is a wrapper around
/// [class@Gio.SocketAddressEnumerator] which takes the [class@Gio.SocketAddress]
/// instances returned by the [class@Gio.SocketAddressEnumerator]
/// and wraps them in [class@Gio.ProxyAddress] instances, using the given
/// [property@Gio.ProxyAddressEnumerator:proxy-resolver].
///
/// This enumerator will be returned (for example, by
/// [method@Gio.SocketConnectable.enumerate]) as appropriate when a proxy is
/// configured; there should be no need to manually wrap a
/// [class@Gio.SocketAddressEnumerator] instance with one.
class GProxyAddressEnumerator extends GSocketAddressEnumerator {
  GProxyAddressEnumerator.fromPointer(super.handle, {super.owned})
    : super.fromPointer();
}

/// The object that handles DNS resolution. Use [func@Gio.Resolver.get_default]
/// to get the default resolver.
///
/// `GResolver` provides cancellable synchronous and asynchronous DNS
/// resolution, for hostnames ([method@Gio.Resolver.lookup_by_address],
/// [method@Gio.Resolver.lookup_by_name] and their async variants) and SRV
/// (service) records ([method@Gio.Resolver.lookup_service]).
///
/// [class@Gio.NetworkAddress] and [class@Gio.NetworkService] provide wrappers
/// around `GResolver` functionality that also implement
/// [iface@Gio.SocketConnectable], making it easy to connect to a remote
/// host/service.
///
/// The default resolver (see [func@Gio.Resolver.get_default]) has a timeout of
/// 30s set on it since GLib 2.78. Earlier versions of GLib did not support
/// resolver timeouts.
///
/// This is an abstract type; subclasses of it implement different resolvers for
/// different platforms and situations.
class GResolver implements ffi.Finalizable {
  GResolver.fromPointer(this.handle, {this.owned = false}) {
    if (owned) {
      _attachFinalizer();
    }
  }
  final ffi.Pointer<ffi.Void> handle;
  final bool owned;
  void _attachFinalizer() =>
      gobjectFinalizer.attach(this, handle, detach: this);

  /// Get the timeout applied to all resolver lookups. See #GResolver:timeout.
  static final _gResolverGetTimeout =
      gioLookup<ffi.NativeFunction<ffi.Uint32 Function(ffi.Pointer<ffi.Void>)>>(
        'g_resolver_get_timeout',
      ).asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  int getTimeout() {
    return _gResolverGetTimeout(this.handle);
  }

  /// Synchronously reverse-resolves @address to determine its
  /// associated hostname.
  ///
  /// If the DNS resolution fails, @error (if non-%NULL) will be set to
  /// a value from #GResolverError.
  ///
  /// If @cancellable is non-%NULL, it can be used to cancel the
  /// operation, in which case @error (if non-%NULL) will be set to
  /// %G_IO_ERROR_CANCELLED.
  static final _gResolverLookupByAddress =
      gioLookup<
            ffi.NativeFunction<
              ffi.Pointer<Utf8> Function(
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Pointer<ffi.Void>>,
              )
            >
          >('g_resolver_lookup_by_address')
          .asFunction<
            ffi.Pointer<Utf8> Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Pointer<ffi.Void>>,
            )
          >();
  String lookupByAddress(GInetAddress address, [GCancellable? cancellable]) {
    final _error = calloc<ffi.Pointer<ffi.Void>>();
    try {
      final _ret = _gResolverLookupByAddress(
        this.handle,
        address.handle,
        cancellable?.handle ?? ffi.nullptr,
        _error,
      );
      if (_error.value != ffi.nullptr) {
        throw GlibException.fromError(_error.value);
      }
      return stringFromNative((_ret).cast(), free: true)!;
    } finally {
      calloc.free(_error);
    }
  }

  /// Retrieves the result of a previous call to
  /// g_resolver_lookup_by_address_async().
  ///
  /// If the DNS resolution failed, @error (if non-%NULL) will be set to
  /// a value from #GResolverError. If the operation was cancelled,
  /// @error will be set to %G_IO_ERROR_CANCELLED.
  static final _gResolverLookupByAddressFinish =
      gioLookup<
            ffi.NativeFunction<
              ffi.Pointer<Utf8> Function(
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Pointer<ffi.Void>>,
              )
            >
          >('g_resolver_lookup_by_address_finish')
          .asFunction<
            ffi.Pointer<Utf8> Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Pointer<ffi.Void>>,
            )
          >();
  String lookupByAddressFinish(GAsyncResult result) {
    final _error = calloc<ffi.Pointer<ffi.Void>>();
    try {
      final _ret = _gResolverLookupByAddressFinish(
        this.handle,
        result.handle,
        _error,
      );
      if (_error.value != ffi.nullptr) {
        throw GlibException.fromError(_error.value);
      }
      return stringFromNative((_ret).cast(), free: true)!;
    } finally {
      calloc.free(_error);
    }
  }

  /// Sets @resolver to be the application's default resolver (reffing
  /// @resolver, and unreffing the previous default resolver, if any).
  /// Future calls to g_resolver_get_default() will return this resolver.
  ///
  /// This can be used if an application wants to perform any sort of DNS
  /// caching or "pinning"; it can implement its own #GResolver that
  /// calls the original default resolver for DNS operations, and
  /// implements its own cache policies on top of that, and then set
  /// itself as the default resolver for all later code to use.
  static final _gResolverSetDefault =
      gioLookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'g_resolver_set_default',
      ).asFunction<void Function(ffi.Pointer<ffi.Void>)>();
  void setDefault() {
    _gResolverSetDefault(this.handle);
  }

  /// Set the timeout applied to all resolver lookups. See #GResolver:timeout.
  static final _gResolverSetTimeout =
      gioLookup<
            ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Uint32)
            >
          >('g_resolver_set_timeout')
          .asFunction<void Function(ffi.Pointer<ffi.Void>, int)>();
  void setTimeout(int timeoutMs) {
    _gResolverSetTimeout(this.handle, timeoutMs);
  }

  /// Gets the default #GResolver. You should unref it when you are done
  /// with it. #GResolver may use its reference count as a hint about how
  /// many threads it should allocate for concurrent DNS resolutions.
  static final _gResolverGetDefault =
      gioLookup<ffi.NativeFunction<ffi.Pointer<ffi.Void> Function()>>(
        'g_resolver_get_default',
      ).asFunction<ffi.Pointer<ffi.Void> Function()>();
  static GResolver getDefault() {
    return GResolver.fromPointer(_gResolverGetDefault());
  }

  /// Emitted when the resolver notices that the system resolver
  /// configuration has changed.
  int onReload(void Function() callback) {
    return _connectVoidSignal(this.handle, 'reload', callback);
  }
}
