// Generated by gir_generator. Do not edit.
part of '../gio.dart';

/// `GSocketAddress` is the equivalent of
/// [`struct sockaddr`](man:sockaddr(3type)) and its subtypes in the BSD sockets
/// API. This is an abstract class; use [class@Gio.InetSocketAddress] for
/// internet sockets, or [class@Gio.UnixSocketAddress] for UNIX domain sockets.
class GSocketAddress extends GObject {
  GSocketAddress.fromPointer(super.handle, {super.owned}) : super.fromPointer();

  /// Creates a #GSocketAddress subclass corresponding to the native
  /// struct sockaddr @native.
  static final _gSocketAddressNewFromNative =
      gioLookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>, ffi.Size)
            >
          >('g_socket_address_new_from_native')
          .asFunction<
            ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>, int)
          >();
  factory GSocketAddress.fromNative(ffi.Pointer<ffi.Void> native, int len) {
    return GSocketAddress.fromPointer(
      _gSocketAddressNewFromNative(native, len),
      owned: true,
    );
  }

  /// Gets the socket family type of @address.
  static final _gSocketAddressGetFamily =
      gioLookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Void>)>>(
        'g_socket_address_get_family',
      ).asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  GSocketFamily getFamily() {
    return GSocketFamily.fromValue(_gSocketAddressGetFamily(this.handle));
  }

  /// Gets the size of @address's native struct sockaddr.
  /// You can use this to allocate memory to pass to
  /// g_socket_address_to_native().
  static final _gSocketAddressGetNativeSize =
      gioLookup<ffi.NativeFunction<ffi.IntPtr Function(ffi.Pointer<ffi.Void>)>>(
        'g_socket_address_get_native_size',
      ).asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  int getNativeSize() {
    return _gSocketAddressGetNativeSize(this.handle);
  }

  /// Converts a #GSocketAddress to a native struct sockaddr, which can
  /// be passed to low-level functions like connect() or bind().
  ///
  /// If not enough space is available, a %G_IO_ERROR_NO_SPACE error
  /// is returned. If the address type is not known on the system
  /// then a %G_IO_ERROR_NOT_SUPPORTED error is returned.
  static final _gSocketAddressToNative =
      gioLookup<
            ffi.NativeFunction<
              ffi.Int32 Function(
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Void>,
                ffi.Size,
                ffi.Pointer<ffi.Pointer<ffi.Void>>,
              )
            >
          >('g_socket_address_to_native')
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Void>,
              int,
              ffi.Pointer<ffi.Pointer<ffi.Void>>,
            )
          >();
  bool toNative(ffi.Pointer<ffi.Void> dest, int destlen) {
    final _error = calloc<ffi.Pointer<ffi.Void>>();
    try {
      final _ret = _gSocketAddressToNative(this.handle, dest, destlen, _error);
      if (_error.value != ffi.nullptr) {
        throw GlibException.fromError(_error.value);
      }
      return (_ret) != 0;
    } finally {
      calloc.free(_error);
    }
  }

  /// The notify signal is emitted on an object when one of its properties has
  /// its value set through g_object_set_property(), g_object_set(), et al.
  ///
  /// Note that getting this signal doesn’t itself guarantee that the value of
  /// the property has actually changed. When it is emitted is determined by the
  /// derived GObject class. If the implementor did not create the property with
  /// %G_PARAM_EXPLICIT_NOTIFY, then any call to g_object_set_property() results
  /// in ::notify being emitted, even if the new value is the same as the old.
  /// If they did pass %G_PARAM_EXPLICIT_NOTIFY, then this signal is emitted only
  /// when they explicitly call g_object_notify() or g_object_notify_by_pspec(),
  /// and common practice is to do that only when the value has actually changed.
  ///
  /// This signal is typically used to obtain change notification for a
  /// single property, by specifying the property name as a detail in the
  /// g_signal_connect() call, like this:
  ///
  /// |[<!-- language="C" -->
  /// g_signal_connect (text_view->buffer, "notify::paste-target-list",
  /// G_CALLBACK (gtk_text_view_target_list_notify),
  /// text_view)
  /// ]|
  ///
  /// It is important to note that you must use
  /// [canonical parameter names][class@GObject.ParamSpec#parameter-names] as
  /// detail strings for the notify signal.
  int onNotify(void Function(GParamSpec pspec) callback) {
    return _connectSignal_v_1_o_gparamspec(this.handle, 'notify', callback);
  }
}

/// `GSocketAddressEnumerator` is an enumerator type for
/// [class@Gio.SocketAddress] instances. It is returned by enumeration functions
/// such as [method@Gio.SocketConnectable.enumerate], which returns a
/// `GSocketAddressEnumerator` to list each [class@Gio.SocketAddress] which could
/// be used to connect to that [iface@Gio.SocketConnectable].
///
/// Enumeration is typically a blocking operation, so the asynchronous methods
/// [method@Gio.SocketAddressEnumerator.next_async] and
/// [method@Gio.SocketAddressEnumerator.next_finish] should be used where
/// possible.
///
/// Each `GSocketAddressEnumerator` can only be enumerated once. Once
/// [method@Gio.SocketAddressEnumerator.next] has returned `NULL`, further
/// enumeration with that `GSocketAddressEnumerator` is not possible, and it can
/// be unreffed.
class GSocketAddressEnumerator extends GObject {
  GSocketAddressEnumerator.fromPointer(super.handle, {super.owned})
    : super.fromPointer();

  /// Retrieves the next #GSocketAddress from @enumerator. Note that this
  /// may block for some amount of time. (Eg, a #GNetworkAddress may need
  /// to do a DNS lookup before it can return an address.) Use
  /// g_socket_address_enumerator_next_async() if you need to avoid
  /// blocking.
  ///
  /// If @enumerator is expected to yield addresses, but for some reason
  /// is unable to (eg, because of a DNS error), then the first call to
  /// g_socket_address_enumerator_next() will return an appropriate error
  /// in `*error`. However, if the first call to
  /// g_socket_address_enumerator_next() succeeds, then any further
  /// internal errors (other than @cancellable being triggered) will be
  /// ignored.
  static final _gSocketAddressEnumeratorNext =
      gioLookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Pointer<ffi.Void>>,
              )
            >
          >('g_socket_address_enumerator_next')
          .asFunction<
            ffi.Pointer<ffi.Void> Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Pointer<ffi.Void>>,
            )
          >();
  GSocketAddress? next([GCancellable? cancellable]) {
    final _error = calloc<ffi.Pointer<ffi.Void>>();
    try {
      final _ret = _gSocketAddressEnumeratorNext(
        this.handle,
        cancellable?.handle ?? ffi.nullptr,
        _error,
      );
      if (_error.value != ffi.nullptr) {
        throw GlibException.fromError(_error.value);
      }
      return (_ret) == ffi.nullptr ? null : GSocketAddress.fromPointer(_ret);
    } finally {
      calloc.free(_error);
    }
  }

  /// Retrieves the result of a completed call to
  /// g_socket_address_enumerator_next_async(). See
  /// g_socket_address_enumerator_next() for more information about
  /// error handling.
  static final _gSocketAddressEnumeratorNextFinish =
      gioLookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Pointer<ffi.Void>>,
              )
            >
          >('g_socket_address_enumerator_next_finish')
          .asFunction<
            ffi.Pointer<ffi.Void> Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Pointer<ffi.Void>>,
            )
          >();
  GSocketAddress? nextFinish(GAsyncResult result) {
    final _error = calloc<ffi.Pointer<ffi.Void>>();
    try {
      final _ret = _gSocketAddressEnumeratorNextFinish(
        this.handle,
        result.handle,
        _error,
      );
      if (_error.value != ffi.nullptr) {
        throw GlibException.fromError(_error.value);
      }
      return (_ret) == ffi.nullptr ? null : GSocketAddress.fromPointer(_ret);
    } finally {
      calloc.free(_error);
    }
  }

  /// The notify signal is emitted on an object when one of its properties has
  /// its value set through g_object_set_property(), g_object_set(), et al.
  ///
  /// Note that getting this signal doesn’t itself guarantee that the value of
  /// the property has actually changed. When it is emitted is determined by the
  /// derived GObject class. If the implementor did not create the property with
  /// %G_PARAM_EXPLICIT_NOTIFY, then any call to g_object_set_property() results
  /// in ::notify being emitted, even if the new value is the same as the old.
  /// If they did pass %G_PARAM_EXPLICIT_NOTIFY, then this signal is emitted only
  /// when they explicitly call g_object_notify() or g_object_notify_by_pspec(),
  /// and common practice is to do that only when the value has actually changed.
  ///
  /// This signal is typically used to obtain change notification for a
  /// single property, by specifying the property name as a detail in the
  /// g_signal_connect() call, like this:
  ///
  /// |[<!-- language="C" -->
  /// g_signal_connect (text_view->buffer, "notify::paste-target-list",
  /// G_CALLBACK (gtk_text_view_target_list_notify),
  /// text_view)
  /// ]|
  ///
  /// It is important to note that you must use
  /// [canonical parameter names][class@GObject.ParamSpec#parameter-names] as
  /// detail strings for the notify signal.
  int onNotify(void Function(GParamSpec pspec) callback) {
    return _connectSignal_v_1_o_gparamspec(this.handle, 'notify', callback);
  }
}
