// Generated by gir_generator. Do not edit.
part of '../gio.dart';

/// Base class for output stream implementations that perform some
/// kind of filtering operation on a base stream. Typical examples
/// of filtering operations are character set conversion, compression
/// and byte order flipping.
class GFilterOutputStream extends GOutputStream {
  GFilterOutputStream.fromPointer(super.handle, {super.owned})
    : super.fromPointer();

  /// Gets the base stream for the filter stream.
  static final _gFilterOutputStreamGetBaseStream =
      gioLookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)
            >
          >('g_filter_output_stream_get_base_stream')
          .asFunction<ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)>();
  GOutputStream getBaseStream() {
    return GOutputStream.fromPointer(
      _gFilterOutputStreamGetBaseStream(this.handle),
    );
  }

  /// Returns whether the base stream will be closed when @stream is
  /// closed.
  static final _gFilterOutputStreamGetCloseBaseStream =
      gioLookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Void>)>>(
        'g_filter_output_stream_get_close_base_stream',
      ).asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  bool getCloseBaseStream() {
    return (_gFilterOutputStreamGetCloseBaseStream(this.handle)) != 0;
  }

  /// Sets whether the base stream will be closed when @stream is closed.
  static final _gFilterOutputStreamSetCloseBaseStream =
      gioLookup<
            ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Int32)
            >
          >('g_filter_output_stream_set_close_base_stream')
          .asFunction<void Function(ffi.Pointer<ffi.Void>, int)>();
  void setCloseBaseStream(bool closeBase) {
    _gFilterOutputStreamSetCloseBaseStream(this.handle, closeBase ? 1 : 0);
  }

  /// The notify signal is emitted on an object when one of its properties has
  /// its value set through g_object_set_property(), g_object_set(), et al.
  ///
  /// Note that getting this signal doesn’t itself guarantee that the value of
  /// the property has actually changed. When it is emitted is determined by the
  /// derived GObject class. If the implementor did not create the property with
  /// %G_PARAM_EXPLICIT_NOTIFY, then any call to g_object_set_property() results
  /// in ::notify being emitted, even if the new value is the same as the old.
  /// If they did pass %G_PARAM_EXPLICIT_NOTIFY, then this signal is emitted only
  /// when they explicitly call g_object_notify() or g_object_notify_by_pspec(),
  /// and common practice is to do that only when the value has actually changed.
  ///
  /// This signal is typically used to obtain change notification for a
  /// single property, by specifying the property name as a detail in the
  /// g_signal_connect() call, like this:
  ///
  /// |[<!-- language="C" -->
  /// g_signal_connect (text_view->buffer, "notify::paste-target-list",
  /// G_CALLBACK (gtk_text_view_target_list_notify),
  /// text_view)
  /// ]|
  ///
  /// It is important to note that you must use
  /// [canonical parameter names][class@GObject.ParamSpec#parameter-names] as
  /// detail strings for the notify signal.
  int onNotify(void Function(GParamSpec pspec) callback) {
    return _connectSignal_v_1_o_gparamspec(this.handle, 'notify', callback);
  }

  /// PyGObject-style typed property accessor. Reads and
  /// writes via the existing `get<Name>` / `set<Name>`
  /// methods; each property here corresponds to a GIR
  /// `<property>` element on this class (or one of its
  /// ancestors). See [GFilterOutputStreamProps] for the typed
  /// accessor pair per property.
  late final GFilterOutputStreamProps _props = GFilterOutputStreamProps(this);
  GFilterOutputStreamProps get props => _props;
}

/// PyGObject-style typed property accessor. Each getter
/// and setter delegates to the existing typed
/// `get<Name>` / `set<Name>` methods on [GFilterOutputStream].
///
/// Skipped properties (unsupported type, missing getter
/// or setter) are recorded in the generation report.
class GFilterOutputStreamProps {
  GFilterOutputStreamProps(this._self);
  final GFilterOutputStream _self;

  GOutputStream get baseStream => _self.getBaseStream();

  bool get closeBaseStream => _self.getCloseBaseStream();
}

/// Provides an interface and default functions for loading and unloading
/// modules. This is used internally to make GIO extensible, but can also
/// be used by others to implement module loading.
class GIOModule extends GTypeModule {
  GIOModule.fromPointer(super.handle, {super.owned}) : super.fromPointer();

  /// Creates a new GIOModule that will load the specific
  /// shared library when in use.
  static final _gIoModuleNew =
      gioLookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(ffi.Pointer<Utf8>)
            >
          >('g_io_module_new')
          .asFunction<ffi.Pointer<ffi.Void> Function(ffi.Pointer<Utf8>)>();
  factory GIOModule(String filename) {
    return withNativeString(filename, (nativeFilename) {
      return GIOModule.fromPointer(
        _gIoModuleNew(nativeFilename.cast<Utf8>()),
        owned: true,
      );
    });
  }

  /// The notify signal is emitted on an object when one of its properties has
  /// its value set through g_object_set_property(), g_object_set(), et al.
  ///
  /// Note that getting this signal doesn’t itself guarantee that the value of
  /// the property has actually changed. When it is emitted is determined by the
  /// derived GObject class. If the implementor did not create the property with
  /// %G_PARAM_EXPLICIT_NOTIFY, then any call to g_object_set_property() results
  /// in ::notify being emitted, even if the new value is the same as the old.
  /// If they did pass %G_PARAM_EXPLICIT_NOTIFY, then this signal is emitted only
  /// when they explicitly call g_object_notify() or g_object_notify_by_pspec(),
  /// and common practice is to do that only when the value has actually changed.
  ///
  /// This signal is typically used to obtain change notification for a
  /// single property, by specifying the property name as a detail in the
  /// g_signal_connect() call, like this:
  ///
  /// |[<!-- language="C" -->
  /// g_signal_connect (text_view->buffer, "notify::paste-target-list",
  /// G_CALLBACK (gtk_text_view_target_list_notify),
  /// text_view)
  /// ]|
  ///
  /// It is important to note that you must use
  /// [canonical parameter names][class@GObject.ParamSpec#parameter-names] as
  /// detail strings for the notify signal.
  int onNotify(void Function(GParamSpec pspec) callback) {
    return _connectSignal_v_1_o_gparamspec(this.handle, 'notify', callback);
  }

  /// Calls the @complete_interface_info function from the
  /// #GTypePluginClass of @plugin. There should be no need to use this
  /// function outside of the GObject type system itself.
  static final _gTypePluginCompleteInterfaceInfo =
      gioLookup<
            ffi.NativeFunction<
              ffi.Void Function(
                ffi.Pointer<ffi.Void>,
                ffi.Size,
                ffi.Size,
                ffi.Pointer<ffi.Void>,
              )
            >
          >('g_type_plugin_complete_interface_info')
          .asFunction<
            void Function(
              ffi.Pointer<ffi.Void>,
              int,
              int,
              ffi.Pointer<ffi.Void>,
            )
          >();
  void completeInterfaceInfo(
    int instanceType,
    int interfaceType,
    GInterfaceInfo info,
  ) {
    _gTypePluginCompleteInterfaceInfo(
      this.handle,
      instanceType,
      interfaceType,
      info.handle,
    );
  }

  /// Calls the @complete_type_info function from the #GTypePluginClass of @plugin.
  /// There should be no need to use this function outside of the GObject
  /// type system itself.
  static final _gTypePluginCompleteTypeInfo =
      gioLookup<
            ffi.NativeFunction<
              ffi.Void Function(
                ffi.Pointer<ffi.Void>,
                ffi.Size,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Void>,
              )
            >
          >('g_type_plugin_complete_type_info')
          .asFunction<
            void Function(
              ffi.Pointer<ffi.Void>,
              int,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Void>,
            )
          >();
  void completeTypeInfo(int gType, GTypeInfo info, GTypeValueTable valueTable) {
    _gTypePluginCompleteTypeInfo(
      this.handle,
      gType,
      info.handle,
      valueTable.handle,
    );
  }

  /// Calls the @unuse_plugin function from the #GTypePluginClass of
  /// @plugin.  There should be no need to use this function outside of
  /// the GObject type system itself.
  static final _gTypePluginUnuse =
      gioLookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'g_type_plugin_unuse',
      ).asFunction<void Function(ffi.Pointer<ffi.Void>)>();
  void unuse() {
    _gTypePluginUnuse(this.handle);
  }

  /// Calls the @use_plugin function from the #GTypePluginClass of
  /// @plugin.  There should be no need to use this function outside of
  /// the GObject type system itself.
  static final _gTypePluginUse =
      gioLookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'g_type_plugin_use',
      ).asFunction<void Function(ffi.Pointer<ffi.Void>)>();
  void useIOModule() {
    _gTypePluginUse(this.handle);
  }
}
