// Generated by gir_generator. Do not edit.
part of '../gio.dart';

/// A `GSocket` is a low-level networking primitive. It is a more or less
/// direct mapping of the BSD socket API in a portable GObject based API.
/// It supports both the UNIX socket implementations and winsock2 on Windows.
///
/// `GSocket` is the platform independent base upon which the higher level
/// network primitives are based. Applications are not typically meant to
/// use it directly, but rather through classes like [class@Gio.SocketClient],
/// [class@Gio.SocketService] and [class@Gio.SocketConnection]. However there may
/// be cases where direct use of `GSocket` is useful.
///
/// `GSocket` implements the [iface@Gio.Initable] interface, so if it is manually
/// constructed by e.g. [ctor@GObject.Object.new] you must call
/// [method@Gio.Initable.init] and check the results before using the object.
/// This is done automatically in [ctor@Gio.Socket.new] and
/// [ctor@Gio.Socket.new_from_fd], so these functions can return `NULL`.
///
/// Sockets operate in two general modes, blocking or non-blocking. When
/// in blocking mode all operations (which don’t take an explicit blocking
/// parameter) block until the requested operation
/// is finished or there is an error. In non-blocking mode all calls that
/// would block return immediately with a `G_IO_ERROR_WOULD_BLOCK` error.
/// To know when a call would successfully run you can call
/// [method@Gio.Socket.condition_check], or [method@Gio.Socket.condition_wait].
/// You can also use [method@Gio.Socket.create_source] and attach it to a
/// [type@GLib.MainContext] to get callbacks when I/O is possible.
/// Note that all sockets are always set to non blocking mode in the system, and
/// blocking mode is emulated in `GSocket`.
///
/// When working in non-blocking mode applications should always be able to
/// handle getting a `G_IO_ERROR_WOULD_BLOCK` error even when some other
/// function said that I/O was possible. This can easily happen in case
/// of a race condition in the application, but it can also happen for other
/// reasons. For instance, on Windows a socket is always seen as writable
/// until a write returns `G_IO_ERROR_WOULD_BLOCK`.
///
/// `GSocket`s can be either connection oriented or datagram based.
/// For connection oriented types you must first establish a connection by
/// either connecting to an address or accepting a connection from another
/// address. For connectionless socket types the target/source address is
/// specified or received in each I/O operation.
///
/// All socket file descriptors are set to be close-on-exec.
///
/// Note that creating a `GSocket` causes the signal `SIGPIPE` to be
/// ignored for the remainder of the program. If you are writing a
/// command-line utility that uses `GSocket`, you may need to take into
/// account the fact that your program will not automatically be killed
/// if it tries to write to `stdout` after it has been closed.
///
/// Like most other APIs in GLib, `GSocket` is not inherently thread safe. To use
/// a `GSocket` concurrently from multiple threads, you must implement your own
/// locking.
///
/// ## Nagle’s algorithm
///
/// Since GLib 2.80, `GSocket` will automatically set the `TCP_NODELAY` option on
/// all `G_SOCKET_TYPE_STREAM` sockets. This disables
/// [Nagle’s algorithm](https://en.wikipedia.org/wiki/Nagle%27s_algorithm) as it
/// typically does more harm than good on modern networks.
///
/// If your application needs Nagle’s algorithm enabled, call
/// [method@Gio.Socket.set_option] after constructing a `GSocket` to enable it:
/// ```c
/// socket = g_socket_new (…, G_SOCKET_TYPE_STREAM, …);
/// if (socket != NULL)
/// {
/// g_socket_set_option (socket, IPPROTO_TCP, TCP_NODELAY, FALSE, &local_error);
/// // handle error if needed
/// }
/// ```
class GSocket extends GObject {
  GSocket.fromPointer(super.handle, {super.owned}) : super.fromPointer();

  /// Creates a new #GSocket with the defined family, type and protocol.
  /// If @protocol is 0 (%G_SOCKET_PROTOCOL_DEFAULT) the default protocol type
  /// for the family and type is used.
  ///
  /// The @protocol is a family and type specific int that specifies what
  /// kind of protocol to use. #GSocketProtocol lists several common ones.
  /// Many families only support one protocol, and use 0 for this, others
  /// support several and using 0 means to use the default protocol for
  /// the family and type.
  ///
  /// The protocol id is passed directly to the operating
  /// system, so you can use protocols not listed in #GSocketProtocol if you
  /// know the protocol number used for it.
  static final _gSocketNew =
      gioLookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(
                ffi.Int32,
                ffi.Int32,
                ffi.Int32,
                ffi.Pointer<ffi.Pointer<ffi.Void>>,
              )
            >
          >('g_socket_new')
          .asFunction<
            ffi.Pointer<ffi.Void> Function(
              int,
              int,
              int,
              ffi.Pointer<ffi.Pointer<ffi.Void>>,
            )
          >();
  factory GSocket(
    GSocketFamily family,
    GSocketType type_,
    GSocketProtocol protocol,
  ) {
    final _error = calloc<ffi.Pointer<ffi.Void>>();
    try {
      final _ret = _gSocketNew(
        family.value,
        type_.value,
        protocol.value,
        _error,
      );
      if (_error.value != ffi.nullptr) {
        throw GlibException.fromError(_error.value);
      }
      return GSocket.fromPointer(_ret, owned: true);
    } finally {
      calloc.free(_error);
    }
  }

  /// Creates a new #GSocket from a native file descriptor
  /// or winsock SOCKET handle.
  ///
  /// This reads all the settings from the file descriptor so that
  /// all properties should work. Note that the file descriptor
  /// will be set to non-blocking mode, independent on the blocking
  /// mode of the #GSocket.
  ///
  /// On success, the returned #GSocket takes ownership of @fd. On failure, the
  /// caller must close @fd themselves.
  ///
  /// Since GLib 2.46, it is no longer a fatal error to call this on a non-socket
  /// descriptor.  Instead, a GError will be set with code %G_IO_ERROR_FAILED
  static final _gSocketNewFromFd =
      gioLookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(
                ffi.Int32,
                ffi.Pointer<ffi.Pointer<ffi.Void>>,
              )
            >
          >('g_socket_new_from_fd')
          .asFunction<
            ffi.Pointer<ffi.Void> Function(
              int,
              ffi.Pointer<ffi.Pointer<ffi.Void>>,
            )
          >();
  factory GSocket.fromFd(int fd) {
    final _error = calloc<ffi.Pointer<ffi.Void>>();
    try {
      final _ret = _gSocketNewFromFd(fd, _error);
      if (_error.value != ffi.nullptr) {
        throw GlibException.fromError(_error.value);
      }
      return GSocket.fromPointer(_ret, owned: true);
    } finally {
      calloc.free(_error);
    }
  }

  /// Accept incoming connections on a connection-based socket. This removes
  /// the first outstanding connection request from the listening socket and
  /// creates a #GSocket object for it.
  ///
  /// The @socket must be bound to a local address with g_socket_bind() and
  /// must be listening for incoming connections (g_socket_listen()).
  ///
  /// If there are no outstanding connections then the operation will block
  /// or return %G_IO_ERROR_WOULD_BLOCK if non-blocking I/O is enabled.
  /// To be notified of an incoming connection, wait for the %G_IO_IN condition.
  static final _gSocketAccept =
      gioLookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Pointer<ffi.Void>>,
              )
            >
          >('g_socket_accept')
          .asFunction<
            ffi.Pointer<ffi.Void> Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Pointer<ffi.Void>>,
            )
          >();
  GSocket accept([GCancellable? cancellable]) {
    final _error = calloc<ffi.Pointer<ffi.Void>>();
    try {
      final _ret = _gSocketAccept(
        this.handle,
        cancellable?.handle ?? ffi.nullptr,
        _error,
      );
      if (_error.value != ffi.nullptr) {
        throw GlibException.fromError(_error.value);
      }
      return GSocket.fromPointer(_ret);
    } finally {
      calloc.free(_error);
    }
  }

  /// When a socket is created it is attached to an address family, but it
  /// doesn't have an address in this family. g_socket_bind() assigns the
  /// address (sometimes called name) of the socket.
  ///
  /// It is generally required to bind to a local address before you can
  /// receive connections. (See g_socket_listen() and g_socket_accept() ).
  /// In certain situations, you may also want to bind a socket that will be
  /// used to initiate connections, though this is not normally required.
  ///
  /// If @socket is a TCP socket, then @allow_reuse controls the setting
  /// of the `SO_REUSEADDR` socket option; normally it should be %TRUE for
  /// server sockets (sockets that you will eventually call
  /// g_socket_accept() on), and %FALSE for client sockets. (Failing to
  /// set this flag on a server socket may cause g_socket_bind() to return
  /// %G_IO_ERROR_ADDRESS_IN_USE if the server program is stopped and then
  /// immediately restarted.)
  ///
  /// If @socket is a UDP socket, then @allow_reuse determines whether or
  /// not other UDP sockets can be bound to the same address at the same
  /// time. In particular, you can have several UDP sockets bound to the
  /// same address, and they will all receive all of the multicast and
  /// broadcast packets sent to that address. (The behavior of unicast
  /// UDP packets to an address with multiple listeners is not defined.)
  static final _gSocketBind =
      gioLookup<
            ffi.NativeFunction<
              ffi.Int32 Function(
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Void>,
                ffi.Int32,
                ffi.Pointer<ffi.Pointer<ffi.Void>>,
              )
            >
          >('g_socket_bind')
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Void>,
              int,
              ffi.Pointer<ffi.Pointer<ffi.Void>>,
            )
          >();
  bool bind(GSocketAddress address, bool allowReuse) {
    final _error = calloc<ffi.Pointer<ffi.Void>>();
    try {
      final _ret = _gSocketBind(
        this.handle,
        address.handle,
        allowReuse ? 1 : 0,
        _error,
      );
      if (_error.value != ffi.nullptr) {
        throw GlibException.fromError(_error.value);
      }
      return (_ret) != 0;
    } finally {
      calloc.free(_error);
    }
  }

  /// Checks and resets the pending connect error for the socket.
  /// This is used to check for errors when g_socket_connect() is
  /// used in non-blocking mode.
  static final _gSocketCheckConnectResult =
      gioLookup<
            ffi.NativeFunction<
              ffi.Int32 Function(
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Pointer<ffi.Void>>,
              )
            >
          >('g_socket_check_connect_result')
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Pointer<ffi.Void>>,
            )
          >();
  bool checkConnectResult() {
    final _error = calloc<ffi.Pointer<ffi.Void>>();
    try {
      final _ret = _gSocketCheckConnectResult(this.handle, _error);
      if (_error.value != ffi.nullptr) {
        throw GlibException.fromError(_error.value);
      }
      return (_ret) != 0;
    } finally {
      calloc.free(_error);
    }
  }

  /// Closes the socket, shutting down any active connection.
  ///
  /// Closing a socket does not wait for all outstanding I/O operations
  /// to finish, so the caller should not rely on them to be guaranteed
  /// to complete even if the close returns with no error.
  ///
  /// Once the socket is closed, all other operations will return
  /// %G_IO_ERROR_CLOSED. Closing a socket multiple times will not
  /// return an error.
  ///
  /// Sockets will be automatically closed when the last reference
  /// is dropped, but you might want to call this function to make sure
  /// resources are released as early as possible.
  ///
  /// Beware that due to the way that TCP works, it is possible for
  /// recently-sent data to be lost if either you close a socket while the
  /// %G_IO_IN condition is set, or else if the remote connection tries to
  /// send something to you after you close the socket but before it has
  /// finished reading all of the data you sent. There is no easy generic
  /// way to avoid this problem; the easiest fix is to design the network
  /// protocol such that the client will never send data "out of turn".
  /// Another solution is for the server to half-close the connection by
  /// calling g_socket_shutdown() with only the @shutdown_write flag set,
  /// and then wait for the client to notice this and close its side of the
  /// connection, after which the server can safely call g_socket_close().
  /// (This is what #GTcpConnection does if you call
  /// g_tcp_connection_set_graceful_disconnect(). But of course, this
  /// only works if the client will close its connection after the server
  /// does.)
  static final _gSocketClose =
      gioLookup<
            ffi.NativeFunction<
              ffi.Int32 Function(
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Pointer<ffi.Void>>,
              )
            >
          >('g_socket_close')
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Pointer<ffi.Void>>,
            )
          >();
  bool close() {
    final _error = calloc<ffi.Pointer<ffi.Void>>();
    try {
      final _ret = _gSocketClose(this.handle, _error);
      if (_error.value != ffi.nullptr) {
        throw GlibException.fromError(_error.value);
      }
      return (_ret) != 0;
    } finally {
      calloc.free(_error);
    }
  }

  /// Checks on the readiness of @socket to perform operations.
  /// The operations specified in @condition are checked for and masked
  /// against the currently-satisfied conditions on @socket. The result
  /// is returned.
  ///
  /// Note that on Windows, it is possible for an operation to return
  /// %G_IO_ERROR_WOULD_BLOCK even immediately after
  /// g_socket_condition_check() has claimed that the socket is ready for
  /// writing. Rather than calling g_socket_condition_check() and then
  /// writing to the socket if it succeeds, it is generally better to
  /// simply try writing to the socket right away, and try again later if
  /// the initial attempt returns %G_IO_ERROR_WOULD_BLOCK.
  ///
  /// It is meaningless to specify %G_IO_ERR or %G_IO_HUP in condition;
  /// these conditions will always be set in the output if they are true.
  ///
  /// This call never blocks.
  static final _gSocketConditionCheck =
      gioLookup<
            ffi.NativeFunction<
              ffi.Uint32 Function(ffi.Pointer<ffi.Void>, ffi.Uint32)
            >
          >('g_socket_condition_check')
          .asFunction<int Function(ffi.Pointer<ffi.Void>, int)>();
  GIOCondition conditionCheck(GIOCondition condition) {
    return GIOCondition(_gSocketConditionCheck(this.handle, condition.value));
  }

  /// Waits for up to @timeout_us microseconds for @condition to become true
  /// on @socket. If the condition is met, %TRUE is returned.
  ///
  /// If @cancellable is cancelled before the condition is met, or if
  /// @timeout_us (or the socket's #GSocket:timeout) is reached before the
  /// condition is met, then %FALSE is returned and @error, if non-%NULL,
  /// is set to the appropriate value (%G_IO_ERROR_CANCELLED or
  /// %G_IO_ERROR_TIMED_OUT).
  ///
  /// If you don't want a timeout, use g_socket_condition_wait().
  /// (Alternatively, you can pass -1 for @timeout_us.)
  ///
  /// Note that although @timeout_us is in microseconds for consistency with
  /// other GLib APIs, this function actually only has millisecond
  /// resolution, and the behavior is undefined if @timeout_us is not an
  /// exact number of milliseconds.
  static final _gSocketConditionTimedWait =
      gioLookup<
            ffi.NativeFunction<
              ffi.Int32 Function(
                ffi.Pointer<ffi.Void>,
                ffi.Uint32,
                ffi.Int64,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Pointer<ffi.Void>>,
              )
            >
          >('g_socket_condition_timed_wait')
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              int,
              int,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Pointer<ffi.Void>>,
            )
          >();
  bool conditionTimedWait(
    GIOCondition condition,
    int timeoutUs, [
    GCancellable? cancellable,
  ]) {
    final _error = calloc<ffi.Pointer<ffi.Void>>();
    try {
      final _ret = _gSocketConditionTimedWait(
        this.handle,
        condition.value,
        timeoutUs,
        cancellable?.handle ?? ffi.nullptr,
        _error,
      );
      if (_error.value != ffi.nullptr) {
        throw GlibException.fromError(_error.value);
      }
      return (_ret) != 0;
    } finally {
      calloc.free(_error);
    }
  }

  /// Waits for @condition to become true on @socket. When the condition
  /// is met, %TRUE is returned.
  ///
  /// If @cancellable is cancelled before the condition is met, or if the
  /// socket has a timeout set and it is reached before the condition is
  /// met, then %FALSE is returned and @error, if non-%NULL, is set to
  /// the appropriate value (%G_IO_ERROR_CANCELLED or
  /// %G_IO_ERROR_TIMED_OUT).
  ///
  /// See also g_socket_condition_timed_wait().
  static final _gSocketConditionWait =
      gioLookup<
            ffi.NativeFunction<
              ffi.Int32 Function(
                ffi.Pointer<ffi.Void>,
                ffi.Uint32,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Pointer<ffi.Void>>,
              )
            >
          >('g_socket_condition_wait')
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              int,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Pointer<ffi.Void>>,
            )
          >();
  bool conditionWait(GIOCondition condition, [GCancellable? cancellable]) {
    final _error = calloc<ffi.Pointer<ffi.Void>>();
    try {
      final _ret = _gSocketConditionWait(
        this.handle,
        condition.value,
        cancellable?.handle ?? ffi.nullptr,
        _error,
      );
      if (_error.value != ffi.nullptr) {
        throw GlibException.fromError(_error.value);
      }
      return (_ret) != 0;
    } finally {
      calloc.free(_error);
    }
  }

  /// Connect the socket to the specified remote address.
  ///
  /// For connection oriented socket this generally means we attempt to make
  /// a connection to the @address. For a connection-less socket it sets
  /// the default address for g_socket_send() and discards all incoming datagrams
  /// from other sources.
  ///
  /// Generally connection oriented sockets can only connect once, but
  /// connection-less sockets can connect multiple times to change the
  /// default address.
  ///
  /// If the connect call needs to do network I/O it will block, unless
  /// non-blocking I/O is enabled. Then %G_IO_ERROR_PENDING is returned
  /// and the user can be notified of the connection finishing by waiting
  /// for the G_IO_OUT condition. The result of the connection must then be
  /// checked with g_socket_check_connect_result().
  static final _gSocketConnect =
      gioLookup<
            ffi.NativeFunction<
              ffi.Int32 Function(
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Pointer<ffi.Void>>,
              )
            >
          >('g_socket_connect')
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Pointer<ffi.Void>>,
            )
          >();
  bool connect(GSocketAddress address, [GCancellable? cancellable]) {
    final _error = calloc<ffi.Pointer<ffi.Void>>();
    try {
      final _ret = _gSocketConnect(
        this.handle,
        address.handle,
        cancellable?.handle ?? ffi.nullptr,
        _error,
      );
      if (_error.value != ffi.nullptr) {
        throw GlibException.fromError(_error.value);
      }
      return (_ret) != 0;
    } finally {
      calloc.free(_error);
    }
  }

  /// Creates a #GSocketConnection subclass of the right type for
  /// @socket.
  static final _gSocketConnectionFactoryCreateConnection =
      gioLookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)
            >
          >('g_socket_connection_factory_create_connection')
          .asFunction<ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)>();
  GSocketConnection connectionFactoryCreateConnection() {
    return GSocketConnection.fromPointer(
      _gSocketConnectionFactoryCreateConnection(this.handle),
    );
  }

  /// Get the amount of data pending in the OS input buffer, without blocking.
  ///
  /// If @socket is a UDP or SCTP socket, this will return the size of
  /// just the next packet, even if additional packets are buffered after
  /// that one.
  ///
  /// Note that on Windows, this function is rather inefficient in the
  /// UDP case, and so if you know any plausible upper bound on the size
  /// of the incoming packet, it is better to just do a
  /// g_socket_receive() with a buffer of that size, rather than calling
  /// g_socket_get_available_bytes() first and then doing a receive of
  /// exactly the right size.
  static final _gSocketGetAvailableBytes =
      gioLookup<ffi.NativeFunction<ffi.IntPtr Function(ffi.Pointer<ffi.Void>)>>(
        'g_socket_get_available_bytes',
      ).asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  int getAvailableBytes() {
    return _gSocketGetAvailableBytes(this.handle);
  }

  /// Gets the blocking mode of the socket. For details on blocking I/O,
  /// see g_socket_set_blocking().
  static final _gSocketGetBlocking =
      gioLookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Void>)>>(
        'g_socket_get_blocking',
      ).asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  bool getBlocking() {
    return (_gSocketGetBlocking(this.handle)) != 0;
  }

  /// Gets the broadcast setting on @socket; if %TRUE,
  /// it is possible to send packets to broadcast
  /// addresses.
  static final _gSocketGetBroadcast =
      gioLookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Void>)>>(
        'g_socket_get_broadcast',
      ).asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  bool getBroadcast() {
    return (_gSocketGetBroadcast(this.handle)) != 0;
  }

  /// Returns the credentials of the foreign process connected to this
  /// socket, if any (e.g. it is only supported for %G_SOCKET_FAMILY_UNIX
  /// sockets).
  ///
  /// If this operation isn't supported on the OS, the method fails with
  /// the %G_IO_ERROR_NOT_SUPPORTED error. On Linux this is implemented
  /// by reading the %SO_PEERCRED option on the underlying socket.
  ///
  /// This method can be expected to be available on the following platforms:
  ///
  /// - Linux since GLib 2.26
  /// - OpenBSD since GLib 2.30
  /// - Solaris, Illumos and OpenSolaris since GLib 2.40
  /// - NetBSD since GLib 2.42
  /// - macOS, tvOS, iOS since GLib 2.66
  ///
  /// Other ways to obtain credentials from a foreign peer includes the
  /// #GUnixCredentialsMessage type and
  /// g_unix_connection_send_credentials() /
  /// g_unix_connection_receive_credentials() functions.
  static final _gSocketGetCredentials =
      gioLookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Pointer<ffi.Void>>,
              )
            >
          >('g_socket_get_credentials')
          .asFunction<
            ffi.Pointer<ffi.Void> Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Pointer<ffi.Void>>,
            )
          >();
  GCredentials getCredentials() {
    final _error = calloc<ffi.Pointer<ffi.Void>>();
    try {
      final _ret = _gSocketGetCredentials(this.handle, _error);
      if (_error.value != ffi.nullptr) {
        throw GlibException.fromError(_error.value);
      }
      return GCredentials.fromPointer(_ret);
    } finally {
      calloc.free(_error);
    }
  }

  /// Gets the socket family of the socket.
  static final _gSocketGetFamily =
      gioLookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Void>)>>(
        'g_socket_get_family',
      ).asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  GSocketFamily getFamily() {
    return GSocketFamily.fromValue(_gSocketGetFamily(this.handle));
  }

  /// Returns the underlying OS socket object. On unix this
  /// is a socket file descriptor, and on Windows this is
  /// a Winsock2 SOCKET handle. This may be useful for
  /// doing platform specific or otherwise unusual operations
  /// on the socket.
  static final _gSocketGetFd =
      gioLookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Void>)>>(
        'g_socket_get_fd',
      ).asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  int getFd() {
    return _gSocketGetFd(this.handle);
  }

  /// Gets the keepalive mode of the socket. For details on this,
  /// see g_socket_set_keepalive().
  static final _gSocketGetKeepalive =
      gioLookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Void>)>>(
        'g_socket_get_keepalive',
      ).asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  bool getKeepalive() {
    return (_gSocketGetKeepalive(this.handle)) != 0;
  }

  /// Gets the listen backlog setting of the socket. For details on this,
  /// see g_socket_set_listen_backlog().
  static final _gSocketGetListenBacklog =
      gioLookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Void>)>>(
        'g_socket_get_listen_backlog',
      ).asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  int getListenBacklog() {
    return _gSocketGetListenBacklog(this.handle);
  }

  /// Try to get the local address of a bound socket. This is only
  /// useful if the socket has been bound to a local address,
  /// either explicitly or implicitly when connecting.
  static final _gSocketGetLocalAddress =
      gioLookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Pointer<ffi.Void>>,
              )
            >
          >('g_socket_get_local_address')
          .asFunction<
            ffi.Pointer<ffi.Void> Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Pointer<ffi.Void>>,
            )
          >();
  GSocketAddress getLocalAddress() {
    final _error = calloc<ffi.Pointer<ffi.Void>>();
    try {
      final _ret = _gSocketGetLocalAddress(this.handle, _error);
      if (_error.value != ffi.nullptr) {
        throw GlibException.fromError(_error.value);
      }
      return GSocketAddress.fromPointer(_ret);
    } finally {
      calloc.free(_error);
    }
  }

  /// Gets the multicast loopback setting on @socket; if %TRUE (the
  /// default), outgoing multicast packets will be looped back to
  /// multicast listeners on the same host.
  static final _gSocketGetMulticastLoopback =
      gioLookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Void>)>>(
        'g_socket_get_multicast_loopback',
      ).asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  bool getMulticastLoopback() {
    return (_gSocketGetMulticastLoopback(this.handle)) != 0;
  }

  /// Gets the multicast time-to-live setting on @socket; see
  /// g_socket_set_multicast_ttl() for more details.
  static final _gSocketGetMulticastTtl =
      gioLookup<ffi.NativeFunction<ffi.Uint32 Function(ffi.Pointer<ffi.Void>)>>(
        'g_socket_get_multicast_ttl',
      ).asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  int getMulticastTtl() {
    return _gSocketGetMulticastTtl(this.handle);
  }

  /// Gets the value of an integer-valued option on @socket, as with
  /// getsockopt(). (If you need to fetch a  non-integer-valued option,
  /// you will need to call getsockopt() directly.)
  ///
  /// The [`<gio/gnetworking.h>`](networking.html)
  /// header pulls in system headers that will define most of the
  /// standard/portable socket options. For unusual socket protocols or
  /// platform-dependent options, you may need to include additional
  /// headers.
  ///
  /// Note that even for socket options that are a single byte in size,
  /// @value is still a pointer to a #gint variable, not a #guchar;
  /// g_socket_get_option() will handle the conversion internally.
  static final _gSocketGetOption =
      gioLookup<
            ffi.NativeFunction<
              ffi.Int32 Function(
                ffi.Pointer<ffi.Void>,
                ffi.Int32,
                ffi.Int32,
                ffi.Pointer<ffi.Int32>,
                ffi.Pointer<ffi.Pointer<ffi.Void>>,
              )
            >
          >('g_socket_get_option')
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              int,
              int,
              ffi.Pointer<ffi.Int32>,
              ffi.Pointer<ffi.Pointer<ffi.Void>>,
            )
          >();
  (bool, int) getOption(int level, int optname) {
    final _out0 = malloc<ffi.Int32>();
    final _error = calloc<ffi.Pointer<ffi.Void>>();
    try {
      final _ret = _gSocketGetOption(
        this.handle,
        level,
        optname,
        _out0,
        _error,
      );
      if (_error.value != ffi.nullptr) {
        throw GlibException.fromError(_error.value);
      }
      return ((_ret) != 0, _out0.value);
    } finally {
      malloc.free(_out0);
      calloc.free(_error);
    }
  }

  /// Gets the socket protocol id the socket was created with.
  /// In case the protocol is unknown, -1 is returned.
  static final _gSocketGetProtocol =
      gioLookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Void>)>>(
        'g_socket_get_protocol',
      ).asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  GSocketProtocol getProtocol() {
    return GSocketProtocol.fromValue(_gSocketGetProtocol(this.handle));
  }

  /// Try to get the remote address of a connected socket. This is only
  /// useful for connection oriented sockets that have been connected.
  static final _gSocketGetRemoteAddress =
      gioLookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Pointer<ffi.Void>>,
              )
            >
          >('g_socket_get_remote_address')
          .asFunction<
            ffi.Pointer<ffi.Void> Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Pointer<ffi.Void>>,
            )
          >();
  GSocketAddress getRemoteAddress() {
    final _error = calloc<ffi.Pointer<ffi.Void>>();
    try {
      final _ret = _gSocketGetRemoteAddress(this.handle, _error);
      if (_error.value != ffi.nullptr) {
        throw GlibException.fromError(_error.value);
      }
      return GSocketAddress.fromPointer(_ret);
    } finally {
      calloc.free(_error);
    }
  }

  /// Gets the socket type of the socket.
  static final _gSocketGetSocketType =
      gioLookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Void>)>>(
        'g_socket_get_socket_type',
      ).asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  GSocketType getSocketType() {
    return GSocketType.fromValue(_gSocketGetSocketType(this.handle));
  }

  /// Gets the timeout setting of the socket. For details on this, see
  /// g_socket_set_timeout().
  static final _gSocketGetTimeout =
      gioLookup<ffi.NativeFunction<ffi.Uint32 Function(ffi.Pointer<ffi.Void>)>>(
        'g_socket_get_timeout',
      ).asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  int getTimeout() {
    return _gSocketGetTimeout(this.handle);
  }

  /// Gets the unicast time-to-live setting on @socket; see
  /// g_socket_set_ttl() for more details.
  static final _gSocketGetTtl =
      gioLookup<ffi.NativeFunction<ffi.Uint32 Function(ffi.Pointer<ffi.Void>)>>(
        'g_socket_get_ttl',
      ).asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  int getTtl() {
    return _gSocketGetTtl(this.handle);
  }

  /// Checks whether a socket is closed.
  static final _gSocketIsClosed =
      gioLookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Void>)>>(
        'g_socket_is_closed',
      ).asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  bool isClosed() {
    return (_gSocketIsClosed(this.handle)) != 0;
  }

  /// Check whether the socket is connected. This is only useful for
  /// connection-oriented sockets.
  ///
  /// If using g_socket_shutdown(), this function will return %TRUE until the
  /// socket has been shut down for reading and writing. If you do a non-blocking
  /// connect, this function will not return %TRUE until after you call
  /// g_socket_check_connect_result().
  static final _gSocketIsConnected =
      gioLookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Void>)>>(
        'g_socket_is_connected',
      ).asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  bool isConnected() {
    return (_gSocketIsConnected(this.handle)) != 0;
  }

  /// Registers @socket to receive multicast messages sent to @group.
  /// @socket must be a %G_SOCKET_TYPE_DATAGRAM socket, and must have
  /// been bound to an appropriate interface and port with
  /// g_socket_bind().
  ///
  /// If @iface is %NULL, the system will automatically pick an interface
  /// to bind to based on @group.
  ///
  /// If @source_specific is %TRUE, source-specific multicast as defined
  /// in RFC 4604 is used. Note that on older platforms this may fail
  /// with a %G_IO_ERROR_NOT_SUPPORTED error.
  ///
  /// To bind to a given source-specific multicast address, use
  /// g_socket_join_multicast_group_ssm() instead.
  static final _gSocketJoinMulticastGroup =
      gioLookup<
            ffi.NativeFunction<
              ffi.Int32 Function(
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Void>,
                ffi.Int32,
                ffi.Pointer<Utf8>,
                ffi.Pointer<ffi.Pointer<ffi.Void>>,
              )
            >
          >('g_socket_join_multicast_group')
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Void>,
              int,
              ffi.Pointer<Utf8>,
              ffi.Pointer<ffi.Pointer<ffi.Void>>,
            )
          >();
  bool joinMulticastGroup(
    GInetAddress group,
    bool sourceSpecific, [
    String? iface,
  ]) {
    return withNativeString(iface, (nativeIface) {
      final _error = calloc<ffi.Pointer<ffi.Void>>();
      try {
        final _ret = _gSocketJoinMulticastGroup(
          this.handle,
          group.handle,
          sourceSpecific ? 1 : 0,
          nativeIface.cast<Utf8>(),
          _error,
        );
        if (_error.value != ffi.nullptr) {
          throw GlibException.fromError(_error.value);
        }
        return (_ret) != 0;
      } finally {
        calloc.free(_error);
      }
    });
  }

  /// Registers @socket to receive multicast messages sent to @group.
  /// @socket must be a %G_SOCKET_TYPE_DATAGRAM socket, and must have
  /// been bound to an appropriate interface and port with
  /// g_socket_bind().
  ///
  /// If @iface is %NULL, the system will automatically pick an interface
  /// to bind to based on @group.
  ///
  /// If @source_specific is not %NULL, use source-specific multicast as
  /// defined in RFC 4604. Note that on older platforms this may fail
  /// with a %G_IO_ERROR_NOT_SUPPORTED error.
  ///
  /// Note that this function can be called multiple times for the same
  /// @group with different @source_specific in order to receive multicast
  /// packets from more than one source.
  static final _gSocketJoinMulticastGroupSsm =
      gioLookup<
            ffi.NativeFunction<
              ffi.Int32 Function(
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<Utf8>,
                ffi.Pointer<ffi.Pointer<ffi.Void>>,
              )
            >
          >('g_socket_join_multicast_group_ssm')
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<Utf8>,
              ffi.Pointer<ffi.Pointer<ffi.Void>>,
            )
          >();
  bool joinMulticastGroupSsm(
    GInetAddress group, [
    GInetAddress? sourceSpecific,
    String? iface,
  ]) {
    return withNativeString(iface, (nativeIface) {
      final _error = calloc<ffi.Pointer<ffi.Void>>();
      try {
        final _ret = _gSocketJoinMulticastGroupSsm(
          this.handle,
          group.handle,
          sourceSpecific?.handle ?? ffi.nullptr,
          nativeIface.cast<Utf8>(),
          _error,
        );
        if (_error.value != ffi.nullptr) {
          throw GlibException.fromError(_error.value);
        }
        return (_ret) != 0;
      } finally {
        calloc.free(_error);
      }
    });
  }

  /// Removes @socket from the multicast group defined by @group, @iface,
  /// and @source_specific (which must all have the same values they had
  /// when you joined the group).
  ///
  /// @socket remains bound to its address and port, and can still receive
  /// unicast messages after calling this.
  ///
  /// To unbind to a given source-specific multicast address, use
  /// g_socket_leave_multicast_group_ssm() instead.
  static final _gSocketLeaveMulticastGroup =
      gioLookup<
            ffi.NativeFunction<
              ffi.Int32 Function(
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Void>,
                ffi.Int32,
                ffi.Pointer<Utf8>,
                ffi.Pointer<ffi.Pointer<ffi.Void>>,
              )
            >
          >('g_socket_leave_multicast_group')
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Void>,
              int,
              ffi.Pointer<Utf8>,
              ffi.Pointer<ffi.Pointer<ffi.Void>>,
            )
          >();
  bool leaveMulticastGroup(
    GInetAddress group,
    bool sourceSpecific, [
    String? iface,
  ]) {
    return withNativeString(iface, (nativeIface) {
      final _error = calloc<ffi.Pointer<ffi.Void>>();
      try {
        final _ret = _gSocketLeaveMulticastGroup(
          this.handle,
          group.handle,
          sourceSpecific ? 1 : 0,
          nativeIface.cast<Utf8>(),
          _error,
        );
        if (_error.value != ffi.nullptr) {
          throw GlibException.fromError(_error.value);
        }
        return (_ret) != 0;
      } finally {
        calloc.free(_error);
      }
    });
  }

  /// Removes @socket from the multicast group defined by @group, @iface,
  /// and @source_specific (which must all have the same values they had
  /// when you joined the group).
  ///
  /// @socket remains bound to its address and port, and can still receive
  /// unicast messages after calling this.
  static final _gSocketLeaveMulticastGroupSsm =
      gioLookup<
            ffi.NativeFunction<
              ffi.Int32 Function(
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<Utf8>,
                ffi.Pointer<ffi.Pointer<ffi.Void>>,
              )
            >
          >('g_socket_leave_multicast_group_ssm')
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<Utf8>,
              ffi.Pointer<ffi.Pointer<ffi.Void>>,
            )
          >();
  bool leaveMulticastGroupSsm(
    GInetAddress group, [
    GInetAddress? sourceSpecific,
    String? iface,
  ]) {
    return withNativeString(iface, (nativeIface) {
      final _error = calloc<ffi.Pointer<ffi.Void>>();
      try {
        final _ret = _gSocketLeaveMulticastGroupSsm(
          this.handle,
          group.handle,
          sourceSpecific?.handle ?? ffi.nullptr,
          nativeIface.cast<Utf8>(),
          _error,
        );
        if (_error.value != ffi.nullptr) {
          throw GlibException.fromError(_error.value);
        }
        return (_ret) != 0;
      } finally {
        calloc.free(_error);
      }
    });
  }

  /// Marks the socket as a server socket, i.e. a socket that is used
  /// to accept incoming requests using g_socket_accept().
  ///
  /// Before calling this the socket must be bound to a local address using
  /// g_socket_bind().
  ///
  /// To set the maximum amount of outstanding clients, use
  /// g_socket_set_listen_backlog().
  static final _gSocketListen =
      gioLookup<
            ffi.NativeFunction<
              ffi.Int32 Function(
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Pointer<ffi.Void>>,
              )
            >
          >('g_socket_listen')
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Pointer<ffi.Void>>,
            )
          >();
  bool listen() {
    final _error = calloc<ffi.Pointer<ffi.Void>>();
    try {
      final _ret = _gSocketListen(this.handle, _error);
      if (_error.value != ffi.nullptr) {
        throw GlibException.fromError(_error.value);
      }
      return (_ret) != 0;
    } finally {
      calloc.free(_error);
    }
  }

  /// Receives data (up to @size bytes) from a socket.
  ///
  /// This function is a variant of [method@Gio.Socket.receive] which returns a
  /// [struct@GLib.Bytes] rather than a plain buffer.
  ///
  /// Pass `-1` to @timeout_us to block indefinitely until data is received (or
  /// the connection is closed, or there is an error). Pass `0` to use the default
  /// timeout from [property@Gio.Socket:timeout], or pass a positive number to wait
  /// for that many microseconds for data before returning `G_IO_ERROR_TIMED_OUT`.
  static final _gSocketReceiveBytes =
      gioLookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(
                ffi.Pointer<ffi.Void>,
                ffi.Size,
                ffi.Int64,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Pointer<ffi.Void>>,
              )
            >
          >('g_socket_receive_bytes')
          .asFunction<
            ffi.Pointer<ffi.Void> Function(
              ffi.Pointer<ffi.Void>,
              int,
              int,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Pointer<ffi.Void>>,
            )
          >();
  GBytes receiveBytes(int size, int timeoutUs, [GCancellable? cancellable]) {
    final _error = calloc<ffi.Pointer<ffi.Void>>();
    try {
      final _ret = _gSocketReceiveBytes(
        this.handle,
        size,
        timeoutUs,
        cancellable?.handle ?? ffi.nullptr,
        _error,
      );
      if (_error.value != ffi.nullptr) {
        throw GlibException.fromError(_error.value);
      }
      return GBytes.fromPointer(_ret);
    } finally {
      calloc.free(_error);
    }
  }

  /// Receive data (up to @size bytes) from a socket.
  ///
  /// This function is a variant of [method@Gio.Socket.receive_from] which returns
  /// a [struct@GLib.Bytes] rather than a plain buffer.
  ///
  /// If @address is non-%NULL then @address will be set equal to the
  /// source address of the received packet.
  ///
  /// The @address is owned by the caller.
  ///
  /// Pass `-1` to @timeout_us to block indefinitely until data is received (or
  /// the connection is closed, or there is an error). Pass `0` to use the default
  /// timeout from [property@Gio.Socket:timeout], or pass a positive number to wait
  /// for that many microseconds for data before returning `G_IO_ERROR_TIMED_OUT`.
  static final _gSocketReceiveBytesFrom =
      gioLookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Void>,
                ffi.Size,
                ffi.Int64,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Pointer<ffi.Void>>,
              )
            >
          >('g_socket_receive_bytes_from')
          .asFunction<
            ffi.Pointer<ffi.Void> Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Void>,
              int,
              int,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Pointer<ffi.Void>>,
            )
          >();
  (GBytes, GSocketAddress?) receiveBytesFrom(
    int size,
    int timeoutUs, [
    GCancellable? cancellable,
  ]) {
    final _out0Anchor = HeapAnchor.allocate(256);
    final _out0 = _out0Anchor.buffer;
    final _error = calloc<ffi.Pointer<ffi.Void>>();
    try {
      final _ret = _gSocketReceiveBytesFrom(
        this.handle,
        _out0.cast<ffi.Void>(),
        size,
        timeoutUs,
        cancellable?.handle ?? ffi.nullptr,
        _error,
      );
      if (_error.value != ffi.nullptr) {
        throw GlibException.fromError(_error.value);
      }
      return (
        GBytes.fromPointer(_ret),
        (_out0) == ffi.nullptr
            ? null
            : GSocketAddress.fromPointer(_out0.cast<ffi.Void>()),
      );
    } finally {
      calloc.free(_error);
    }
  }

  /// Sets the blocking mode of the socket. In blocking mode
  /// all operations (which don’t take an explicit blocking parameter) block until
  /// they succeed or there is an error. In
  /// non-blocking mode all functions return results immediately or
  /// with a %G_IO_ERROR_WOULD_BLOCK error.
  ///
  /// All sockets are created in blocking mode. However, note that the
  /// platform level socket is always non-blocking, and blocking mode
  /// is a GSocket level feature.
  static final _gSocketSetBlocking =
      gioLookup<
            ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Int32)
            >
          >('g_socket_set_blocking')
          .asFunction<void Function(ffi.Pointer<ffi.Void>, int)>();
  void setBlocking(bool blocking) {
    _gSocketSetBlocking(this.handle, blocking ? 1 : 0);
  }

  /// Sets whether @socket should allow sending to broadcast addresses.
  /// This is %FALSE by default.
  static final _gSocketSetBroadcast =
      gioLookup<
            ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Int32)
            >
          >('g_socket_set_broadcast')
          .asFunction<void Function(ffi.Pointer<ffi.Void>, int)>();
  void setBroadcast(bool broadcast) {
    _gSocketSetBroadcast(this.handle, broadcast ? 1 : 0);
  }

  /// Sets or unsets the %SO_KEEPALIVE flag on the underlying socket. When
  /// this flag is set on a socket, the system will attempt to verify that the
  /// remote socket endpoint is still present if a sufficiently long period of
  /// time passes with no data being exchanged. If the system is unable to
  /// verify the presence of the remote endpoint, it will automatically close
  /// the connection.
  ///
  /// This option is only functional on certain kinds of sockets. (Notably,
  /// %G_SOCKET_PROTOCOL_TCP sockets.)
  ///
  /// The exact time between pings is system- and protocol-dependent, but will
  /// normally be at least two hours. Most commonly, you would set this flag
  /// on a server socket if you want to allow clients to remain idle for long
  /// periods of time, but also want to ensure that connections are eventually
  /// garbage-collected if clients crash or become unreachable.
  static final _gSocketSetKeepalive =
      gioLookup<
            ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Int32)
            >
          >('g_socket_set_keepalive')
          .asFunction<void Function(ffi.Pointer<ffi.Void>, int)>();
  void setKeepalive(bool keepalive) {
    _gSocketSetKeepalive(this.handle, keepalive ? 1 : 0);
  }

  /// Sets the maximum number of outstanding connections allowed
  /// when listening on this socket. If more clients than this are
  /// connecting to the socket and the application is not handling them
  /// on time then the new connections will be refused.
  ///
  /// Note that this must be called before g_socket_listen() and has no
  /// effect if called after that.
  static final _gSocketSetListenBacklog =
      gioLookup<
            ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Int32)
            >
          >('g_socket_set_listen_backlog')
          .asFunction<void Function(ffi.Pointer<ffi.Void>, int)>();
  void setListenBacklog(int backlog) {
    _gSocketSetListenBacklog(this.handle, backlog);
  }

  /// Sets whether outgoing multicast packets will be received by sockets
  /// listening on that multicast address on the same host. This is %TRUE
  /// by default.
  static final _gSocketSetMulticastLoopback =
      gioLookup<
            ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Int32)
            >
          >('g_socket_set_multicast_loopback')
          .asFunction<void Function(ffi.Pointer<ffi.Void>, int)>();
  void setMulticastLoopback(bool loopback) {
    _gSocketSetMulticastLoopback(this.handle, loopback ? 1 : 0);
  }

  /// Sets the time-to-live for outgoing multicast datagrams on @socket.
  /// By default, this is 1, meaning that multicast packets will not leave
  /// the local network.
  static final _gSocketSetMulticastTtl =
      gioLookup<
            ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Uint32)
            >
          >('g_socket_set_multicast_ttl')
          .asFunction<void Function(ffi.Pointer<ffi.Void>, int)>();
  void setMulticastTtl(int ttl) {
    _gSocketSetMulticastTtl(this.handle, ttl);
  }

  /// Sets the value of an integer-valued option on @socket, as with
  /// setsockopt(). (If you need to set a non-integer-valued option,
  /// you will need to call setsockopt() directly.)
  ///
  /// The [`<gio/gnetworking.h>`](networking.html)
  /// header pulls in system headers that will define most of the
  /// standard/portable socket options. For unusual socket protocols or
  /// platform-dependent options, you may need to include additional
  /// headers.
  static final _gSocketSetOption =
      gioLookup<
            ffi.NativeFunction<
              ffi.Int32 Function(
                ffi.Pointer<ffi.Void>,
                ffi.Int32,
                ffi.Int32,
                ffi.Int32,
                ffi.Pointer<ffi.Pointer<ffi.Void>>,
              )
            >
          >('g_socket_set_option')
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              int,
              int,
              int,
              ffi.Pointer<ffi.Pointer<ffi.Void>>,
            )
          >();
  bool setOption(int level, int optname, int value) {
    final _error = calloc<ffi.Pointer<ffi.Void>>();
    try {
      final _ret = _gSocketSetOption(
        this.handle,
        level,
        optname,
        value,
        _error,
      );
      if (_error.value != ffi.nullptr) {
        throw GlibException.fromError(_error.value);
      }
      return (_ret) != 0;
    } finally {
      calloc.free(_error);
    }
  }

  /// Sets the time in seconds after which I/O operations on @socket will
  /// time out if they have not yet completed.
  ///
  /// On a blocking socket, this means that any blocking #GSocket
  /// operation will time out after @timeout seconds of inactivity,
  /// returning %G_IO_ERROR_TIMED_OUT.
  ///
  /// On a non-blocking socket, calls to g_socket_condition_wait() will
  /// also fail with %G_IO_ERROR_TIMED_OUT after the given time. Sources
  /// created with g_socket_create_source() will trigger after
  /// @timeout seconds of inactivity, with the requested condition
  /// set, at which point calling g_socket_receive(), g_socket_send(),
  /// g_socket_check_connect_result(), etc, will fail with
  /// %G_IO_ERROR_TIMED_OUT.
  ///
  /// If @timeout is 0 (the default), operations will never time out
  /// on their own.
  ///
  /// Note that if an I/O operation is interrupted by a signal, this may
  /// cause the timeout to be reset.
  static final _gSocketSetTimeout =
      gioLookup<
            ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Uint32)
            >
          >('g_socket_set_timeout')
          .asFunction<void Function(ffi.Pointer<ffi.Void>, int)>();
  void setTimeout(int timeout) {
    _gSocketSetTimeout(this.handle, timeout);
  }

  /// Sets the time-to-live for outgoing unicast packets on @socket.
  /// By default the platform-specific default value is used.
  static final _gSocketSetTtl =
      gioLookup<
            ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Uint32)
            >
          >('g_socket_set_ttl')
          .asFunction<void Function(ffi.Pointer<ffi.Void>, int)>();
  void setTtl(int ttl) {
    _gSocketSetTtl(this.handle, ttl);
  }

  /// Shut down part or all of a full-duplex connection.
  ///
  /// If @shutdown_read is %TRUE then the receiving side of the connection
  /// is shut down, and further reading is disallowed.
  ///
  /// If @shutdown_write is %TRUE then the sending side of the connection
  /// is shut down, and further writing is disallowed.
  ///
  /// It is allowed for both @shutdown_read and @shutdown_write to be %TRUE.
  ///
  /// One example where it is useful to shut down only one side of a connection is
  /// graceful disconnect for TCP connections where you close the sending side,
  /// then wait for the other side to close the connection, thus ensuring that the
  /// other side saw all sent data.
  static final _gSocketShutdown =
      gioLookup<
            ffi.NativeFunction<
              ffi.Int32 Function(
                ffi.Pointer<ffi.Void>,
                ffi.Int32,
                ffi.Int32,
                ffi.Pointer<ffi.Pointer<ffi.Void>>,
              )
            >
          >('g_socket_shutdown')
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              int,
              int,
              ffi.Pointer<ffi.Pointer<ffi.Void>>,
            )
          >();
  bool shutdown(bool shutdownRead, bool shutdownWrite) {
    final _error = calloc<ffi.Pointer<ffi.Void>>();
    try {
      final _ret = _gSocketShutdown(
        this.handle,
        shutdownRead ? 1 : 0,
        shutdownWrite ? 1 : 0,
        _error,
      );
      if (_error.value != ffi.nullptr) {
        throw GlibException.fromError(_error.value);
      }
      return (_ret) != 0;
    } finally {
      calloc.free(_error);
    }
  }

  /// Checks if a socket is capable of speaking IPv4.
  ///
  /// IPv4 sockets are capable of speaking IPv4.  On some operating systems
  /// and under some combinations of circumstances IPv6 sockets are also
  /// capable of speaking IPv4.  See RFC 3493 section 3.7 for more
  /// information.
  ///
  /// No other types of sockets are currently considered as being capable
  /// of speaking IPv4.
  static final _gSocketSpeaksIpv4 =
      gioLookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Void>)>>(
        'g_socket_speaks_ipv4',
      ).asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  bool speaksIpv4() {
    return (_gSocketSpeaksIpv4(this.handle)) != 0;
  }

  /// The notify signal is emitted on an object when one of its properties has
  /// its value set through g_object_set_property(), g_object_set(), et al.
  ///
  /// Note that getting this signal doesn’t itself guarantee that the value of
  /// the property has actually changed. When it is emitted is determined by the
  /// derived GObject class. If the implementor did not create the property with
  /// %G_PARAM_EXPLICIT_NOTIFY, then any call to g_object_set_property() results
  /// in ::notify being emitted, even if the new value is the same as the old.
  /// If they did pass %G_PARAM_EXPLICIT_NOTIFY, then this signal is emitted only
  /// when they explicitly call g_object_notify() or g_object_notify_by_pspec(),
  /// and common practice is to do that only when the value has actually changed.
  ///
  /// This signal is typically used to obtain change notification for a
  /// single property, by specifying the property name as a detail in the
  /// g_signal_connect() call, like this:
  ///
  /// |[<!-- language="C" -->
  /// g_signal_connect (text_view->buffer, "notify::paste-target-list",
  /// G_CALLBACK (gtk_text_view_target_list_notify),
  /// text_view)
  /// ]|
  ///
  /// It is important to note that you must use
  /// [canonical parameter names][class@GObject.ParamSpec#parameter-names] as
  /// detail strings for the notify signal.
  int onNotify(void Function(GParamSpec pspec) callback) {
    return _connectSignal_v_1_o_gparamspec(this.handle, 'notify', callback);
  }

  /// Waits for up to @timeout microseconds for condition to become true on
  /// @datagram_based. If the condition is met, %TRUE is returned.
  ///
  /// If @cancellable is cancelled before the condition is met, or if @timeout is
  /// reached before the condition is met, then %FALSE is returned and @error is
  /// set appropriately (%G_IO_ERROR_CANCELLED or %G_IO_ERROR_TIMED_OUT).
  static final _gDatagramBasedConditionWait =
      gioLookup<
            ffi.NativeFunction<
              ffi.Int32 Function(
                ffi.Pointer<ffi.Void>,
                ffi.Uint32,
                ffi.Int64,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Pointer<ffi.Void>>,
              )
            >
          >('g_datagram_based_condition_wait')
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              int,
              int,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Pointer<ffi.Void>>,
            )
          >();
  bool conditionWaitSocket(
    GIOCondition condition,
    int timeout, [
    GCancellable? cancellable,
  ]) {
    final _error = calloc<ffi.Pointer<ffi.Void>>();
    try {
      final _ret = _gDatagramBasedConditionWait(
        this.handle,
        condition.value,
        timeout,
        cancellable?.handle ?? ffi.nullptr,
        _error,
      );
      if (_error.value != ffi.nullptr) {
        throw GlibException.fromError(_error.value);
      }
      return (_ret) != 0;
    } finally {
      calloc.free(_error);
    }
  }

  /// Creates a #GSource that can be attached to a #GMainContext to monitor for
  /// the availability of the specified @condition on the #GDatagramBased. The
  /// #GSource keeps a reference to the @datagram_based.
  ///
  /// The callback on the source is of the #GDatagramBasedSourceFunc type.
  ///
  /// It is meaningless to specify %G_IO_ERR or %G_IO_HUP in @condition; these
  /// conditions will always be reported in the callback if they are true.
  ///
  /// If non-%NULL, @cancellable can be used to cancel the source, which will
  /// cause the source to trigger, reporting the current condition (which is
  /// likely 0 unless cancellation happened at the same time as a condition
  /// change). You can check for this in the callback using
  /// g_cancellable_is_cancelled().
  static final _gDatagramBasedCreateSource =
      gioLookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(
                ffi.Pointer<ffi.Void>,
                ffi.Uint32,
                ffi.Pointer<ffi.Void>,
              )
            >
          >('g_datagram_based_create_source')
          .asFunction<
            ffi.Pointer<ffi.Void> Function(
              ffi.Pointer<ffi.Void>,
              int,
              ffi.Pointer<ffi.Void>,
            )
          >();
  GSource createSource(GIOCondition condition, [GCancellable? cancellable]) {
    return GSource.fromPointer(
      _gDatagramBasedCreateSource(
        this.handle,
        condition.value,
        cancellable?.handle ?? ffi.nullptr,
      ),
    );
  }

  /// Initializes the object implementing the interface.
  ///
  /// This method is intended for language bindings. If writing in C,
  /// g_initable_new() should typically be used instead.
  ///
  /// The object must be initialized before any real use after initial
  /// construction, either with this function or g_async_initable_init_async().
  ///
  /// Implementations may also support cancellation. If @cancellable is not %NULL,
  /// then initialization can be cancelled by triggering the cancellable object
  /// from another thread. If the operation was cancelled, the error
  /// %G_IO_ERROR_CANCELLED will be returned. If @cancellable is not %NULL and
  /// the object doesn't support cancellable initialization the error
  /// %G_IO_ERROR_NOT_SUPPORTED will be returned.
  ///
  /// If the object is not initialized, or initialization returns with an
  /// error, then all operations on the object except g_object_ref() and
  /// g_object_unref() are considered to be invalid, and have undefined
  /// behaviour. See the [description][iface@Gio.Initable#description] for more details.
  ///
  /// Callers should not assume that a class which implements #GInitable can be
  /// initialized multiple times, unless the class explicitly documents itself as
  /// supporting this. Generally, a class’ implementation of init() can assume
  /// (and assert) that it will only be called once. Previously, this documentation
  /// recommended all #GInitable implementations should be idempotent; that
  /// recommendation was relaxed in GLib 2.54.
  ///
  /// If a class explicitly supports being initialized multiple times, it is
  /// recommended that the method is idempotent: multiple calls with the same
  /// arguments should return the same results. Only the first call initializes
  /// the object; further calls return the result of the first call.
  ///
  /// One reason why a class might need to support idempotent initialization is if
  /// it is designed to be used via the singleton pattern, with a
  /// #GObjectClass.constructor that sometimes returns an existing instance.
  /// In this pattern, a caller would expect to be able to call g_initable_init()
  /// on the result of g_object_new(), regardless of whether it is in fact a new
  /// instance.
  static final _gInitableInit =
      gioLookup<
            ffi.NativeFunction<
              ffi.Int32 Function(
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Pointer<ffi.Void>>,
              )
            >
          >('g_initable_init')
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Pointer<ffi.Void>>,
            )
          >();
  bool init([GCancellable? cancellable]) {
    final _error = calloc<ffi.Pointer<ffi.Void>>();
    try {
      final _ret = _gInitableInit(
        this.handle,
        cancellable?.handle ?? ffi.nullptr,
        _error,
      );
      if (_error.value != ffi.nullptr) {
        throw GlibException.fromError(_error.value);
      }
      return (_ret) != 0;
    } finally {
      calloc.free(_error);
    }
  }

  /// PyGObject-style typed property accessor. Reads and
  /// writes via the existing `get<Name>` / `set<Name>`
  /// methods; each property here corresponds to a GIR
  /// `<property>` element on this class (or one of its
  /// ancestors). See [GSocketProps] for the typed
  /// accessor pair per property.
  late final GSocketProps _props = GSocketProps(this);
  GSocketProps get props => _props;
}
