// Generated by gir_generator. Do not edit.
part of '../gio.dart';

/// Data input stream implements [class@Gio.InputStream] and includes functions
/// for reading structured data directly from a binary input stream.
class GDataInputStream extends GBufferedInputStream {
  GDataInputStream.fromPointer(super.handle, {super.owned})
    : super.fromPointer();

  /// Creates a new data input stream for the @base_stream.
  static final _gDataInputStreamNew =
      gioLookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)
            >
          >('g_data_input_stream_new')
          .asFunction<ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)>();
  factory GDataInputStream(GInputStream baseStream) {
    return GDataInputStream.fromPointer(
      _gDataInputStreamNew(baseStream.handle),
      owned: true,
    );
  }

  /// Gets the byte order for the data input stream.
  static final _gDataInputStreamGetByteOrder =
      gioLookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Void>)>>(
        'g_data_input_stream_get_byte_order',
      ).asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  GDataStreamByteOrder getByteOrder() {
    return GDataStreamByteOrder.fromValue(
      _gDataInputStreamGetByteOrder(this.handle),
    );
  }

  /// Gets the current newline type for the @stream.
  static final _gDataInputStreamGetNewlineType =
      gioLookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Void>)>>(
        'g_data_input_stream_get_newline_type',
      ).asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  GDataStreamNewlineType getNewlineType() {
    return GDataStreamNewlineType.fromValue(
      _gDataInputStreamGetNewlineType(this.handle),
    );
  }

  /// Reads an unsigned 8-bit/1-byte value from @stream.
  static final _gDataInputStreamReadByte =
      gioLookup<
            ffi.NativeFunction<
              ffi.Uint8 Function(
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Pointer<ffi.Void>>,
              )
            >
          >('g_data_input_stream_read_byte')
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Pointer<ffi.Void>>,
            )
          >();
  int readByteDataInputStream([GCancellable? cancellable]) {
    final _error = calloc<ffi.Pointer<ffi.Void>>();
    try {
      final _ret = _gDataInputStreamReadByte(
        this.handle,
        cancellable?.handle ?? ffi.nullptr,
        _error,
      );
      if (_error.value != ffi.nullptr) {
        throw GlibException.fromError(_error.value);
      }
      return _ret;
    } finally {
      calloc.free(_error);
    }
  }

  /// Reads a 16-bit/2-byte value from @stream.
  ///
  /// In order to get the correct byte order for this read operation,
  /// see g_data_input_stream_get_byte_order() and g_data_input_stream_set_byte_order().
  static final _gDataInputStreamReadInt16 =
      gioLookup<
            ffi.NativeFunction<
              ffi.Int16 Function(
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Pointer<ffi.Void>>,
              )
            >
          >('g_data_input_stream_read_int16')
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Pointer<ffi.Void>>,
            )
          >();
  int readInt16([GCancellable? cancellable]) {
    final _error = calloc<ffi.Pointer<ffi.Void>>();
    try {
      final _ret = _gDataInputStreamReadInt16(
        this.handle,
        cancellable?.handle ?? ffi.nullptr,
        _error,
      );
      if (_error.value != ffi.nullptr) {
        throw GlibException.fromError(_error.value);
      }
      return _ret;
    } finally {
      calloc.free(_error);
    }
  }

  /// Reads a signed 32-bit/4-byte value from @stream.
  ///
  /// In order to get the correct byte order for this read operation,
  /// see g_data_input_stream_get_byte_order() and g_data_input_stream_set_byte_order().
  ///
  /// If @cancellable is not %NULL, then the operation can be cancelled by
  /// triggering the cancellable object from another thread. If the operation
  /// was cancelled, the error %G_IO_ERROR_CANCELLED will be returned.
  static final _gDataInputStreamReadInt32 =
      gioLookup<
            ffi.NativeFunction<
              ffi.Int32 Function(
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Pointer<ffi.Void>>,
              )
            >
          >('g_data_input_stream_read_int32')
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Pointer<ffi.Void>>,
            )
          >();
  int readInt32([GCancellable? cancellable]) {
    final _error = calloc<ffi.Pointer<ffi.Void>>();
    try {
      final _ret = _gDataInputStreamReadInt32(
        this.handle,
        cancellable?.handle ?? ffi.nullptr,
        _error,
      );
      if (_error.value != ffi.nullptr) {
        throw GlibException.fromError(_error.value);
      }
      return _ret;
    } finally {
      calloc.free(_error);
    }
  }

  /// Reads a 64-bit/8-byte value from @stream.
  ///
  /// In order to get the correct byte order for this read operation,
  /// see g_data_input_stream_get_byte_order() and g_data_input_stream_set_byte_order().
  ///
  /// If @cancellable is not %NULL, then the operation can be cancelled by
  /// triggering the cancellable object from another thread. If the operation
  /// was cancelled, the error %G_IO_ERROR_CANCELLED will be returned.
  static final _gDataInputStreamReadInt64 =
      gioLookup<
            ffi.NativeFunction<
              ffi.Int64 Function(
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Pointer<ffi.Void>>,
              )
            >
          >('g_data_input_stream_read_int64')
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Pointer<ffi.Void>>,
            )
          >();
  int readInt64([GCancellable? cancellable]) {
    final _error = calloc<ffi.Pointer<ffi.Void>>();
    try {
      final _ret = _gDataInputStreamReadInt64(
        this.handle,
        cancellable?.handle ?? ffi.nullptr,
        _error,
      );
      if (_error.value != ffi.nullptr) {
        throw GlibException.fromError(_error.value);
      }
      return _ret;
    } finally {
      calloc.free(_error);
    }
  }

  /// Reads an unsigned 16-bit/2-byte value from @stream.
  ///
  /// In order to get the correct byte order for this read operation,
  /// see g_data_input_stream_get_byte_order() and g_data_input_stream_set_byte_order().
  static final _gDataInputStreamReadUint16 =
      gioLookup<
            ffi.NativeFunction<
              ffi.Uint16 Function(
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Pointer<ffi.Void>>,
              )
            >
          >('g_data_input_stream_read_uint16')
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Pointer<ffi.Void>>,
            )
          >();
  int readUint16([GCancellable? cancellable]) {
    final _error = calloc<ffi.Pointer<ffi.Void>>();
    try {
      final _ret = _gDataInputStreamReadUint16(
        this.handle,
        cancellable?.handle ?? ffi.nullptr,
        _error,
      );
      if (_error.value != ffi.nullptr) {
        throw GlibException.fromError(_error.value);
      }
      return _ret;
    } finally {
      calloc.free(_error);
    }
  }

  /// Reads an unsigned 32-bit/4-byte value from @stream.
  ///
  /// In order to get the correct byte order for this read operation,
  /// see g_data_input_stream_get_byte_order() and g_data_input_stream_set_byte_order().
  ///
  /// If @cancellable is not %NULL, then the operation can be cancelled by
  /// triggering the cancellable object from another thread. If the operation
  /// was cancelled, the error %G_IO_ERROR_CANCELLED will be returned.
  static final _gDataInputStreamReadUint32 =
      gioLookup<
            ffi.NativeFunction<
              ffi.Uint32 Function(
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Pointer<ffi.Void>>,
              )
            >
          >('g_data_input_stream_read_uint32')
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Pointer<ffi.Void>>,
            )
          >();
  int readUint32([GCancellable? cancellable]) {
    final _error = calloc<ffi.Pointer<ffi.Void>>();
    try {
      final _ret = _gDataInputStreamReadUint32(
        this.handle,
        cancellable?.handle ?? ffi.nullptr,
        _error,
      );
      if (_error.value != ffi.nullptr) {
        throw GlibException.fromError(_error.value);
      }
      return _ret;
    } finally {
      calloc.free(_error);
    }
  }

  /// Reads an unsigned 64-bit/8-byte value from @stream.
  ///
  /// In order to get the correct byte order for this read operation,
  /// see g_data_input_stream_get_byte_order().
  ///
  /// If @cancellable is not %NULL, then the operation can be cancelled by
  /// triggering the cancellable object from another thread. If the operation
  /// was cancelled, the error %G_IO_ERROR_CANCELLED will be returned.
  static final _gDataInputStreamReadUint64 =
      gioLookup<
            ffi.NativeFunction<
              ffi.Uint64 Function(
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Pointer<ffi.Void>>,
              )
            >
          >('g_data_input_stream_read_uint64')
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Pointer<ffi.Void>>,
            )
          >();
  int readUint64([GCancellable? cancellable]) {
    final _error = calloc<ffi.Pointer<ffi.Void>>();
    try {
      final _ret = _gDataInputStreamReadUint64(
        this.handle,
        cancellable?.handle ?? ffi.nullptr,
        _error,
      );
      if (_error.value != ffi.nullptr) {
        throw GlibException.fromError(_error.value);
      }
      return _ret;
    } finally {
      calloc.free(_error);
    }
  }

  /// This function sets the byte order for the given @stream. All subsequent
  /// reads from the @stream will be read in the given @order.
  static final _gDataInputStreamSetByteOrder =
      gioLookup<
            ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Int32)
            >
          >('g_data_input_stream_set_byte_order')
          .asFunction<void Function(ffi.Pointer<ffi.Void>, int)>();
  void setByteOrder(GDataStreamByteOrder order) {
    _gDataInputStreamSetByteOrder(this.handle, order.value);
  }

  /// Sets the newline type for the @stream.
  ///
  /// Note that using G_DATA_STREAM_NEWLINE_TYPE_ANY is slightly unsafe. If a read
  /// chunk ends in "CR" we must read an additional byte to know if this is "CR" or
  /// "CR LF", and this might block if there is no more data available.
  static final _gDataInputStreamSetNewlineType =
      gioLookup<
            ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Int32)
            >
          >('g_data_input_stream_set_newline_type')
          .asFunction<void Function(ffi.Pointer<ffi.Void>, int)>();
  void setNewlineType(GDataStreamNewlineType type_) {
    _gDataInputStreamSetNewlineType(this.handle, type_.value);
  }
}

/// Data output stream implements [class@Gio.OutputStream] and includes functions
/// for writing data directly to an output stream.
class GDataOutputStream extends GFilterOutputStream {
  GDataOutputStream.fromPointer(super.handle, {super.owned})
    : super.fromPointer();

  /// Creates a new data output stream for @base_stream.
  static final _gDataOutputStreamNew =
      gioLookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)
            >
          >('g_data_output_stream_new')
          .asFunction<ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)>();
  factory GDataOutputStream(GOutputStream baseStream) {
    return GDataOutputStream.fromPointer(
      _gDataOutputStreamNew(baseStream.handle),
      owned: true,
    );
  }

  /// Gets the byte order for the stream.
  static final _gDataOutputStreamGetByteOrder =
      gioLookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Void>)>>(
        'g_data_output_stream_get_byte_order',
      ).asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  GDataStreamByteOrder getByteOrder() {
    return GDataStreamByteOrder.fromValue(
      _gDataOutputStreamGetByteOrder(this.handle),
    );
  }

  /// Puts a byte into the output stream.
  static final _gDataOutputStreamPutByte =
      gioLookup<
            ffi.NativeFunction<
              ffi.Int32 Function(
                ffi.Pointer<ffi.Void>,
                ffi.Uint8,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Pointer<ffi.Void>>,
              )
            >
          >('g_data_output_stream_put_byte')
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              int,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Pointer<ffi.Void>>,
            )
          >();
  bool putByte(int data, [GCancellable? cancellable]) {
    final _error = calloc<ffi.Pointer<ffi.Void>>();
    try {
      final _ret = _gDataOutputStreamPutByte(
        this.handle,
        data,
        cancellable?.handle ?? ffi.nullptr,
        _error,
      );
      if (_error.value != ffi.nullptr) {
        throw GlibException.fromError(_error.value);
      }
      return (_ret) != 0;
    } finally {
      calloc.free(_error);
    }
  }

  /// Puts a signed 16-bit integer into the output stream.
  static final _gDataOutputStreamPutInt16 =
      gioLookup<
            ffi.NativeFunction<
              ffi.Int32 Function(
                ffi.Pointer<ffi.Void>,
                ffi.Int16,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Pointer<ffi.Void>>,
              )
            >
          >('g_data_output_stream_put_int16')
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              int,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Pointer<ffi.Void>>,
            )
          >();
  bool putInt16(int data, [GCancellable? cancellable]) {
    final _error = calloc<ffi.Pointer<ffi.Void>>();
    try {
      final _ret = _gDataOutputStreamPutInt16(
        this.handle,
        data,
        cancellable?.handle ?? ffi.nullptr,
        _error,
      );
      if (_error.value != ffi.nullptr) {
        throw GlibException.fromError(_error.value);
      }
      return (_ret) != 0;
    } finally {
      calloc.free(_error);
    }
  }

  /// Puts a signed 32-bit integer into the output stream.
  static final _gDataOutputStreamPutInt32 =
      gioLookup<
            ffi.NativeFunction<
              ffi.Int32 Function(
                ffi.Pointer<ffi.Void>,
                ffi.Int32,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Pointer<ffi.Void>>,
              )
            >
          >('g_data_output_stream_put_int32')
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              int,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Pointer<ffi.Void>>,
            )
          >();
  bool putInt32(int data, [GCancellable? cancellable]) {
    final _error = calloc<ffi.Pointer<ffi.Void>>();
    try {
      final _ret = _gDataOutputStreamPutInt32(
        this.handle,
        data,
        cancellable?.handle ?? ffi.nullptr,
        _error,
      );
      if (_error.value != ffi.nullptr) {
        throw GlibException.fromError(_error.value);
      }
      return (_ret) != 0;
    } finally {
      calloc.free(_error);
    }
  }

  /// Puts a signed 64-bit integer into the stream.
  static final _gDataOutputStreamPutInt64 =
      gioLookup<
            ffi.NativeFunction<
              ffi.Int32 Function(
                ffi.Pointer<ffi.Void>,
                ffi.Int64,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Pointer<ffi.Void>>,
              )
            >
          >('g_data_output_stream_put_int64')
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              int,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Pointer<ffi.Void>>,
            )
          >();
  bool putInt64(int data, [GCancellable? cancellable]) {
    final _error = calloc<ffi.Pointer<ffi.Void>>();
    try {
      final _ret = _gDataOutputStreamPutInt64(
        this.handle,
        data,
        cancellable?.handle ?? ffi.nullptr,
        _error,
      );
      if (_error.value != ffi.nullptr) {
        throw GlibException.fromError(_error.value);
      }
      return (_ret) != 0;
    } finally {
      calloc.free(_error);
    }
  }

  /// Puts a string into the output stream.
  static final _gDataOutputStreamPutString =
      gioLookup<
            ffi.NativeFunction<
              ffi.Int32 Function(
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<Utf8>,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Pointer<ffi.Void>>,
              )
            >
          >('g_data_output_stream_put_string')
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<Utf8>,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Pointer<ffi.Void>>,
            )
          >();
  bool putString(String str, [GCancellable? cancellable]) {
    return withNativeString(str, (nativeStr) {
      final _error = calloc<ffi.Pointer<ffi.Void>>();
      try {
        final _ret = _gDataOutputStreamPutString(
          this.handle,
          nativeStr.cast<Utf8>(),
          cancellable?.handle ?? ffi.nullptr,
          _error,
        );
        if (_error.value != ffi.nullptr) {
          throw GlibException.fromError(_error.value);
        }
        return (_ret) != 0;
      } finally {
        calloc.free(_error);
      }
    });
  }

  /// Puts an unsigned 16-bit integer into the output stream.
  static final _gDataOutputStreamPutUint16 =
      gioLookup<
            ffi.NativeFunction<
              ffi.Int32 Function(
                ffi.Pointer<ffi.Void>,
                ffi.Uint16,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Pointer<ffi.Void>>,
              )
            >
          >('g_data_output_stream_put_uint16')
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              int,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Pointer<ffi.Void>>,
            )
          >();
  bool putUint16(int data, [GCancellable? cancellable]) {
    final _error = calloc<ffi.Pointer<ffi.Void>>();
    try {
      final _ret = _gDataOutputStreamPutUint16(
        this.handle,
        data,
        cancellable?.handle ?? ffi.nullptr,
        _error,
      );
      if (_error.value != ffi.nullptr) {
        throw GlibException.fromError(_error.value);
      }
      return (_ret) != 0;
    } finally {
      calloc.free(_error);
    }
  }

  /// Puts an unsigned 32-bit integer into the stream.
  static final _gDataOutputStreamPutUint32 =
      gioLookup<
            ffi.NativeFunction<
              ffi.Int32 Function(
                ffi.Pointer<ffi.Void>,
                ffi.Uint32,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Pointer<ffi.Void>>,
              )
            >
          >('g_data_output_stream_put_uint32')
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              int,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Pointer<ffi.Void>>,
            )
          >();
  bool putUint32(int data, [GCancellable? cancellable]) {
    final _error = calloc<ffi.Pointer<ffi.Void>>();
    try {
      final _ret = _gDataOutputStreamPutUint32(
        this.handle,
        data,
        cancellable?.handle ?? ffi.nullptr,
        _error,
      );
      if (_error.value != ffi.nullptr) {
        throw GlibException.fromError(_error.value);
      }
      return (_ret) != 0;
    } finally {
      calloc.free(_error);
    }
  }

  /// Puts an unsigned 64-bit integer into the stream.
  static final _gDataOutputStreamPutUint64 =
      gioLookup<
            ffi.NativeFunction<
              ffi.Int32 Function(
                ffi.Pointer<ffi.Void>,
                ffi.Uint64,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Pointer<ffi.Void>>,
              )
            >
          >('g_data_output_stream_put_uint64')
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              int,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Pointer<ffi.Void>>,
            )
          >();
  bool putUint64(int data, [GCancellable? cancellable]) {
    final _error = calloc<ffi.Pointer<ffi.Void>>();
    try {
      final _ret = _gDataOutputStreamPutUint64(
        this.handle,
        data,
        cancellable?.handle ?? ffi.nullptr,
        _error,
      );
      if (_error.value != ffi.nullptr) {
        throw GlibException.fromError(_error.value);
      }
      return (_ret) != 0;
    } finally {
      calloc.free(_error);
    }
  }

  /// Sets the byte order of the data output stream to @order.
  static final _gDataOutputStreamSetByteOrder =
      gioLookup<
            ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Int32)
            >
          >('g_data_output_stream_set_byte_order')
          .asFunction<void Function(ffi.Pointer<ffi.Void>, int)>();
  void setByteOrder(GDataStreamByteOrder order) {
    _gDataOutputStreamSetByteOrder(this.handle, order.value);
  }
}
