// Generated by gir_generator. Do not edit.
part of '../gio.dart';

/// PyGObject-style typed property accessor. Each getter
/// and setter delegates to the existing typed
/// `get<Name>` / `set<Name>` methods on [GDataOutputStream].
///
/// Skipped properties (unsupported type, missing getter
/// or setter) are recorded in the generation report.
class GDataOutputStreamProps extends GFilterOutputStreamProps {
  GDataOutputStreamProps(GDataOutputStream $self) : _self = $self, super($self);
  final GDataOutputStream _self;

  GDataStreamByteOrder get byteOrder => _self.getByteOrder();
  set byteOrder(GDataStreamByteOrder value) {
    _self.setByteOrder(value);
  }

  GOutputStream get baseStream => _self.getBaseStream();

  bool get closeBaseStream => _self.getCloseBaseStream();
}
