// Generated by gir_generator. Do not edit.
part of '../gio.dart';

/// Loaded native libraries for the Gio namespace.
final gioLibs = _openLibs();

List<ffi.DynamicLibrary> _openLibs() {
  final libs = <ffi.DynamicLibrary>[];
  for (final name in const ['libgio-2.0.so.0']) {
    try {
      libs.add(ffi.DynamicLibrary.open(name));
    } on ArgumentError {
      // Library not present; try the next one.
    }
  }
  if (libs.isEmpty) {
    libs.add(ffi.DynamicLibrary.process());
  }
  return libs;
}

/// Looks up [symbol] in each of the Gio libraries.
ffi.Pointer<T> gioLookup<T extends ffi.NativeType>(String symbol) {
  for (final lib in gioLibs) {
    try {
      return lib.lookup<T>(symbol);
    } on ArgumentError {
      // Symbol lives in another library of this package.
    }
  }
  return ffi.DynamicLibrary.process().lookup<T>(symbol);
}
