// Generated by gir_generator. Do not edit.
part of '../gio.dart';

/// Information about an installed application and methods to launch
/// it (with file arguments).
///
/// `GAppInfo` and `GAppLaunchContext` are used for describing and launching
/// applications installed on the system.
///
/// As of GLib 2.20, URIs will always be converted to POSIX paths
/// (using [method@Gio.File.get_path]) when using [method@Gio.AppInfo.launch]
/// even if the application requested an URI and not a POSIX path. For example
/// for a desktop-file based application with the following Exec key:
///
/// ```
/// Exec=totem %U
/// ```
///
/// and a single URI, `sftp://foo/file.avi`, then
/// `/home/user/.gvfs/sftp on foo/file.avi` will be passed. This will only work
/// if a set of suitable GIO extensions (such as GVfs 2.26 compiled with FUSE
/// support), is available and operational; if this is not the case, the URI
/// will be passed unmodified to the application. Some URIs, such as `mailto:`,
/// of course cannot be mapped to a POSIX path (in GVfs there’s no FUSE mount
/// for it); such URIs will be passed unmodified to the application.
///
/// Specifically for GVfs 2.26 and later, the POSIX URI will be mapped
/// back to the GIO URI in the [iface@Gio.File] constructors (since GVfs
/// implements the GVfs extension point). As such, if the application
/// needs to examine the URI, it needs to use [method@Gio.File.get_uri]
/// or similar on [iface@Gio.File]. In other words, an application cannot
/// assume that the URI passed to e.g. [func@Gio.File.new_for_commandline_arg]
/// is equal to the result of [method@Gio.File.get_uri]. The following snippet
/// illustrates this:
///
/// ```c
/// GFile *f;
/// char *uri;
///
/// file = g_file_new_for_commandline_arg (uri_from_commandline);
///
/// uri = g_file_get_uri (file);
/// strcmp (uri, uri_from_commandline) == 0;
/// g_free (uri);
///
/// if (g_file_has_uri_scheme (file, "cdda"))
/// {
/// // do something special with uri
/// }
/// g_object_unref (file);
/// ```
///
/// This code will work when both `cdda://sr0/Track 1.wav` and
/// `/home/user/.gvfs/cdda on sr0/Track 1.wav` is passed to the
/// application. It should be noted that it’s generally not safe
/// for applications to rely on the format of a particular URIs.
/// Different launcher applications (e.g. file managers) may have
/// different ideas of what a given URI means.
final class GAppInfo {
  GAppInfo.fromPointer(this.handle);
  final ffi.Pointer<ffi.Void> handle;

  /// Adds a content type to the application information to indicate the
  /// application is capable of opening files with the given content type.
  static final _gAppInfoAddSupportsType =
      gioLookup<
            ffi.NativeFunction<
              ffi.Int32 Function(
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<Utf8>,
                ffi.Pointer<ffi.Pointer<ffi.Void>>,
              )
            >
          >('g_app_info_add_supports_type')
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<Utf8>,
              ffi.Pointer<ffi.Pointer<ffi.Void>>,
            )
          >();
  bool addSupportsType(String contentType) {
    return withNativeString(contentType, (nativeContentType) {
      final _error = calloc<ffi.Pointer<ffi.Void>>();
      try {
        final _ret = _gAppInfoAddSupportsType(
          this.handle,
          nativeContentType.cast<Utf8>(),
          _error,
        );
        if (_error.value != ffi.nullptr) {
          throw GlibException.fromError(_error.value);
        }
        return (_ret) != 0;
      } finally {
        calloc.free(_error);
      }
    });
  }

  /// Obtains the information whether the [iface@Gio.AppInfo] can be deleted.
  /// See [method@Gio.AppInfo.delete].
  static final _gAppInfoCanDelete =
      gioLookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Void>)>>(
        'g_app_info_can_delete',
      ).asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  bool canDelete() {
    return (_gAppInfoCanDelete(this.handle)) != 0;
  }

  /// Checks if a supported content type can be removed from an application.
  static final _gAppInfoCanRemoveSupportsType =
      gioLookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Void>)>>(
        'g_app_info_can_remove_supports_type',
      ).asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  bool canRemoveSupportsType() {
    return (_gAppInfoCanRemoveSupportsType(this.handle)) != 0;
  }

  /// Tries to delete a [iface@Gio.AppInfo].
  ///
  /// On some platforms, there may be a difference between user-defined
  /// [iface@Gio.AppInfo]s which can be deleted, and system-wide ones which cannot.
  /// See [method@Gio.AppInfo.can_delete].
  static final _gAppInfoDelete =
      gioLookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Void>)>>(
        'g_app_info_delete',
      ).asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  bool delete() {
    return (_gAppInfoDelete(this.handle)) != 0;
  }

  /// Creates a duplicate of a [iface@Gio.AppInfo].
  static final _gAppInfoDup =
      gioLookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)
            >
          >('g_app_info_dup')
          .asFunction<ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)>();
  GAppInfo dup() {
    return GAppInfo.fromPointer(_gAppInfoDup(this.handle));
  }

  /// Checks if two [iface@Gio.AppInfo]s are equal.
  ///
  /// Note that the check *may not* compare each individual field, and only does
  /// an identity check. In case detecting changes in the contents is needed,
  /// program code must additionally compare relevant fields.
  static final _gAppInfoEqual =
      gioLookup<
            ffi.NativeFunction<
              ffi.Int32 Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)
            >
          >('g_app_info_equal')
          .asFunction<
            int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)
          >();
  bool equal(GAppInfo appinfo2) {
    return (_gAppInfoEqual(this.handle, appinfo2.handle)) != 0;
  }

  /// Gets the commandline with which the application will be
  /// started.
  static final _gAppInfoGetCommandline =
      gioLookup<
            ffi.NativeFunction<
              ffi.Pointer<Utf8> Function(ffi.Pointer<ffi.Void>)
            >
          >('g_app_info_get_commandline')
          .asFunction<ffi.Pointer<Utf8> Function(ffi.Pointer<ffi.Void>)>();
  String? getCommandline() {
    return stringFromNative(
      (_gAppInfoGetCommandline(this.handle)).cast(),
      free: false,
    );
  }

  /// Gets a human-readable description of an installed application.
  static final _gAppInfoGetDescription =
      gioLookup<
            ffi.NativeFunction<
              ffi.Pointer<Utf8> Function(ffi.Pointer<ffi.Void>)
            >
          >('g_app_info_get_description')
          .asFunction<ffi.Pointer<Utf8> Function(ffi.Pointer<ffi.Void>)>();
  String? getDescription() {
    return stringFromNative(
      (_gAppInfoGetDescription(this.handle)).cast(),
      free: false,
    );
  }

  /// Gets the display name of the application. The display name is often more
  /// descriptive to the user than the name itself.
  static final _gAppInfoGetDisplayName =
      gioLookup<
            ffi.NativeFunction<
              ffi.Pointer<Utf8> Function(ffi.Pointer<ffi.Void>)
            >
          >('g_app_info_get_display_name')
          .asFunction<ffi.Pointer<Utf8> Function(ffi.Pointer<ffi.Void>)>();
  String getDisplayName() {
    return stringFromNative(
      (_gAppInfoGetDisplayName(this.handle)).cast(),
      free: false,
    )!;
  }

  /// Gets the executable’s name for the installed application.
  ///
  /// This is intended to be used for debugging or labelling what program is going
  /// to be run. To launch the executable, use [method@Gio.AppInfo.launch] and related
  /// functions, rather than spawning the return value from this function.
  static final _gAppInfoGetExecutable =
      gioLookup<
            ffi.NativeFunction<
              ffi.Pointer<Utf8> Function(ffi.Pointer<ffi.Void>)
            >
          >('g_app_info_get_executable')
          .asFunction<ffi.Pointer<Utf8> Function(ffi.Pointer<ffi.Void>)>();
  String getExecutable() {
    return stringFromNative(
      (_gAppInfoGetExecutable(this.handle)).cast(),
      free: false,
    )!;
  }

  /// Gets the icon for the application.
  static final _gAppInfoGetIcon =
      gioLookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)
            >
          >('g_app_info_get_icon')
          .asFunction<ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)>();
  GIcon? getIcon() {
    return (_gAppInfoGetIcon(this.handle)) == ffi.nullptr
        ? null
        : GIcon.fromPointer(_gAppInfoGetIcon(this.handle));
  }

  /// Gets the ID of an application. An id is a string that identifies the
  /// application. The exact format of the id is platform dependent. For instance,
  /// on Unix this is the desktop file id from the xdg menu specification.
  ///
  /// Note that the returned ID may be `NULL`, depending on how the @appinfo has
  /// been constructed.
  static final _gAppInfoGetId =
      gioLookup<
            ffi.NativeFunction<
              ffi.Pointer<Utf8> Function(ffi.Pointer<ffi.Void>)
            >
          >('g_app_info_get_id')
          .asFunction<ffi.Pointer<Utf8> Function(ffi.Pointer<ffi.Void>)>();
  String? getId() {
    return stringFromNative((_gAppInfoGetId(this.handle)).cast(), free: false);
  }

  /// Gets the installed name of the application.
  static final _gAppInfoGetName =
      gioLookup<
            ffi.NativeFunction<
              ffi.Pointer<Utf8> Function(ffi.Pointer<ffi.Void>)
            >
          >('g_app_info_get_name')
          .asFunction<ffi.Pointer<Utf8> Function(ffi.Pointer<ffi.Void>)>();
  String getName() {
    return stringFromNative(
      (_gAppInfoGetName(this.handle)).cast(),
      free: false,
    )!;
  }

  /// Launches the application. Passes @files to the launched application
  /// as arguments, using the optional @context to get information
  /// about the details of the launcher (like what screen it is on).
  /// On error, @error will be set accordingly.
  ///
  /// To launch the application without arguments pass a `NULL` @files list.
  ///
  /// Note that even if the launch is successful the application launched
  /// can fail to start if it runs into problems during startup. There is
  /// no way to detect this.
  ///
  /// Some URIs can be changed when passed through a GFile (for instance
  /// unsupported URIs with strange formats like mailto:), so if you have
  /// a textual URI you want to pass in as argument, consider using
  /// [method@Gio.AppInfo.launch_uris] instead.
  ///
  /// The launched application inherits the environment of the launching
  /// process, but it can be modified with [method@Gio.AppLaunchContext.setenv]
  /// and [method@Gio.AppLaunchContext.unsetenv].
  ///
  /// On UNIX, this function sets the `GIO_LAUNCHED_DESKTOP_FILE`
  /// environment variable with the path of the launched desktop file and
  /// `GIO_LAUNCHED_DESKTOP_FILE_PID` to the process id of the launched
  /// process. This can be used to ignore `GIO_LAUNCHED_DESKTOP_FILE`,
  /// should it be inherited by further processes. The `DISPLAY`,
  /// `XDG_ACTIVATION_TOKEN` and `DESKTOP_STARTUP_ID` environment
  /// variables are also set, based on information provided in @context.
  static final _gAppInfoLaunch =
      gioLookup<
            ffi.NativeFunction<
              ffi.Int32 Function(
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Pointer<ffi.Void>>,
              )
            >
          >('g_app_info_launch')
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Pointer<ffi.Void>>,
            )
          >();
  bool launch([GList? files, GAppLaunchContext? context]) {
    final _error = calloc<ffi.Pointer<ffi.Void>>();
    try {
      final _ret = _gAppInfoLaunch(
        this.handle,
        files?.handle ?? ffi.nullptr,
        context?.handle ?? ffi.nullptr,
        _error,
      );
      if (_error.value != ffi.nullptr) {
        throw GlibException.fromError(_error.value);
      }
      return (_ret) != 0;
    } finally {
      calloc.free(_error);
    }
  }

  /// Launches the application. This passes the @uris to the launched application
  /// as arguments, using the optional @context to get information
  /// about the details of the launcher (like what screen it is on).
  /// On error, @error will be set accordingly. If the application only supports
  /// one URI per invocation as part of their command-line, multiple instances
  /// of the application will be spawned.
  ///
  /// To launch the application without arguments pass a `NULL` @uris list.
  ///
  /// Note that even if the launch is successful the application launched
  /// can fail to start if it runs into problems during startup. There is
  /// no way to detect this.
  static final _gAppInfoLaunchUris =
      gioLookup<
            ffi.NativeFunction<
              ffi.Int32 Function(
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Pointer<ffi.Void>>,
              )
            >
          >('g_app_info_launch_uris')
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Pointer<ffi.Void>>,
            )
          >();
  bool launchUris([GList? uris, GAppLaunchContext? context]) {
    final _error = calloc<ffi.Pointer<ffi.Void>>();
    try {
      final _ret = _gAppInfoLaunchUris(
        this.handle,
        uris?.handle ?? ffi.nullptr,
        context?.handle ?? ffi.nullptr,
        _error,
      );
      if (_error.value != ffi.nullptr) {
        throw GlibException.fromError(_error.value);
      }
      return (_ret) != 0;
    } finally {
      calloc.free(_error);
    }
  }

  /// Async version of [method@Gio.AppInfo.launch_uris].
  ///
  /// The @callback is invoked immediately after the application launch, but it
  /// waits for activation in case of D-Bus–activated applications and also provides
  /// extended error information for sandboxed applications, see notes for
  /// [func@Gio.AppInfo.launch_default_for_uri_async].
  static final _gAppInfoLaunchUrisAsync =
      gioLookup<
            ffi.NativeFunction<
              ffi.Void Function(
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<
                  ffi.NativeFunction<
                    ffi.Void Function(
                      ffi.Pointer<ffi.Void>,
                      ffi.Pointer<ffi.Void>,
                      ffi.Pointer<ffi.Void>,
                    )
                  >
                >,
                ffi.Pointer<ffi.Void>,
              )
            >
          >('g_app_info_launch_uris_async')
          .asFunction<
            void Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<
                ffi.NativeFunction<
                  ffi.Void Function(
                    ffi.Pointer<ffi.Void>,
                    ffi.Pointer<ffi.Void>,
                    ffi.Pointer<ffi.Void>,
                  )
                >
              >,
              ffi.Pointer<ffi.Void>,
            )
          >();
  void launchUrisAsync(
    GList? uris,
    GAppLaunchContext? context,
    GCancellable? cancellable,
    void Function(
      ffi.Pointer<ffi.Void>,
      ffi.Pointer<ffi.Void>,
      ffi.Pointer<ffi.Void>,
    )?
    callback,
    ffi.Pointer<ffi.Void> userData,
  ) {
    final _nc4 = callback == null
        ? null
        : ffi.NativeCallable<
            ffi.Void Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Void>,
            )
          >.isolateLocal(callback);
    try {
      _gAppInfoLaunchUrisAsync(
        this.handle,
        uris?.handle ?? ffi.nullptr,
        context?.handle ?? ffi.nullptr,
        cancellable?.handle ?? ffi.nullptr,
        _nc4?.nativeFunction ?? ffi.nullptr,
        userData,
      );
    } finally {
      _nc4?.close();
    }
  }

  static final _launchUrisAsyncCallbackRegistry =
      <int, void Function(GObject?, GAsyncResult)>{};
  static int _launchUrisAsyncCallbackSeq = 0;
  static final _launchUrisAsyncCallbackPtr =
      ffi.Pointer.fromFunction<
        ffi.Void Function(
          ffi.Pointer<ffi.Void>,
          ffi.Pointer<ffi.Void>,
          ffi.Pointer<ffi.Void>,
        )
      >(_launchUrisAsyncCallbackTrampoline);
  static void _launchUrisAsyncCallbackTrampoline(
    ffi.Pointer<ffi.Void> sourceObject,
    ffi.Pointer<ffi.Void> res,
    ffi.Pointer<ffi.Void> data,
  ) {
    final id = data.cast<ffi.IntPtr>().value;
    final fn = _launchUrisAsyncCallbackRegistry.remove(id);
    malloc.free(data);
    if (fn == null) return;
    fn(
      sourceObject == ffi.nullptr
          ? null
          : GObject.fromPointer(sourceObject.cast()),
      GAsyncResult.fromPointer(res.cast()),
    );
  }

  /// Lifetime-safe variant of [launchUrisAsync] for use with
  /// async callbacks. See `docs/async.md`.
  void launchUrisAsyncCallback(
    GList? uris,
    GAppLaunchContext? context,
    GCancellable? cancellable,
    void Function(GObject?, GAsyncResult) callback,
  ) {
    final id = ++_launchUrisAsyncCallbackSeq;
    _launchUrisAsyncCallbackRegistry[id] = callback;
    final _data = malloc<ffi.IntPtr>()..value = id;
    _gAppInfoLaunchUrisAsync(
      this.handle,
      uris?.handle ?? ffi.nullptr,
      context?.handle ?? ffi.nullptr,
      cancellable?.handle ?? ffi.nullptr,
      _launchUrisAsyncCallbackPtr,
      _data.cast<ffi.Void>(),
    );
  }

  /// Finishes a [method@Gio.AppInfo.launch_uris_async] operation.
  static final _gAppInfoLaunchUrisFinish =
      gioLookup<
            ffi.NativeFunction<
              ffi.Int32 Function(
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Pointer<ffi.Void>>,
              )
            >
          >('g_app_info_launch_uris_finish')
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Pointer<ffi.Void>>,
            )
          >();
  bool launchUrisFinish(GAsyncResult result) {
    final _error = calloc<ffi.Pointer<ffi.Void>>();
    try {
      final _ret = _gAppInfoLaunchUrisFinish(
        this.handle,
        result.handle,
        _error,
      );
      if (_error.value != ffi.nullptr) {
        throw GlibException.fromError(_error.value);
      }
      return (_ret) != 0;
    } finally {
      calloc.free(_error);
    }
  }

  /// Removes a supported type from an application, if possible.
  static final _gAppInfoRemoveSupportsType =
      gioLookup<
            ffi.NativeFunction<
              ffi.Int32 Function(
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<Utf8>,
                ffi.Pointer<ffi.Pointer<ffi.Void>>,
              )
            >
          >('g_app_info_remove_supports_type')
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<Utf8>,
              ffi.Pointer<ffi.Pointer<ffi.Void>>,
            )
          >();
  bool removeSupportsType(String contentType) {
    return withNativeString(contentType, (nativeContentType) {
      final _error = calloc<ffi.Pointer<ffi.Void>>();
      try {
        final _ret = _gAppInfoRemoveSupportsType(
          this.handle,
          nativeContentType.cast<Utf8>(),
          _error,
        );
        if (_error.value != ffi.nullptr) {
          throw GlibException.fromError(_error.value);
        }
        return (_ret) != 0;
      } finally {
        calloc.free(_error);
      }
    });
  }

  /// Sets the application as the default handler for the given file extension.
  static final _gAppInfoSetAsDefaultForExtension =
      gioLookup<
            ffi.NativeFunction<
              ffi.Int32 Function(
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<Utf8>,
                ffi.Pointer<ffi.Pointer<ffi.Void>>,
              )
            >
          >('g_app_info_set_as_default_for_extension')
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<Utf8>,
              ffi.Pointer<ffi.Pointer<ffi.Void>>,
            )
          >();
  bool setAsDefaultForExtension(String extension_) {
    return withNativeString(extension_, (nativeExtension_) {
      final _error = calloc<ffi.Pointer<ffi.Void>>();
      try {
        final _ret = _gAppInfoSetAsDefaultForExtension(
          this.handle,
          nativeExtension_.cast<Utf8>(),
          _error,
        );
        if (_error.value != ffi.nullptr) {
          throw GlibException.fromError(_error.value);
        }
        return (_ret) != 0;
      } finally {
        calloc.free(_error);
      }
    });
  }

  /// Sets the application as the default handler for a given type.
  static final _gAppInfoSetAsDefaultForType =
      gioLookup<
            ffi.NativeFunction<
              ffi.Int32 Function(
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<Utf8>,
                ffi.Pointer<ffi.Pointer<ffi.Void>>,
              )
            >
          >('g_app_info_set_as_default_for_type')
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<Utf8>,
              ffi.Pointer<ffi.Pointer<ffi.Void>>,
            )
          >();
  bool setAsDefaultForType(String contentType) {
    return withNativeString(contentType, (nativeContentType) {
      final _error = calloc<ffi.Pointer<ffi.Void>>();
      try {
        final _ret = _gAppInfoSetAsDefaultForType(
          this.handle,
          nativeContentType.cast<Utf8>(),
          _error,
        );
        if (_error.value != ffi.nullptr) {
          throw GlibException.fromError(_error.value);
        }
        return (_ret) != 0;
      } finally {
        calloc.free(_error);
      }
    });
  }

  /// Sets the application as the last used application for a given type. This
  /// will make the application appear as first in the list returned by
  /// [func@Gio.AppInfo.get_recommended_for_type], regardless of the default
  /// application for that content type.
  static final _gAppInfoSetAsLastUsedForType =
      gioLookup<
            ffi.NativeFunction<
              ffi.Int32 Function(
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<Utf8>,
                ffi.Pointer<ffi.Pointer<ffi.Void>>,
              )
            >
          >('g_app_info_set_as_last_used_for_type')
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<Utf8>,
              ffi.Pointer<ffi.Pointer<ffi.Void>>,
            )
          >();
  bool setAsLastUsedForType(String contentType) {
    return withNativeString(contentType, (nativeContentType) {
      final _error = calloc<ffi.Pointer<ffi.Void>>();
      try {
        final _ret = _gAppInfoSetAsLastUsedForType(
          this.handle,
          nativeContentType.cast<Utf8>(),
          _error,
        );
        if (_error.value != ffi.nullptr) {
          throw GlibException.fromError(_error.value);
        }
        return (_ret) != 0;
      } finally {
        calloc.free(_error);
      }
    });
  }

  /// Checks if the application info should be shown in menus that
  /// list available applications.
  static final _gAppInfoShouldShow =
      gioLookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Void>)>>(
        'g_app_info_should_show',
      ).asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  bool shouldShow() {
    return (_gAppInfoShouldShow(this.handle)) != 0;
  }

  /// Checks if the application accepts files as arguments.
  static final _gAppInfoSupportsFiles =
      gioLookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Void>)>>(
        'g_app_info_supports_files',
      ).asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  bool supportsFiles() {
    return (_gAppInfoSupportsFiles(this.handle)) != 0;
  }

  /// Checks if the application supports reading files and directories from URIs.
  static final _gAppInfoSupportsUris =
      gioLookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Void>)>>(
        'g_app_info_supports_uris',
      ).asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  bool supportsUris() {
    return (_gAppInfoSupportsUris(this.handle)) != 0;
  }

  /// Creates a new [iface@Gio.AppInfo] from the given information.
  ///
  /// Note that for @commandline, the quoting rules of the `Exec` key of the
  /// [freedesktop.org Desktop Entry Specification](http://freedesktop.org/Standards/desktop-entry-spec)
  /// are applied. For example, if the @commandline contains
  /// percent-encoded URIs, the percent-character must be doubled in order to prevent it from
  /// being swallowed by `Exec` key unquoting. See
  /// [the specification](https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s07.html)
  /// for exact quoting rules.
  static final _gAppInfoCreateFromCommandline =
      gioLookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(
                ffi.Pointer<Utf8>,
                ffi.Pointer<Utf8>,
                ffi.Uint32,
                ffi.Pointer<ffi.Pointer<ffi.Void>>,
              )
            >
          >('g_app_info_create_from_commandline')
          .asFunction<
            ffi.Pointer<ffi.Void> Function(
              ffi.Pointer<Utf8>,
              ffi.Pointer<Utf8>,
              int,
              ffi.Pointer<ffi.Pointer<ffi.Void>>,
            )
          >();
  static GAppInfo createFromCommandline(
    String commandline,
    String? applicationName,
    GAppInfoCreateFlags flags,
  ) {
    return withNativeString(commandline, (nativeCommandline) {
      return withNativeString(applicationName, (nativeApplicationName) {
        final _error = calloc<ffi.Pointer<ffi.Void>>();
        try {
          final _ret = _gAppInfoCreateFromCommandline(
            nativeCommandline.cast<Utf8>(),
            nativeApplicationName.cast<Utf8>(),
            flags.value,
            _error,
          );
          if (_error.value != ffi.nullptr) {
            throw GlibException.fromError(_error.value);
          }
          return GAppInfo.fromPointer(_ret);
        } finally {
          calloc.free(_error);
        }
      });
    });
  }

  /// Gets a list of all of the applications currently registered
  /// on this system.
  ///
  /// For desktop files, this includes applications that have
  /// [`NoDisplay=true`](https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s06.html#key-nodisplay)
  /// set or are excluded from display by means of
  /// [`OnlyShowIn`](https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s06.html#key-onlyshowin)
  /// or [`NotShowIn`](https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s06.html#key-notshowin).
  /// See [method@Gio.AppInfo.should_show].
  ///
  /// The returned list does not include applications which have the
  /// [`Hidden` key](https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s06.html#key-hidden)
  /// set.
  static final _gAppInfoGetAll =
      gioLookup<ffi.NativeFunction<ffi.Pointer<ffi.Void> Function()>>(
        'g_app_info_get_all',
      ).asFunction<ffi.Pointer<ffi.Void> Function()>();
  static GList getAll() {
    return GList.fromPointer(_gAppInfoGetAll());
  }

  /// Gets a list of all [iface@Gio.AppInfo]s for a given content type,
  /// including the recommended and fallback [iface@Gio.AppInfo]s. See
  /// [func@Gio.AppInfo.get_recommended_for_type] and
  /// [func@Gio.AppInfo.get_fallback_for_type].
  static final _gAppInfoGetAllForType =
      gioLookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(ffi.Pointer<Utf8>)
            >
          >('g_app_info_get_all_for_type')
          .asFunction<ffi.Pointer<ffi.Void> Function(ffi.Pointer<Utf8>)>();
  static GList getAllForType(String contentType) {
    return withNativeString(contentType, (nativeContentType) {
      return GList.fromPointer(
        _gAppInfoGetAllForType(nativeContentType.cast<Utf8>()),
      );
    });
  }

  /// Gets the default [iface@Gio.AppInfo] for a given content type.
  static final _gAppInfoGetDefaultForType =
      gioLookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(ffi.Pointer<Utf8>, ffi.Int32)
            >
          >('g_app_info_get_default_for_type')
          .asFunction<ffi.Pointer<ffi.Void> Function(ffi.Pointer<Utf8>, int)>();
  static GAppInfo? getDefaultForType(String contentType, bool mustSupportUris) {
    return withNativeString(contentType, (nativeContentType) {
      return (_gAppInfoGetDefaultForType(
                nativeContentType.cast<Utf8>(),
                mustSupportUris ? 1 : 0,
              )) ==
              ffi.nullptr
          ? null
          : GAppInfo.fromPointer(
              _gAppInfoGetDefaultForType(
                nativeContentType.cast<Utf8>(),
                mustSupportUris ? 1 : 0,
              ),
            );
    });
  }

  /// Asynchronously gets the default [iface@Gio.AppInfo] for a given content
  /// type.
  static final _gAppInfoGetDefaultForTypeAsync =
      gioLookup<
            ffi.NativeFunction<
              ffi.Void Function(
                ffi.Pointer<Utf8>,
                ffi.Int32,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<
                  ffi.NativeFunction<
                    ffi.Void Function(
                      ffi.Pointer<ffi.Void>,
                      ffi.Pointer<ffi.Void>,
                      ffi.Pointer<ffi.Void>,
                    )
                  >
                >,
                ffi.Pointer<ffi.Void>,
              )
            >
          >('g_app_info_get_default_for_type_async')
          .asFunction<
            void Function(
              ffi.Pointer<Utf8>,
              int,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<
                ffi.NativeFunction<
                  ffi.Void Function(
                    ffi.Pointer<ffi.Void>,
                    ffi.Pointer<ffi.Void>,
                    ffi.Pointer<ffi.Void>,
                  )
                >
              >,
              ffi.Pointer<ffi.Void>,
            )
          >();
  static void getDefaultForTypeAsync(
    String contentType,
    bool mustSupportUris,
    GCancellable? cancellable,
    void Function(
      ffi.Pointer<ffi.Void>,
      ffi.Pointer<ffi.Void>,
      ffi.Pointer<ffi.Void>,
    )?
    callback,
    ffi.Pointer<ffi.Void> userData,
  ) {
    withNativeString(contentType, (nativeContentType) {
      final _nc4 = callback == null
          ? null
          : ffi.NativeCallable<
              ffi.Void Function(
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Void>,
              )
            >.isolateLocal(callback);
      try {
        _gAppInfoGetDefaultForTypeAsync(
          nativeContentType.cast<Utf8>(),
          mustSupportUris ? 1 : 0,
          cancellable?.handle ?? ffi.nullptr,
          _nc4?.nativeFunction ?? ffi.nullptr,
          userData,
        );
      } finally {
        _nc4?.close();
      }
    });
  }

  /// Finishes a default [iface@Gio.AppInfo] lookup started by
  /// [func@Gio.AppInfo.get_default_for_type_async].
  ///
  /// If no #[iface@Gio.AppInfo] is found, then @error will be set to
  /// [error@Gio.IOErrorEnum.NOT_FOUND].
  static final _gAppInfoGetDefaultForTypeFinish =
      gioLookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Pointer<ffi.Void>>,
              )
            >
          >('g_app_info_get_default_for_type_finish')
          .asFunction<
            ffi.Pointer<ffi.Void> Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Pointer<ffi.Void>>,
            )
          >();
  static GAppInfo getDefaultForTypeFinish(GAsyncResult result) {
    final _error = calloc<ffi.Pointer<ffi.Void>>();
    try {
      final _ret = _gAppInfoGetDefaultForTypeFinish(result.handle, _error);
      if (_error.value != ffi.nullptr) {
        throw GlibException.fromError(_error.value);
      }
      return GAppInfo.fromPointer(_ret);
    } finally {
      calloc.free(_error);
    }
  }

  /// Gets the default application for handling URIs with the given URI scheme.
  ///
  /// A URI scheme is the initial part of the URI, up to but not including the `:`.
  /// For example, `http`, `ftp` or `sip`.
  static final _gAppInfoGetDefaultForUriScheme =
      gioLookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(ffi.Pointer<Utf8>)
            >
          >('g_app_info_get_default_for_uri_scheme')
          .asFunction<ffi.Pointer<ffi.Void> Function(ffi.Pointer<Utf8>)>();
  static GAppInfo? getDefaultForUriScheme(String uriScheme) {
    return withNativeString(uriScheme, (nativeUriScheme) {
      return (_gAppInfoGetDefaultForUriScheme(nativeUriScheme.cast<Utf8>())) ==
              ffi.nullptr
          ? null
          : GAppInfo.fromPointer(
              _gAppInfoGetDefaultForUriScheme(nativeUriScheme.cast<Utf8>()),
            );
    });
  }

  /// Asynchronously gets the default application for handling URIs with
  /// the given URI scheme. A URI scheme is the initial part
  /// of the URI, up to but not including the `:`, e.g. `http`,
  /// `ftp` or `sip`.
  static final _gAppInfoGetDefaultForUriSchemeAsync =
      gioLookup<
            ffi.NativeFunction<
              ffi.Void Function(
                ffi.Pointer<Utf8>,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<
                  ffi.NativeFunction<
                    ffi.Void Function(
                      ffi.Pointer<ffi.Void>,
                      ffi.Pointer<ffi.Void>,
                      ffi.Pointer<ffi.Void>,
                    )
                  >
                >,
                ffi.Pointer<ffi.Void>,
              )
            >
          >('g_app_info_get_default_for_uri_scheme_async')
          .asFunction<
            void Function(
              ffi.Pointer<Utf8>,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<
                ffi.NativeFunction<
                  ffi.Void Function(
                    ffi.Pointer<ffi.Void>,
                    ffi.Pointer<ffi.Void>,
                    ffi.Pointer<ffi.Void>,
                  )
                >
              >,
              ffi.Pointer<ffi.Void>,
            )
          >();
  static void getDefaultForUriSchemeAsync(
    String uriScheme,
    GCancellable? cancellable,
    void Function(
      ffi.Pointer<ffi.Void>,
      ffi.Pointer<ffi.Void>,
      ffi.Pointer<ffi.Void>,
    )?
    callback,
    ffi.Pointer<ffi.Void> userData,
  ) {
    withNativeString(uriScheme, (nativeUriScheme) {
      final _nc3 = callback == null
          ? null
          : ffi.NativeCallable<
              ffi.Void Function(
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Void>,
              )
            >.isolateLocal(callback);
      try {
        _gAppInfoGetDefaultForUriSchemeAsync(
          nativeUriScheme.cast<Utf8>(),
          cancellable?.handle ?? ffi.nullptr,
          _nc3?.nativeFunction ?? ffi.nullptr,
          userData,
        );
      } finally {
        _nc3?.close();
      }
    });
  }

  /// Finishes a default [iface@Gio.AppInfo] lookup started by
  /// [func@Gio.AppInfo.get_default_for_uri_scheme_async].
  ///
  /// If no [iface@Gio.AppInfo] is found, then @error will be set to
  /// [error@Gio.IOErrorEnum.NOT_FOUND].
  static final _gAppInfoGetDefaultForUriSchemeFinish =
      gioLookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Pointer<ffi.Void>>,
              )
            >
          >('g_app_info_get_default_for_uri_scheme_finish')
          .asFunction<
            ffi.Pointer<ffi.Void> Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Pointer<ffi.Void>>,
            )
          >();
  static GAppInfo getDefaultForUriSchemeFinish(GAsyncResult result) {
    final _error = calloc<ffi.Pointer<ffi.Void>>();
    try {
      final _ret = _gAppInfoGetDefaultForUriSchemeFinish(result.handle, _error);
      if (_error.value != ffi.nullptr) {
        throw GlibException.fromError(_error.value);
      }
      return GAppInfo.fromPointer(_ret);
    } finally {
      calloc.free(_error);
    }
  }

  /// Gets a list of fallback [iface@Gio.AppInfo]s for a given content type, i.e.
  /// those applications which claim to support the given content type by MIME
  /// type subclassing and not directly.
  static final _gAppInfoGetFallbackForType =
      gioLookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(ffi.Pointer<Utf8>)
            >
          >('g_app_info_get_fallback_for_type')
          .asFunction<ffi.Pointer<ffi.Void> Function(ffi.Pointer<Utf8>)>();
  static GList getFallbackForType(String contentType) {
    return withNativeString(contentType, (nativeContentType) {
      return GList.fromPointer(
        _gAppInfoGetFallbackForType(nativeContentType.cast<Utf8>()),
      );
    });
  }

  /// Gets a list of recommended [iface@Gio.AppInfo]s for a given content type,
  /// i.e. those applications which claim to support the given content type
  /// exactly, and not by MIME type subclassing.
  ///
  /// Note that the first application of the list is the last used one, i.e.
  /// the last one for which [method@Gio.AppInfo.set_as_last_used_for_type] has
  /// been called.
  static final _gAppInfoGetRecommendedForType =
      gioLookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(ffi.Pointer<Utf8>)
            >
          >('g_app_info_get_recommended_for_type')
          .asFunction<ffi.Pointer<ffi.Void> Function(ffi.Pointer<Utf8>)>();
  static GList getRecommendedForType(String contentType) {
    return withNativeString(contentType, (nativeContentType) {
      return GList.fromPointer(
        _gAppInfoGetRecommendedForType(nativeContentType.cast<Utf8>()),
      );
    });
  }

  /// Utility function that launches the default application registered to handle
  /// the specified uri. Synchronous I/O is done on the uri to detect the type of
  /// the file if required.
  ///
  /// The D-Bus–activated applications don’t have to be started if your application
  /// terminates too soon after this function. To prevent this, use
  /// [func@Gio.AppInfo.launch_default_for_uri_async] instead.
  static final _gAppInfoLaunchDefaultForUri =
      gioLookup<
            ffi.NativeFunction<
              ffi.Int32 Function(
                ffi.Pointer<Utf8>,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Pointer<ffi.Void>>,
              )
            >
          >('g_app_info_launch_default_for_uri')
          .asFunction<
            int Function(
              ffi.Pointer<Utf8>,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Pointer<ffi.Void>>,
            )
          >();
  static bool launchDefaultForUri(String uri, [GAppLaunchContext? context]) {
    return withNativeString(uri, (nativeUri) {
      final _error = calloc<ffi.Pointer<ffi.Void>>();
      try {
        final _ret = _gAppInfoLaunchDefaultForUri(
          nativeUri.cast<Utf8>(),
          context?.handle ?? ffi.nullptr,
          _error,
        );
        if (_error.value != ffi.nullptr) {
          throw GlibException.fromError(_error.value);
        }
        return (_ret) != 0;
      } finally {
        calloc.free(_error);
      }
    });
  }

  /// Async version of [func@Gio.AppInfo.launch_default_for_uri].
  ///
  /// This version is useful if you are interested in receiving error information
  /// in the case where the application is sandboxed and the portal may present an
  /// application chooser dialog to the user.
  ///
  /// This is also useful if you want to be sure that the D-Bus–activated
  /// applications are really started before termination and if you are interested
  /// in receiving error information from their activation.
  static final _gAppInfoLaunchDefaultForUriAsync =
      gioLookup<
            ffi.NativeFunction<
              ffi.Void Function(
                ffi.Pointer<Utf8>,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<
                  ffi.NativeFunction<
                    ffi.Void Function(
                      ffi.Pointer<ffi.Void>,
                      ffi.Pointer<ffi.Void>,
                      ffi.Pointer<ffi.Void>,
                    )
                  >
                >,
                ffi.Pointer<ffi.Void>,
              )
            >
          >('g_app_info_launch_default_for_uri_async')
          .asFunction<
            void Function(
              ffi.Pointer<Utf8>,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<
                ffi.NativeFunction<
                  ffi.Void Function(
                    ffi.Pointer<ffi.Void>,
                    ffi.Pointer<ffi.Void>,
                    ffi.Pointer<ffi.Void>,
                  )
                >
              >,
              ffi.Pointer<ffi.Void>,
            )
          >();
  static void launchDefaultForUriAsync(
    String uri,
    GAppLaunchContext? context,
    GCancellable? cancellable,
    void Function(
      ffi.Pointer<ffi.Void>,
      ffi.Pointer<ffi.Void>,
      ffi.Pointer<ffi.Void>,
    )?
    callback,
    ffi.Pointer<ffi.Void> userData,
  ) {
    withNativeString(uri, (nativeUri) {
      final _nc4 = callback == null
          ? null
          : ffi.NativeCallable<
              ffi.Void Function(
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Void>,
              )
            >.isolateLocal(callback);
      try {
        _gAppInfoLaunchDefaultForUriAsync(
          nativeUri.cast<Utf8>(),
          context?.handle ?? ffi.nullptr,
          cancellable?.handle ?? ffi.nullptr,
          _nc4?.nativeFunction ?? ffi.nullptr,
          userData,
        );
      } finally {
        _nc4?.close();
      }
    });
  }

  /// Finishes an asynchronous launch-default-for-uri operation.
  static final _gAppInfoLaunchDefaultForUriFinish =
      gioLookup<
            ffi.NativeFunction<
              ffi.Int32 Function(
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Pointer<ffi.Void>>,
              )
            >
          >('g_app_info_launch_default_for_uri_finish')
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Pointer<ffi.Void>>,
            )
          >();
  static bool launchDefaultForUriFinish(GAsyncResult result) {
    final _error = calloc<ffi.Pointer<ffi.Void>>();
    try {
      final _ret = _gAppInfoLaunchDefaultForUriFinish(result.handle, _error);
      if (_error.value != ffi.nullptr) {
        throw GlibException.fromError(_error.value);
      }
      return (_ret) != 0;
    } finally {
      calloc.free(_error);
    }
  }

  /// Removes all changes to the type associations done by
  /// [method@Gio.AppInfo.set_as_default_for_type],
  /// [method@Gio.AppInfo.set_as_default_for_extension],
  /// [method@Gio.AppInfo.add_supports_type] or
  /// [method@Gio.AppInfo.remove_supports_type].
  static final _gAppInfoResetTypeAssociations =
      gioLookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<Utf8>)>>(
        'g_app_info_reset_type_associations',
      ).asFunction<void Function(ffi.Pointer<Utf8>)>();
  static void resetTypeAssociations(String contentType) {
    withNativeString(contentType, (nativeContentType) {
      _gAppInfoResetTypeAssociations(nativeContentType.cast<Utf8>());
    });
  }
}
