// Generated by gir_generator. Do not edit.
part of '../gdk_pixbuf.dart';

/// Major version of gdk-pixbuf library, that is the "0" in
/// "0.8.2" for example.
const pixbufMajor = 2;

/// Micro version of gdk-pixbuf library, that is the "2" in
/// "0.8.2" for example.
const pixbufMicro = 4;

/// Minor version of gdk-pixbuf library, that is the "8" in
/// "0.8.2" for example.
const pixbufMinor = 44;

/// Contains the full version of GdkPixbuf as a string.
///
/// This is the version being compiled against; contrast with
/// `gdk_pixbuf_version`.
const pixbufVersion = '2.44.4';
