// Generated by gir_generator. Do not edit.
part of '../pango.dart';

/// A `PangoFontFace` is used to represent a group of fonts with
/// the same family, slant, weight, and width, but varying sizes.
class PangoFontFace implements ffi.Finalizable {
  PangoFontFace.fromPointer(this.handle, {this.owned = false}) {
    if (owned) {
      _attachFinalizer();
    }
  }
  final ffi.Pointer<ffi.Void> handle;
  final bool owned;
  void _attachFinalizer() =>
      gobjectFinalizer.attach(this, handle, detach: this);

  /// Returns a font description that matches the face.
  ///
  /// The resulting font description will have the family, style,
  /// variant, weight and stretch of the face, but its size field
  /// will be unset.
  static final _pangoFontFaceDescribe =
      pangoLookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)
            >
          >('pango_font_face_describe')
          .asFunction<ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)>();
  PangoFontDescription describe() {
    return PangoFontDescription.fromPointer(
      _pangoFontFaceDescribe(this.handle),
    );
  }

  /// Gets a name representing the style of this face.
  ///
  /// Note that a font family may contain multiple faces
  /// with the same name (e.g. a variable and a non-variable
  /// face for the same style).
  static final _pangoFontFaceGetFaceName =
      pangoLookup<
            ffi.NativeFunction<
              ffi.Pointer<Utf8> Function(ffi.Pointer<ffi.Void>)
            >
          >('pango_font_face_get_face_name')
          .asFunction<ffi.Pointer<Utf8> Function(ffi.Pointer<ffi.Void>)>();
  String getFaceName() {
    return stringFromNative(
      (_pangoFontFaceGetFaceName(this.handle)).cast(),
      free: false,
    )!;
  }

  /// Gets the `PangoFontFamily` that @face belongs to.
  static final _pangoFontFaceGetFamily =
      pangoLookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)
            >
          >('pango_font_face_get_family')
          .asFunction<ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)>();
  PangoFontFamily getFamily() {
    return PangoFontFamily.fromPointer(_pangoFontFaceGetFamily(this.handle));
  }

  /// Returns whether a `PangoFontFace` is synthesized.
  ///
  /// This will be the case if the underlying font rendering engine
  /// creates this face from another face, by shearing, emboldening,
  /// lightening or modifying it in some other way.
  static final _pangoFontFaceIsSynthesized =
      pangoLookup<
            ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Void>)>
          >('pango_font_face_is_synthesized')
          .asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  bool isSynthesized() {
    return (_pangoFontFaceIsSynthesized(this.handle)) != 0;
  }
}

/// A `PangoFontFamily` is used to represent a family of related
/// font faces.
///
/// The font faces in a family share a common design, but differ in
/// slant, weight, width or other aspects.
class PangoFontFamily implements ffi.Finalizable {
  PangoFontFamily.fromPointer(this.handle, {this.owned = false}) {
    if (owned) {
      _attachFinalizer();
    }
  }
  final ffi.Pointer<ffi.Void> handle;
  final bool owned;
  void _attachFinalizer() =>
      gobjectFinalizer.attach(this, handle, detach: this);

  /// Gets the `PangoFontFace` of @family with the given name.
  static final _pangoFontFamilyGetFace =
      pangoLookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<Utf8>,
              )
            >
          >('pango_font_family_get_face')
          .asFunction<
            ffi.Pointer<ffi.Void> Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<Utf8>,
            )
          >();
  PangoFontFace? getFace([String? name]) {
    return withNativeString(name, (nativeName) {
      return (_pangoFontFamilyGetFace(this.handle, nativeName.cast<Utf8>())) ==
              ffi.nullptr
          ? null
          : PangoFontFace.fromPointer(
              _pangoFontFamilyGetFace(this.handle, nativeName.cast<Utf8>()),
            );
    });
  }

  /// Gets the name of the family.
  ///
  /// The name is unique among all fonts for the font backend and can
  /// be used in a `PangoFontDescription` to specify that a face from
  /// this family is desired.
  static final _pangoFontFamilyGetName =
      pangoLookup<
            ffi.NativeFunction<
              ffi.Pointer<Utf8> Function(ffi.Pointer<ffi.Void>)
            >
          >('pango_font_family_get_name')
          .asFunction<ffi.Pointer<Utf8> Function(ffi.Pointer<ffi.Void>)>();
  String getName() {
    return stringFromNative(
      (_pangoFontFamilyGetName(this.handle)).cast(),
      free: false,
    )!;
  }

  /// A monospace font is a font designed for text display where the the
  /// characters form a regular grid.
  ///
  /// For Western languages this would
  /// mean that the advance width of all characters are the same, but
  /// this categorization also includes Asian fonts which include
  /// double-width characters: characters that occupy two grid cells.
  /// g_unichar_iswide() returns a result that indicates whether a
  /// character is typically double-width in a monospace font.
  ///
  /// The best way to find out the grid-cell size is to call
  /// [method@Pango.FontMetrics.get_approximate_digit_width], since the
  /// results of [method@Pango.FontMetrics.get_approximate_char_width] may
  /// be affected by double-width characters.
  static final _pangoFontFamilyIsMonospace =
      pangoLookup<
            ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Void>)>
          >('pango_font_family_is_monospace')
          .asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  bool isMonospace() {
    return (_pangoFontFamilyIsMonospace(this.handle)) != 0;
  }

  /// A variable font is a font which has axes that can be modified to
  /// produce different faces.
  ///
  /// Such axes are also known as _variations_; see
  /// [method@Pango.FontDescription.set_variations] for more information.
  static final _pangoFontFamilyIsVariable =
      pangoLookup<
            ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Void>)>
          >('pango_font_family_is_variable')
          .asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  bool isVariable() {
    return (_pangoFontFamilyIsVariable(this.handle)) != 0;
  }
}

/// A `PangoFontMap` represents the set of fonts available for a
/// particular rendering system.
///
/// This is a virtual object with implementations being specific to
/// particular rendering systems.
class PangoFontMap implements ffi.Finalizable {
  PangoFontMap.fromPointer(this.handle, {this.owned = false}) {
    if (owned) {
      _attachFinalizer();
    }
  }
  final ffi.Pointer<ffi.Void> handle;
  final bool owned;
  void _attachFinalizer() =>
      gobjectFinalizer.attach(this, handle, detach: this);

  /// Loads a font file with one or more fonts into the `PangoFontMap`.
  ///
  /// The added fonts will take precedence over preexisting
  /// fonts with the same name.
  static final _pangoFontMapAddFontFile =
      pangoLookup<
            ffi.NativeFunction<
              ffi.Int32 Function(
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<Utf8>,
                ffi.Pointer<ffi.Pointer<ffi.Void>>,
              )
            >
          >('pango_font_map_add_font_file')
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<Utf8>,
              ffi.Pointer<ffi.Pointer<ffi.Void>>,
            )
          >();
  bool addFontFile(String filename) {
    return withNativeString(filename, (nativeFilename) {
      final _error = calloc<ffi.Pointer<ffi.Void>>();
      try {
        final _ret = _pangoFontMapAddFontFile(
          this.handle,
          nativeFilename.cast<Utf8>(),
          _error,
        );
        if (_error.value != ffi.nullptr) {
          throw GlibException.fromError(_error.value);
        }
        return (_ret) != 0;
      } finally {
        calloc.free(_error);
      }
    });
  }

  /// Forces a change in the fontmap, which will cause any `PangoContext`
  /// using this fontmap to change.
  ///
  /// This function is only useful when implementing a new backend
  /// for Pango, something applications won't do. Backends should
  /// call this function if they have attached extra data to the
  /// fontmap and such data is changed.
  static final _pangoFontMapChanged =
      pangoLookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'pango_font_map_changed',
      ).asFunction<void Function(ffi.Pointer<ffi.Void>)>();
  void changed() {
    _pangoFontMapChanged(this.handle);
  }

  /// Creates a `PangoContext` connected to @fontmap.
  ///
  /// This is equivalent to [ctor@Pango.Context.new] followed by
  /// [method@Pango.Context.set_font_map].
  ///
  /// If you are using Pango as part of a higher-level system,
  /// that system may have it's own way of create a `PangoContext`.
  /// For instance, the GTK toolkit has, among others,
  /// gtk_widget_get_pango_context(). Use those instead.
  static final _pangoFontMapCreateContext =
      pangoLookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)
            >
          >('pango_font_map_create_context')
          .asFunction<ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)>();
  PangoContext createContext() {
    return PangoContext.fromPointer(_pangoFontMapCreateContext(this.handle));
  }

  /// Gets a font family by name.
  static final _pangoFontMapGetFamily =
      pangoLookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<Utf8>,
              )
            >
          >('pango_font_map_get_family')
          .asFunction<
            ffi.Pointer<ffi.Void> Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<Utf8>,
            )
          >();
  PangoFontFamily? getFamily(String name) {
    return withNativeString(name, (nativeName) {
      return (_pangoFontMapGetFamily(this.handle, nativeName.cast<Utf8>())) ==
              ffi.nullptr
          ? null
          : PangoFontFamily.fromPointer(
              _pangoFontMapGetFamily(this.handle, nativeName.cast<Utf8>()),
            );
    });
  }

  /// Returns the current serial number of @fontmap.
  ///
  /// The serial number is initialized to an small number larger than zero
  /// when a new fontmap is created and is increased whenever the fontmap
  /// is changed. It may wrap, but will never have the value 0. Since it can
  /// wrap, never compare it with "less than", always use "not equals".
  ///
  /// The fontmap can only be changed using backend-specific API, like changing
  /// fontmap resolution.
  ///
  /// This can be used to automatically detect changes to a `PangoFontMap`,
  /// like in `PangoContext`.
  static final _pangoFontMapGetSerial =
      pangoLookup<
            ffi.NativeFunction<ffi.Uint32 Function(ffi.Pointer<ffi.Void>)>
          >('pango_font_map_get_serial')
          .asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  int getSerial() {
    return _pangoFontMapGetSerial(this.handle);
  }

  /// Load the font in the fontmap that is the closest match for @desc.
  static final _pangoFontMapLoadFont =
      pangoLookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Void>,
              )
            >
          >('pango_font_map_load_font')
          .asFunction<
            ffi.Pointer<ffi.Void> Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Void>,
            )
          >();
  PangoFont? loadFont(PangoContext context, PangoFontDescription desc) {
    return (_pangoFontMapLoadFont(this.handle, context.handle, desc.handle)) ==
            ffi.nullptr
        ? null
        : PangoFont.fromPointer(
            _pangoFontMapLoadFont(this.handle, context.handle, desc.handle),
          );
  }

  /// Load a set of fonts in the fontmap that can be used to render
  /// a font matching @desc.
  static final _pangoFontMapLoadFontset =
      pangoLookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Void>,
              )
            >
          >('pango_font_map_load_fontset')
          .asFunction<
            ffi.Pointer<ffi.Void> Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Void>,
            )
          >();
  PangoFontset? loadFontset(
    PangoContext context,
    PangoFontDescription desc,
    PangoLanguage language,
  ) {
    return (_pangoFontMapLoadFontset(
              this.handle,
              context.handle,
              desc.handle,
              language.handle,
            )) ==
            ffi.nullptr
        ? null
        : PangoFontset.fromPointer(
            _pangoFontMapLoadFontset(
              this.handle,
              context.handle,
              desc.handle,
              language.handle,
            ),
          );
  }

  /// Returns a new font that is like @font, except that it is scaled
  /// by @scale, its backend-dependent configuration (e.g. cairo font options)
  /// is replaced by the one in @context, and its variations are replaced
  /// by @variations.
  ///
  /// Note that the scaling here is meant to be linear, so this
  /// scaling can be used to render a font on a hi-dpi display
  /// without changing its optical size.
  static final _pangoFontMapReloadFont =
      pangoLookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Void>,
                ffi.Double,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<Utf8>,
              )
            >
          >('pango_font_map_reload_font')
          .asFunction<
            ffi.Pointer<ffi.Void> Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Void>,
              double,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<Utf8>,
            )
          >();
  PangoFont reloadFont(
    PangoFont font,
    double scale, [
    PangoContext? context,
    String? variations,
  ]) {
    return withNativeString(variations, (nativeVariations) {
      return PangoFont.fromPointer(
        _pangoFontMapReloadFont(
          this.handle,
          font.handle,
          scale,
          context?.handle ?? ffi.nullptr,
          nativeVariations.cast<Utf8>(),
        ),
      );
    });
  }
}

/// A `PangoFontset` represents a set of `PangoFont` to use when rendering text.
///
/// A `PangoFontset` is the result of resolving a `PangoFontDescription`
/// against a particular `PangoContext`. It has operations for finding the
/// component font for a particular Unicode character, and for finding a
/// composite set of metrics for the entire fontset.
class PangoFontset implements ffi.Finalizable {
  PangoFontset.fromPointer(this.handle, {this.owned = false}) {
    if (owned) {
      _attachFinalizer();
    }
  }
  final ffi.Pointer<ffi.Void> handle;
  final bool owned;
  void _attachFinalizer() =>
      gobjectFinalizer.attach(this, handle, detach: this);

  /// Iterates through all the fonts in a fontset, calling @func for
  /// each one.
  ///
  /// If @func returns %TRUE, that stops the iteration.
  static final _pangoFontsetForeach =
      pangoLookup<
            ffi.NativeFunction<
              ffi.Void Function(
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<
                  ffi.NativeFunction<
                    ffi.Int32 Function(
                      ffi.Pointer<ffi.Void>,
                      ffi.Pointer<ffi.Void>,
                      ffi.Pointer<ffi.Void>,
                    )
                  >
                >,
                ffi.Pointer<ffi.Void>,
              )
            >
          >('pango_fontset_foreach')
          .asFunction<
            void Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<
                ffi.NativeFunction<
                  ffi.Int32 Function(
                    ffi.Pointer<ffi.Void>,
                    ffi.Pointer<ffi.Void>,
                    ffi.Pointer<ffi.Void>,
                  )
                >
              >,
              ffi.Pointer<ffi.Void>,
            )
          >();
  void foreach(
    int Function(
      ffi.Pointer<ffi.Void>,
      ffi.Pointer<ffi.Void>,
      ffi.Pointer<ffi.Void>,
    )
    func,
    ffi.Pointer<ffi.Void> data,
  ) {
    final _nc1 =
        ffi.NativeCallable<
          ffi.Int32 Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Void>,
          )
        >.isolateLocal(func, exceptionalReturn: 0);
    try {
      _pangoFontsetForeach(this.handle, _nc1.nativeFunction, data);
    } finally {
      _nc1.close();
    }
  }

  /// Returns the font in the fontset that contains the best
  /// glyph for a Unicode character.
  static final _pangoFontsetGetFont =
      pangoLookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>, ffi.Uint32)
            >
          >('pango_fontset_get_font')
          .asFunction<
            ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>, int)
          >();
  PangoFont getFont(int wc) {
    return PangoFont.fromPointer(_pangoFontsetGetFont(this.handle, wc));
  }

  /// Get overall metric information for the fonts in the fontset.
  static final _pangoFontsetGetMetrics =
      pangoLookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)
            >
          >('pango_fontset_get_metrics')
          .asFunction<ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)>();
  PangoFontMetrics getMetrics() {
    return PangoFontMetrics.fromPointer(_pangoFontsetGetMetrics(this.handle));
  }
}

/// `PangoFontsetSimple` is a implementation of the abstract
/// `PangoFontset` base class as an array of fonts.
///
/// When creating a `PangoFontsetSimple`, you have to provide
/// the array of fonts that make up the fontset.
class PangoFontsetSimple extends PangoFontset {
  PangoFontsetSimple.fromPointer(super.handle, {super.owned})
    : super.fromPointer();

  /// Creates a new `PangoFontsetSimple` for the given language.
  static final _pangoFontsetSimpleNew =
      pangoLookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)
            >
          >('pango_fontset_simple_new')
          .asFunction<ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)>();
  factory PangoFontsetSimple(PangoLanguage language) {
    return PangoFontsetSimple.fromPointer(
      _pangoFontsetSimpleNew(language.handle),
      owned: true,
    );
  }

  /// Adds a font to the fontset.
  ///
  /// The fontset takes ownership of @font.
  static final _pangoFontsetSimpleAppend =
      pangoLookup<
            ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)
            >
          >('pango_fontset_simple_append')
          .asFunction<
            void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)
          >();
  void append(PangoFont font) {
    _pangoFontsetSimpleAppend(this.handle, font.handle);
  }

  /// Returns the number of fonts in the fontset.
  static final _pangoFontsetSimpleSize =
      pangoLookup<
            ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Void>)>
          >('pango_fontset_simple_size')
          .asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  int size() {
    return _pangoFontsetSimpleSize(this.handle);
  }
}
