// Generated by gir_generator. Do not edit.
part of '../gobject.dart';

/// A #GParamSpec derived structure that contains the meta data for double properties.
class GParamSpecDouble extends GParamSpec {
  GParamSpecDouble.fromPointer(super.handle, {super.owned})
    : super.fromPointer();
}
