// Generated by gir_generator. Do not edit.
part of '../gtk4.dart';

/// PyGObject-style typed property accessor. Each getter
/// and setter delegates to the existing typed
/// `get<Name>` / `set<Name>` methods on [GtkFileChooserNative].
///
/// Skipped properties (unsupported type, missing getter
/// or setter) are recorded in the generation report.
class GtkFileChooserNativeProps extends GtkNativeDialogProps {
  GtkFileChooserNativeProps(GtkFileChooserNative $self)
    : _self = $self,
      super($self);
  final GtkFileChooserNative _self;

  String? get acceptLabel => _self.getAcceptLabel();
  set acceptLabel(String? value) {
    _self.setAcceptLabel(value);
  }

  String? get cancelLabel => _self.getCancelLabel();
  set cancelLabel(String? value) {
    _self.setCancelLabel(value);
  }

  bool get modal => _self.getModal();
  set modal(bool value) {
    _self.setModal(value);
  }

  String? get title => _self.getTitle();
  set title(String value) {
    _self.setTitle(value);
  }

  GtkWindow? get transientFor => _self.getTransientFor();
  set transientFor(GtkWindow? value) {
    _self.setTransientFor(value);
  }

  bool get visible => _self.getVisible();
}
