// Generated by gir_generator. Do not edit.
part of '../gtk4.dart';

/// Allows to select a numeric value with a slider control.
///
/// <picture>
/// <source srcset="scales-dark.png" media="(prefers-color-scheme: dark)">
/// <img alt="An example GtkScale" src="scales.png">
/// </picture>
///
/// To use it, you’ll probably want to investigate the methods on its base
/// class, [class@Gtk.Range], in addition to the methods for `GtkScale` itself.
/// To set the value of a scale, you would normally use [method@Gtk.Range.set_value].
/// To detect changes to the value, you would normally use the
/// [signal@Gtk.Range::value-changed] signal.
///
/// Note that using the same upper and lower bounds for the `GtkScale` (through
/// the `GtkRange` methods) will hide the slider itself. This is useful for
/// applications that want to show an undeterminate value on the scale, without
/// changing the layout of the application (such as movie or music players).
///
/// # GtkScale as GtkBuildable
///
/// `GtkScale` supports a custom `<marks>` element, which can contain multiple
/// `<mark\>` elements. The “value” and “position” attributes have the same
/// meaning as [method@Gtk.Scale.add_mark] parameters of the same name. If
/// the element is not empty, its content is taken as the markup to show at
/// the mark. It can be translated with the usual ”translatable” and
/// “context” attributes.
///
/// # Shortcuts and Gestures
///
/// `GtkPopoverMenu` supports the following keyboard shortcuts:
///
/// - Arrow keys, <kbd>+</kbd> and <kbd>-</kbd> will increment or decrement
/// by step, or by page when combined with <kbd>Ctrl</kbd>.
/// - <kbd>PgUp</kbd> and <kbd>PgDn</kbd> will increment or decrement by page.
/// - <kbd>Home</kbd> and <kbd>End</kbd> will set the minimum or maximum value.
///
/// # CSS nodes
///
/// ```
/// scale[.fine-tune][.marks-before][.marks-after]
/// ├── [value][.top][.right][.bottom][.left]
/// ├── marks.top
/// │   ├── mark
/// │   ┊    ├── [label]
/// │   ┊    ╰── indicator
/// ┊   ┊
/// │   ╰── mark
/// ├── marks.bottom
/// │   ├── mark
/// │   ┊    ├── indicator
/// │   ┊    ╰── [label]
/// ┊   ┊
/// │   ╰── mark
/// ╰── trough
/// ├── [fill]
/// ├── [highlight]
/// ╰── slider
/// ```
///
/// `GtkScale` has a main CSS node with name scale and a subnode for its contents,
/// with subnodes named trough and slider.
///
/// The main node gets the style class .fine-tune added when the scale is in
/// 'fine-tuning' mode.
///
/// If the scale has an origin (see [method@Gtk.Scale.set_has_origin]), there is
/// a subnode with name highlight below the trough node that is used for rendering
/// the highlighted part of the trough.
///
/// If the scale is showing a fill level (see [method@Gtk.Range.set_show_fill_level]),
/// there is a subnode with name fill below the trough node that is used for
/// rendering the filled in part of the trough.
///
/// If marks are present, there is a marks subnode before or after the trough
/// node, below which each mark gets a node with name mark. The marks nodes get
/// either the .top or .bottom style class.
///
/// The mark node has a subnode named indicator. If the mark has text, it also
/// has a subnode named label. When the mark is either above or left of the
/// scale, the label subnode is the first when present. Otherwise, the indicator
/// subnode is the first.
///
/// The main CSS node gets the 'marks-before' and/or 'marks-after' style classes
/// added depending on what marks are present.
///
/// If the scale is displaying the value (see [property@Gtk.Scale:draw-value]),
/// there is subnode with name value. This node will get the .top or .bottom style
/// classes similar to the marks node.
///
/// # Accessibility
///
/// `GtkScale` uses the [enum@Gtk.AccessibleRole.slider] role.
class GtkScale extends GtkRange {
  GtkScale.fromPointer(super.handle, {super.owned}) : super.fromPointer();

  /// Creates a new `GtkScale`.
  static final _gtkScaleNew =
      gtk4Lookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(ffi.Int32, ffi.Pointer<ffi.Void>)
            >
          >('gtk_scale_new')
          .asFunction<
            ffi.Pointer<ffi.Void> Function(int, ffi.Pointer<ffi.Void>)
          >();
  factory GtkScale(GtkOrientation orientation, [GtkAdjustment? adjustment]) {
    return GtkScale.fromPointer(
      gObjectRefSink(
        _gtkScaleNew(orientation.value, adjustment?.handle ?? ffi.nullptr),
      ),
      owned: true,
    );
  }

  /// Creates a new scale widget with a range from @min to @max.
  ///
  /// The returns scale will have the given orientation and will let the
  /// user input a number between @min and @max (including @min and @max)
  /// with the increment @step. @step must be nonzero; it’s the distance
  /// the slider moves when using the arrow keys to adjust the scale
  /// value.
  ///
  /// Note that the way in which the precision is derived works best if
  /// @step is a power of ten. If the resulting precision is not suitable
  /// for your needs, use [method@Gtk.Scale.set_digits] to correct it.
  static final _gtkScaleNewWithRange =
      gtk4Lookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(
                ffi.Int32,
                ffi.Double,
                ffi.Double,
                ffi.Double,
              )
            >
          >('gtk_scale_new_with_range')
          .asFunction<
            ffi.Pointer<ffi.Void> Function(int, double, double, double)
          >();
  factory GtkScale.withRange(
    GtkOrientation orientation,
    double min,
    double max,
    double step,
  ) {
    return GtkScale.fromPointer(
      gObjectRefSink(_gtkScaleNewWithRange(orientation.value, min, max, step)),
      owned: true,
    );
  }

  /// Adds a mark at @value.
  ///
  /// A mark is indicated visually by drawing a tick mark next to the scale,
  /// and GTK makes it easy for the user to position the scale exactly at the
  /// marks value.
  ///
  /// If @markup is not %NULL, text is shown next to the tick mark.
  ///
  /// To remove marks from a scale, use [method@Gtk.Scale.clear_marks].
  static final _gtkScaleAddMark =
      gtk4Lookup<
            ffi.NativeFunction<
              ffi.Void Function(
                ffi.Pointer<ffi.Void>,
                ffi.Double,
                ffi.Int32,
                ffi.Pointer<Utf8>,
              )
            >
          >('gtk_scale_add_mark')
          .asFunction<
            void Function(ffi.Pointer<ffi.Void>, double, int, ffi.Pointer<Utf8>)
          >();
  void addMark(double value, GtkPositionType position, [String? markup]) {
    withNativeString(markup, (nativeMarkup) {
      _gtkScaleAddMark(
        this.handle,
        value,
        position.value,
        nativeMarkup.cast<Utf8>(),
      );
    });
  }

  /// Removes any marks that have been added.
  static final _gtkScaleClearMarks =
      gtk4Lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'gtk_scale_clear_marks',
      ).asFunction<void Function(ffi.Pointer<ffi.Void>)>();
  void clearMarks() {
    _gtkScaleClearMarks(this.handle);
  }

  /// Gets the number of decimal places that are displayed in the value.
  static final _gtkScaleGetDigits =
      gtk4Lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Void>)>>(
        'gtk_scale_get_digits',
      ).asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  int getDigits() {
    return _gtkScaleGetDigits(this.handle);
  }

  /// Returns whether the current value is displayed as a string
  /// next to the slider.
  static final _gtkScaleGetDrawValue =
      gtk4Lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Void>)>>(
        'gtk_scale_get_draw_value',
      ).asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  bool getDrawValue() {
    return (_gtkScaleGetDrawValue(this.handle)) != 0;
  }

  /// Returns whether the scale has an origin.
  static final _gtkScaleGetHasOrigin =
      gtk4Lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Void>)>>(
        'gtk_scale_get_has_origin',
      ).asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  bool getHasOrigin() {
    return (_gtkScaleGetHasOrigin(this.handle)) != 0;
  }

  /// Gets the `PangoLayout` used to display the scale.
  ///
  /// The returned object is owned by the scale so does not need
  /// to be freed by the caller.
  static final _gtkScaleGetLayout =
      gtk4Lookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)
            >
          >('gtk_scale_get_layout')
          .asFunction<ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)>();
  PangoLayout? getLayout() {
    return (_gtkScaleGetLayout(this.handle)) == ffi.nullptr
        ? null
        : PangoLayout.fromPointer(_gtkScaleGetLayout(this.handle));
  }

  /// Gets the position in which the current value is displayed.
  static final _gtkScaleGetValuePos =
      gtk4Lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Void>)>>(
        'gtk_scale_get_value_pos',
      ).asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  GtkPositionType getValuePos() {
    return GtkPositionType.fromValue(_gtkScaleGetValuePos(this.handle));
  }

  /// Sets the number of decimal places that are displayed in the value.
  ///
  /// Also causes the value of the adjustment to be rounded to this number
  /// of digits, so the retrieved value matches the displayed one, if
  /// [property@Gtk.Scale:draw-value] is %TRUE when the value changes. If
  /// you want to enforce rounding the value when [property@Gtk.Scale:draw-value]
  /// is %FALSE, you can set [property@Gtk.Range:round-digits] instead.
  ///
  /// Note that rounding to a small number of digits can interfere with
  /// the smooth autoscrolling that is built into `GtkScale`. As an alternative,
  /// you can use [method@Gtk.Scale.set_format_value_func] to format the displayed
  /// value yourself.
  static final _gtkScaleSetDigits =
      gtk4Lookup<
            ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Int32)
            >
          >('gtk_scale_set_digits')
          .asFunction<void Function(ffi.Pointer<ffi.Void>, int)>();
  void setDigits(int digits) {
    _gtkScaleSetDigits(this.handle, digits);
  }

  /// Specifies whether the current value is displayed as a string next
  /// to the slider.
  static final _gtkScaleSetDrawValue =
      gtk4Lookup<
            ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Int32)
            >
          >('gtk_scale_set_draw_value')
          .asFunction<void Function(ffi.Pointer<ffi.Void>, int)>();
  void setDrawValue(bool drawValue) {
    _gtkScaleSetDrawValue(this.handle, drawValue ? 1 : 0);
  }

  /// Sets whether the scale has an origin.
  ///
  /// If [property@Gtk.Scale:has-origin] is set to %TRUE (the default),
  /// the scale will highlight the part of the trough between the origin
  /// (bottom or left side) and the current value.
  static final _gtkScaleSetHasOrigin =
      gtk4Lookup<
            ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Int32)
            >
          >('gtk_scale_set_has_origin')
          .asFunction<void Function(ffi.Pointer<ffi.Void>, int)>();
  void setHasOrigin(bool hasOrigin) {
    _gtkScaleSetHasOrigin(this.handle, hasOrigin ? 1 : 0);
  }

  /// Sets the position in which the current value is displayed.
  static final _gtkScaleSetValuePos =
      gtk4Lookup<
            ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Int32)
            >
          >('gtk_scale_set_value_pos')
          .asFunction<void Function(ffi.Pointer<ffi.Void>, int)>();
  void setValuePos(GtkPositionType pos) {
    _gtkScaleSetValuePos(this.handle, pos.value);
  }

  /// Emitted before clamping a value, to give the application a
  /// chance to adjust the bounds.
  int onAdjustBounds(void Function(double value) callback) {
    return _connectSignal_v_1_d_double(this.handle, 'adjust-bounds', callback);
  }

  /// Emitted when a scroll action is performed on a range.
  ///
  /// It allows an application to determine the type of scroll event
  /// that occurred and the resultant new value. The application can
  /// handle the event itself and return %TRUE to prevent further
  /// processing. Or, by returning %FALSE, it can pass the event to
  /// other handlers until the default GTK handler is reached.
  ///
  /// The value parameter is unrounded. An application that overrides
  /// the ::change-value signal is responsible for clamping the value
  /// to the desired number of decimal digits; the default GTK
  /// handler clamps the value based on [property@Gtk.Range:round-digits].
  int onChangeValue(
    bool Function(GtkScrollType scroll, double value) callback,
  ) {
    return _connectSignal_b_2_i_d_gtkscrolltype_double(
      this.handle,
      'change-value',
      callback,
    );
  }

  /// Virtual function that moves the slider.
  ///
  /// Used for keybindings.
  int onMoveSlider(void Function(GtkScrollType step) callback) {
    return _connectSignal_v_1_i_gtkscrolltype(
      this.handle,
      'move-slider',
      callback,
    );
  }

  /// Emitted when the range value changes.
  int onValueChanged(void Function() callback) {
    return _connectSignal_v_0(this.handle, 'value-changed', callback);
  }

  /// Signals that all holders of a reference to the widget should release
  /// the reference that they hold.
  ///
  /// May result in finalization of the widget if all references are released.
  ///
  /// This signal is not suitable for saving widget state.
  int onDestroy(void Function() callback) {
    return _connectSignal_v_0(this.handle, 'destroy', callback);
  }

  /// Emitted when the text direction of a widget changes.
  int onDirectionChanged(
    void Function(GtkTextDirection previousDirection) callback,
  ) {
    return _connectSignal_v_1_i_gtktextdirection(
      this.handle,
      'direction-changed',
      callback,
    );
  }

  /// Emitted when @widget is hidden.
  int onHide(void Function() callback) {
    return _connectSignal_v_0(this.handle, 'hide', callback);
  }

  /// Emitted if keyboard navigation fails.
  ///
  /// See [method@Gtk.Widget.keynav_failed] for details.
  int onKeynavFailed(bool Function(GtkDirectionType direction) callback) {
    return _connectSignal_b_1_i_gtkdirectiontype(
      this.handle,
      'keynav-failed',
      callback,
    );
  }

  /// Emitted when @widget is going to be mapped.
  ///
  /// A widget is mapped when the widget is visible (which is controlled with
  /// [property@Gtk.Widget:visible]) and all its parents up to the toplevel widget
  /// are also visible.
  ///
  /// The `::map` signal can be used to determine whether a widget will be drawn,
  /// for instance it can resume an animation that was stopped during the
  /// emission of [signal@Gtk.Widget::unmap].
  int onMap(void Function() callback) {
    return _connectSignal_v_0(this.handle, 'map', callback);
  }

  /// Emitted when a widget is activated via a mnemonic.
  ///
  /// The default handler for this signal activates @widget if @group_cycling
  /// is false, or just makes @widget grab focus if @group_cycling is true.
  int onMnemonicActivate(bool Function(bool groupCycling) callback) {
    return _connectSignal_b_1_b_bool(
      this.handle,
      'mnemonic-activate',
      callback,
    );
  }

  /// Emitted when the focus is moved.
  ///
  /// The `::move-focus` signal is a [keybinding signal](class.SignalAction.html).
  ///
  /// The default bindings for this signal are <kbd>Tab</kbd> to move forward,
  /// and <kbd>Shift</kbd>+<kbd>Tab</kbd> to move backward.
  int onMoveFocus(void Function(GtkDirectionType direction) callback) {
    return _connectSignal_v_1_i_gtkdirectiontype(
      this.handle,
      'move-focus',
      callback,
    );
  }

  /// Emitted when the widget’s tooltip is about to be shown.
  ///
  /// This happens when the [property@Gtk.Widget:has-tooltip] property
  /// is true and the hover timeout has expired with the cursor hovering
  /// above @widget; or emitted when @widget got focus in keyboard mode.
  ///
  /// Using the given coordinates, the signal handler should determine
  /// whether a tooltip should be shown for @widget. If this is the case
  /// true should be returned, false otherwise. Note that if @keyboard_mode
  /// is true, the values of @x and @y are undefined and should not be used.
  ///
  /// The signal handler is free to manipulate @tooltip with the therefore
  /// destined function calls.
  int onQueryTooltip(
    bool Function(int x, int y, bool keyboardMode, GtkTooltip tooltip) callback,
  ) {
    return _connectSignal_b_4_i_i_b_o_int_int_bool_gtktooltip(
      this.handle,
      'query-tooltip',
      callback,
    );
  }

  /// Emitted when @widget is associated with a `GdkSurface`.
  ///
  /// This means that [method@Gtk.Widget.realize] has been called
  /// or the widget has been mapped (that is, it is going to be drawn).
  int onRealize(void Function() callback) {
    return _connectSignal_v_0(this.handle, 'realize', callback);
  }

  /// Emitted when @widget is shown.
  int onShow(void Function() callback) {
    return _connectSignal_v_0(this.handle, 'show', callback);
  }

  /// Emitted when the widget state changes.
  ///
  /// See [method@Gtk.Widget.get_state_flags].
  int onStateFlagsChanged(void Function(GtkStateFlags flags) callback) {
    return _connectSignal_v_1_u_gtkstateflags(
      this.handle,
      'state-flags-changed',
      callback,
    );
  }

  /// Emitted when @widget is going to be unmapped.
  ///
  /// A widget is unmapped when either it or any of its parents up to the
  /// toplevel widget have been set as hidden.
  ///
  /// As `::unmap` indicates that a widget will not be shown any longer,
  /// it can be used to, for example, stop an animation on the widget.
  int onUnmap(void Function() callback) {
    return _connectSignal_v_0(this.handle, 'unmap', callback);
  }

  /// Emitted when the `GdkSurface` associated with @widget is destroyed.
  ///
  /// This means that [method@Gtk.Widget.unrealize] has been called
  /// or the widget has been unmapped (that is, it is going to be hidden).
  int onUnrealize(void Function() callback) {
    return _connectSignal_v_0(this.handle, 'unrealize', callback);
  }

  /// The notify signal is emitted on an object when one of its properties has
  /// its value set through g_object_set_property(), g_object_set(), et al.
  ///
  /// Note that getting this signal doesn’t itself guarantee that the value of
  /// the property has actually changed. When it is emitted is determined by the
  /// derived GObject class. If the implementor did not create the property with
  /// %G_PARAM_EXPLICIT_NOTIFY, then any call to g_object_set_property() results
  /// in ::notify being emitted, even if the new value is the same as the old.
  /// If they did pass %G_PARAM_EXPLICIT_NOTIFY, then this signal is emitted only
  /// when they explicitly call g_object_notify() or g_object_notify_by_pspec(),
  /// and common practice is to do that only when the value has actually changed.
  ///
  /// This signal is typically used to obtain change notification for a
  /// single property, by specifying the property name as a detail in the
  /// g_signal_connect() call, like this:
  ///
  /// |[<!-- language="C" -->
  /// g_signal_connect (text_view->buffer, "notify::paste-target-list",
  /// G_CALLBACK (gtk_text_view_target_list_notify),
  /// text_view)
  /// ]|
  ///
  /// It is important to note that you must use
  /// [canonical parameter names][class@GObject.ParamSpec#parameter-names] as
  /// detail strings for the notify signal.
  int onNotify(void Function(GParamSpec pspec) callback) {
    return _connectSignal_v_1_o_gparamspec(this.handle, 'notify', callback);
  }
}
