// Generated by gir_generator. Do not edit.
part of '../gtk4.dart';

/// A `GtkWindow` subclass that integrates with `GtkApplication`.
///
/// Notably, `GtkApplicationWindow` can handle an application menubar.
///
/// This class implements the [iface@Gio.ActionGroup] and [iface@Gio.ActionMap]
/// interfaces, to let you add window-specific actions that will be exported
/// by the associated [class@Gtk.Application], together with its application-wide
/// actions. Window-specific actions are prefixed with the “win.”
/// prefix and application-wide actions are prefixed with the “app.”
/// prefix. Actions must be addressed with the prefixed name when
/// referring to them from a menu model.
///
/// Note that widgets that are placed inside a `GtkApplicationWindow`
/// can also activate these actions, if they implement the
/// [iface@Gtk.Actionable] interface.
///
/// The settings [property@Gtk.Settings:gtk-shell-shows-app-menu] and
/// [property@Gtk.Settings:gtk-shell-shows-menubar] tell GTK whether the
/// desktop environment is showing the application menu and menubar
/// models outside the application as part of the desktop shell.
/// For instance, on OS X, both menus will be displayed remotely;
/// on Windows neither will be.
///
/// If the desktop environment does not display the menubar, it can be shown in
/// the `GtkApplicationWindow` by setting the
/// [property@Gtk.ApplicationWindow:show-menubar] property to true. If the
/// desktop environment does not display the application menu, then it will
/// automatically be included in the menubar or in the window’s client-side
/// decorations.
///
/// See [class@Gtk.PopoverMenu] for information about the XML language
/// used by `GtkBuilder` for menu models.
///
/// See also: [method@Gtk.Application.set_menubar].
///
/// ## A GtkApplicationWindow with a menubar
///
/// The code sample below shows how to set up a `GtkApplicationWindow`
/// with a menu bar defined on the [class@Gtk.Application]:
///
/// ```c
/// GtkApplication *app = gtk_application_new ("org.gtk.test", 0);
///
/// GtkBuilder *builder = gtk_builder_new_from_string (
/// "<interface>"
/// "  <menu id='menubar'>"
/// "    <submenu>"
/// "      <attribute name='label' translatable='yes'>_Edit</attribute>"
/// "      <item>"
/// "        <attribute name='label' translatable='yes'>_Copy</attribute>"
/// "        <attribute name='action'>win.copy</attribute>"
/// "      </item>"
/// "      <item>"
/// "        <attribute name='label' translatable='yes'>_Paste</attribute>"
/// "        <attribute name='action'>win.paste</attribute>"
/// "      </item>"
/// "    </submenu>"
/// "  </menu>"
/// "</interface>",
/// -1);
///
/// GMenuModel *menubar = G_MENU_MODEL (gtk_builder_get_object (builder, "menubar"));
/// gtk_application_set_menubar (GTK_APPLICATION (app), menubar);
/// g_object_unref (builder);
///
/// // ...
///
/// GtkWidget *window = gtk_application_window_new (app);
/// ```
class GtkApplicationWindow extends GtkWindow {
  GtkApplicationWindow.fromPointer(super.handle, {super.owned})
    : super.fromPointer();

  /// Creates a new `GtkApplicationWindow`.
  static final _gtkApplicationWindowNew =
      gtk4Lookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)
            >
          >('gtk_application_window_new')
          .asFunction<ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)>();
  factory GtkApplicationWindow(GtkApplication application) {
    return GtkApplicationWindow.fromPointer(
      gObjectRefSink(_gtkApplicationWindowNew(application.handle)),
      owned: true,
    );
  }

  /// Gets the `GtkShortcutsWindow` that is associated with @window.
  ///
  /// See [method@Gtk.ApplicationWindow.set_help_overlay].
  static final _gtkApplicationWindowGetHelpOverlay =
      gtk4Lookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)
            >
          >('gtk_application_window_get_help_overlay')
          .asFunction<ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)>();
  GtkShortcutsWindow? getHelpOverlay() {
    return (_gtkApplicationWindowGetHelpOverlay(this.handle)) == ffi.nullptr
        ? null
        : GtkShortcutsWindow.fromPointer(
            _gtkApplicationWindowGetHelpOverlay(this.handle),
          );
  }

  /// Returns the unique ID of the window.
  ///
  /// If the window has not yet been added to a `GtkApplication`, returns `0`.
  static final _gtkApplicationWindowGetId =
      gtk4Lookup<
            ffi.NativeFunction<ffi.Uint32 Function(ffi.Pointer<ffi.Void>)>
          >('gtk_application_window_get_id')
          .asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  int getId() {
    return _gtkApplicationWindowGetId(this.handle);
  }

  /// Returns whether the window will display a menubar for the app menu
  /// and menubar as needed.
  static final _gtkApplicationWindowGetShowMenubar =
      gtk4Lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Void>)>>(
        'gtk_application_window_get_show_menubar',
      ).asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  bool getShowMenubar() {
    return (_gtkApplicationWindowGetShowMenubar(this.handle)) != 0;
  }

  /// Associates a shortcuts window with the application window.
  ///
  /// Additionally, sets up an action with the name
  /// `win.show-help-overlay` to present it.
  ///
  /// The window takes responsibility for destroying the help overlay.
  static final _gtkApplicationWindowSetHelpOverlay =
      gtk4Lookup<
            ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)
            >
          >('gtk_application_window_set_help_overlay')
          .asFunction<
            void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)
          >();
  void setHelpOverlay([GtkShortcutsWindow? helpOverlay]) {
    _gtkApplicationWindowSetHelpOverlay(
      this.handle,
      helpOverlay?.handle ?? ffi.nullptr,
    );
  }

  /// Sets whether the window will display a menubar for the app menu
  /// and menubar as needed.
  static final _gtkApplicationWindowSetShowMenubar =
      gtk4Lookup<
            ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Int32)
            >
          >('gtk_application_window_set_show_menubar')
          .asFunction<void Function(ffi.Pointer<ffi.Void>, int)>();
  void setShowMenubar(bool showMenubar) {
    _gtkApplicationWindowSetShowMenubar(this.handle, showMenubar ? 1 : 0);
  }

  /// Emitted when the user activates the default widget.
  ///
  /// This is a [keybinding signal](class.SignalAction.html).
  ///
  /// The keybindings for this signal are all forms of the <kbd>Enter</kbd> key.
  int onActivateDefault(void Function() callback) {
    return _connectSignal_v_0(this.handle, 'activate-default', callback);
  }

  /// Emitted when the user activates the currently focused
  /// widget of @window.
  ///
  /// This is a [keybinding signal](class.SignalAction.html).
  ///
  /// The default binding for this signal is <kbd>␣</kbd>.
  int onActivateFocus(void Function() callback) {
    return _connectSignal_v_0(this.handle, 'activate-focus', callback);
  }

  /// Emitted when the user clicks on the close button of the window.
  int onCloseRequest(bool Function() callback) {
    return _connectSignal_b_0(this.handle, 'close-request', callback);
  }

  /// Emitted when the user enables or disables interactive debugging.
  ///
  /// When @toggle is true, interactive debugging is toggled on or off,
  /// when it is false, the debugger will be pointed at the widget
  /// under the pointer.
  ///
  /// This is a [keybinding signal](class.SignalAction.html).
  ///
  /// The default bindings for this signal are
  /// <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd> and
  /// <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>D</kbd>.
  int onEnableDebugging(bool Function(bool toggle) callback) {
    return _connectSignal_b_1_b_bool(this.handle, 'enable-debugging', callback);
  }

  /// Emitted when the set of accelerators or mnemonics that
  /// are associated with the window changes.
  int onKeysChanged(void Function() callback) {
    return _connectSignal_v_0(this.handle, 'keys-changed', callback);
  }

  /// Signals that all holders of a reference to the widget should release
  /// the reference that they hold.
  ///
  /// May result in finalization of the widget if all references are released.
  ///
  /// This signal is not suitable for saving widget state.
  int onDestroy(void Function() callback) {
    return _connectSignal_v_0(this.handle, 'destroy', callback);
  }

  /// Emitted when the text direction of a widget changes.
  int onDirectionChanged(
    void Function(GtkTextDirection previousDirection) callback,
  ) {
    return _connectSignal_v_1_i_gtktextdirection(
      this.handle,
      'direction-changed',
      callback,
    );
  }

  /// Emitted when @widget is hidden.
  int onHide(void Function() callback) {
    return _connectSignal_v_0(this.handle, 'hide', callback);
  }

  /// Emitted if keyboard navigation fails.
  ///
  /// See [method@Gtk.Widget.keynav_failed] for details.
  int onKeynavFailed(bool Function(GtkDirectionType direction) callback) {
    return _connectSignal_b_1_i_gtkdirectiontype(
      this.handle,
      'keynav-failed',
      callback,
    );
  }

  /// Emitted when @widget is going to be mapped.
  ///
  /// A widget is mapped when the widget is visible (which is controlled with
  /// [property@Gtk.Widget:visible]) and all its parents up to the toplevel widget
  /// are also visible.
  ///
  /// The `::map` signal can be used to determine whether a widget will be drawn,
  /// for instance it can resume an animation that was stopped during the
  /// emission of [signal@Gtk.Widget::unmap].
  int onMap(void Function() callback) {
    return _connectSignal_v_0(this.handle, 'map', callback);
  }

  /// Emitted when a widget is activated via a mnemonic.
  ///
  /// The default handler for this signal activates @widget if @group_cycling
  /// is false, or just makes @widget grab focus if @group_cycling is true.
  int onMnemonicActivate(bool Function(bool toggle) callback) {
    return _connectSignal_b_1_b_bool(
      this.handle,
      'mnemonic-activate',
      callback,
    );
  }

  /// Emitted when the focus is moved.
  ///
  /// The `::move-focus` signal is a [keybinding signal](class.SignalAction.html).
  ///
  /// The default bindings for this signal are <kbd>Tab</kbd> to move forward,
  /// and <kbd>Shift</kbd>+<kbd>Tab</kbd> to move backward.
  int onMoveFocus(void Function(GtkDirectionType direction) callback) {
    return _connectSignal_v_1_i_gtkdirectiontype(
      this.handle,
      'move-focus',
      callback,
    );
  }

  /// Emitted when the widget’s tooltip is about to be shown.
  ///
  /// This happens when the [property@Gtk.Widget:has-tooltip] property
  /// is true and the hover timeout has expired with the cursor hovering
  /// above @widget; or emitted when @widget got focus in keyboard mode.
  ///
  /// Using the given coordinates, the signal handler should determine
  /// whether a tooltip should be shown for @widget. If this is the case
  /// true should be returned, false otherwise. Note that if @keyboard_mode
  /// is true, the values of @x and @y are undefined and should not be used.
  ///
  /// The signal handler is free to manipulate @tooltip with the therefore
  /// destined function calls.
  int onQueryTooltip(
    bool Function(int x, int y, bool keyboardMode, GtkTooltip tooltip) callback,
  ) {
    return _connectSignal_b_4_i_i_b_o_int_int_bool_gtktooltip(
      this.handle,
      'query-tooltip',
      callback,
    );
  }

  /// Emitted when @widget is associated with a `GdkSurface`.
  ///
  /// This means that [method@Gtk.Widget.realize] has been called
  /// or the widget has been mapped (that is, it is going to be drawn).
  int onRealize(void Function() callback) {
    return _connectSignal_v_0(this.handle, 'realize', callback);
  }

  /// Emitted when @widget is shown.
  int onShow(void Function() callback) {
    return _connectSignal_v_0(this.handle, 'show', callback);
  }

  /// Emitted when the widget state changes.
  ///
  /// See [method@Gtk.Widget.get_state_flags].
  int onStateFlagsChanged(void Function(GtkStateFlags flags) callback) {
    return _connectSignal_v_1_u_gtkstateflags(
      this.handle,
      'state-flags-changed',
      callback,
    );
  }

  /// Emitted when @widget is going to be unmapped.
  ///
  /// A widget is unmapped when either it or any of its parents up to the
  /// toplevel widget have been set as hidden.
  ///
  /// As `::unmap` indicates that a widget will not be shown any longer,
  /// it can be used to, for example, stop an animation on the widget.
  int onUnmap(void Function() callback) {
    return _connectSignal_v_0(this.handle, 'unmap', callback);
  }

  /// Emitted when the `GdkSurface` associated with @widget is destroyed.
  ///
  /// This means that [method@Gtk.Widget.unrealize] has been called
  /// or the widget has been unmapped (that is, it is going to be hidden).
  int onUnrealize(void Function() callback) {
    return _connectSignal_v_0(this.handle, 'unrealize', callback);
  }

  /// The notify signal is emitted on an object when one of its properties has
  /// its value set through g_object_set_property(), g_object_set(), et al.
  ///
  /// Note that getting this signal doesn’t itself guarantee that the value of
  /// the property has actually changed. When it is emitted is determined by the
  /// derived GObject class. If the implementor did not create the property with
  /// %G_PARAM_EXPLICIT_NOTIFY, then any call to g_object_set_property() results
  /// in ::notify being emitted, even if the new value is the same as the old.
  /// If they did pass %G_PARAM_EXPLICIT_NOTIFY, then this signal is emitted only
  /// when they explicitly call g_object_notify() or g_object_notify_by_pspec(),
  /// and common practice is to do that only when the value has actually changed.
  ///
  /// This signal is typically used to obtain change notification for a
  /// single property, by specifying the property name as a detail in the
  /// g_signal_connect() call, like this:
  ///
  /// |[<!-- language="C" -->
  /// g_signal_connect (text_view->buffer, "notify::paste-target-list",
  /// G_CALLBACK (gtk_text_view_target_list_notify),
  /// text_view)
  /// ]|
  ///
  /// It is important to note that you must use
  /// [canonical parameter names][class@GObject.ParamSpec#parameter-names] as
  /// detail strings for the notify signal.
  int onNotify(void Function(GParamSpec pspec) callback) {
    return _connectSignal_v_1_o_gparamspec(this.handle, 'notify', callback);
  }
}
