// Generated by gir_generator. Do not edit.
part of '../gtk4.dart';

/// Collects the arguments that are needed to present a message to the user.
///
/// The message is shown with the [method@Gtk.AlertDialog.choose]
/// function.
///
/// If you don't need to wait for a button to be clicked, you can use
/// [method@Gtk.AlertDialog.show].
class GtkAlertDialog extends GObject {
  GtkAlertDialog.fromPointer(super.handle, {super.owned}) : super.fromPointer();

  /// Shows the alert to the user.
  ///
  /// It is ok to pass `NULL` for the callback if the alert
  /// does not have more than one button. A simpler API for
  /// this case is [method@Gtk.AlertDialog.show].
  static final _gtkAlertDialogChoose =
      gtk4Lookup<
            ffi.NativeFunction<
              ffi.Void Function(
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<
                  ffi.NativeFunction<
                    ffi.Void Function(
                      ffi.Pointer<ffi.Void>,
                      ffi.Pointer<ffi.Void>,
                      ffi.Pointer<ffi.Void>,
                    )
                  >
                >,
                ffi.Pointer<ffi.Void>,
              )
            >
          >('gtk_alert_dialog_choose')
          .asFunction<
            void Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<
                ffi.NativeFunction<
                  ffi.Void Function(
                    ffi.Pointer<ffi.Void>,
                    ffi.Pointer<ffi.Void>,
                    ffi.Pointer<ffi.Void>,
                  )
                >
              >,
              ffi.Pointer<ffi.Void>,
            )
          >();
  void choose(
    GtkWindow? parent,
    GCancellable? cancellable,
    void Function(
      ffi.Pointer<ffi.Void>,
      ffi.Pointer<ffi.Void>,
      ffi.Pointer<ffi.Void>,
    )?
    callback,
    ffi.Pointer<ffi.Void> userData,
  ) {
    final _nc3 = callback == null
        ? null
        : ffi.NativeCallable<
            ffi.Void Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Void>,
            )
          >.isolateLocal(callback);
    try {
      _gtkAlertDialogChoose(
        this.handle,
        parent?.handle ?? ffi.nullptr,
        cancellable?.handle ?? ffi.nullptr,
        _nc3?.nativeFunction ?? ffi.nullptr,
        userData,
      );
    } finally {
      _nc3?.close();
    }
  }

  static final _chooseCallbackRegistry =
      <int, void Function(GObject?, GAsyncResult)>{};
  static int _chooseCallbackSeq = 0;
  static final _chooseCallbackPtr =
      ffi.Pointer.fromFunction<
        ffi.Void Function(
          ffi.Pointer<ffi.Void>,
          ffi.Pointer<ffi.Void>,
          ffi.Pointer<ffi.Void>,
        )
      >(_chooseCallbackTrampoline);
  static void _chooseCallbackTrampoline(
    ffi.Pointer<ffi.Void> sourceObject,
    ffi.Pointer<ffi.Void> res,
    ffi.Pointer<ffi.Void> data,
  ) {
    final id = data.cast<ffi.IntPtr>().value;
    final fn = _chooseCallbackRegistry.remove(id);
    malloc.free(data);
    if (fn == null) return;
    fn(
      sourceObject == ffi.nullptr
          ? null
          : GObject.fromPointer(sourceObject.cast()),
      GAsyncResult.fromPointer(res.cast()),
    );
  }

  /// Lifetime-safe variant of [choose] for use with
  /// async callbacks. See `docs/async.md`.
  void chooseCallback(
    GtkWindow? parent,
    GCancellable? cancellable,
    void Function(GObject?, GAsyncResult) callback,
  ) {
    final id = ++_chooseCallbackSeq;
    _chooseCallbackRegistry[id] = callback;
    final _data = malloc<ffi.IntPtr>()..value = id;
    _gtkAlertDialogChoose(
      this.handle,
      parent?.handle ?? ffi.nullptr,
      cancellable?.handle ?? ffi.nullptr,
      _chooseCallbackPtr,
      _data.cast<ffi.Void>(),
    );
  }

  /// Finishes the [method@Gtk.AlertDialog.choose] call.
  static final _gtkAlertDialogChooseFinish =
      gtk4Lookup<
            ffi.NativeFunction<
              ffi.Int32 Function(
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Pointer<ffi.Void>>,
              )
            >
          >('gtk_alert_dialog_choose_finish')
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Pointer<ffi.Void>>,
            )
          >();
  int chooseFinish(GAsyncResult result) {
    final _error = calloc<ffi.Pointer<ffi.Void>>();
    try {
      final _ret = _gtkAlertDialogChooseFinish(
        this.handle,
        result.handle,
        _error,
      );
      if (_error.value != ffi.nullptr) {
        throw GlibException.fromError(_error.value);
      }
      return _ret;
    } finally {
      calloc.free(_error);
    }
  }

  /// Returns the index of the cancel button.
  static final _gtkAlertDialogGetCancelButton =
      gtk4Lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Void>)>>(
        'gtk_alert_dialog_get_cancel_button',
      ).asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  int getCancelButton() {
    return _gtkAlertDialogGetCancelButton(this.handle);
  }

  /// Returns the index of the default button.
  static final _gtkAlertDialogGetDefaultButton =
      gtk4Lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Void>)>>(
        'gtk_alert_dialog_get_default_button',
      ).asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  int getDefaultButton() {
    return _gtkAlertDialogGetDefaultButton(this.handle);
  }

  /// Returns the detail text that will be shown in the alert.
  static final _gtkAlertDialogGetDetail =
      gtk4Lookup<
            ffi.NativeFunction<
              ffi.Pointer<Utf8> Function(ffi.Pointer<ffi.Void>)
            >
          >('gtk_alert_dialog_get_detail')
          .asFunction<ffi.Pointer<Utf8> Function(ffi.Pointer<ffi.Void>)>();
  String getDetail() {
    return stringFromNative(
      (_gtkAlertDialogGetDetail(this.handle)).cast(),
      free: false,
    )!;
  }

  /// Returns the message that will be shown in the alert.
  static final _gtkAlertDialogGetMessage =
      gtk4Lookup<
            ffi.NativeFunction<
              ffi.Pointer<Utf8> Function(ffi.Pointer<ffi.Void>)
            >
          >('gtk_alert_dialog_get_message')
          .asFunction<ffi.Pointer<Utf8> Function(ffi.Pointer<ffi.Void>)>();
  String getMessage() {
    return stringFromNative(
      (_gtkAlertDialogGetMessage(this.handle)).cast(),
      free: false,
    )!;
  }

  /// Returns whether the alert blocks interaction
  /// with the parent window while it is presented.
  static final _gtkAlertDialogGetModal =
      gtk4Lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Void>)>>(
        'gtk_alert_dialog_get_modal',
      ).asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  bool getModal() {
    return (_gtkAlertDialogGetModal(this.handle)) != 0;
  }

  /// Sets the button labels for the alert.
  static final _gtkAlertDialogSetButtons =
      gtk4Lookup<
            ffi.NativeFunction<
              ffi.Void Function(
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Pointer<Utf8>>,
              )
            >
          >('gtk_alert_dialog_set_buttons')
          .asFunction<
            void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Pointer<Utf8>>)
          >();
  void setButtons([List<String?>? labels]) {
    withNativeStringList(labels, (nativeLabels) {
      _gtkAlertDialogSetButtons(this.handle, nativeLabels);
    });
  }

  /// Sets the index of the cancel button.
  ///
  /// See [property@Gtk.AlertDialog:cancel-button] for
  /// details of how this value is used.
  static final _gtkAlertDialogSetCancelButton =
      gtk4Lookup<
            ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Int32)
            >
          >('gtk_alert_dialog_set_cancel_button')
          .asFunction<void Function(ffi.Pointer<ffi.Void>, int)>();
  void setCancelButton(int button) {
    _gtkAlertDialogSetCancelButton(this.handle, button);
  }

  /// Sets the index of the default button.
  ///
  /// See [property@Gtk.AlertDialog:default-button] for
  /// details of how this value is used.
  static final _gtkAlertDialogSetDefaultButton =
      gtk4Lookup<
            ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Int32)
            >
          >('gtk_alert_dialog_set_default_button')
          .asFunction<void Function(ffi.Pointer<ffi.Void>, int)>();
  void setDefaultButton(int button) {
    _gtkAlertDialogSetDefaultButton(this.handle, button);
  }

  /// Sets the detail text that will be shown in the alert.
  static final _gtkAlertDialogSetDetail =
      gtk4Lookup<
            ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<Utf8>)
            >
          >('gtk_alert_dialog_set_detail')
          .asFunction<
            void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<Utf8>)
          >();
  void setDetail(String detail) {
    withNativeString(detail, (nativeDetail) {
      _gtkAlertDialogSetDetail(this.handle, nativeDetail.cast<Utf8>());
    });
  }

  /// Sets the message that will be shown in the alert.
  static final _gtkAlertDialogSetMessage =
      gtk4Lookup<
            ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<Utf8>)
            >
          >('gtk_alert_dialog_set_message')
          .asFunction<
            void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<Utf8>)
          >();
  void setMessage(String message) {
    withNativeString(message, (nativeMessage) {
      _gtkAlertDialogSetMessage(this.handle, nativeMessage.cast<Utf8>());
    });
  }

  /// Sets whether the alert blocks interaction
  /// with the parent window while it is presented.
  static final _gtkAlertDialogSetModal =
      gtk4Lookup<
            ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Int32)
            >
          >('gtk_alert_dialog_set_modal')
          .asFunction<void Function(ffi.Pointer<ffi.Void>, int)>();
  void setModal(bool modal) {
    _gtkAlertDialogSetModal(this.handle, modal ? 1 : 0);
  }

  /// Shows the alert to the user.
  ///
  /// This function is a simpler version of [method@Gtk.AlertDialog.choose]
  /// intended for dialogs with a single button.
  ///
  /// If you want to cancel the dialog or if the alert has more than one
  /// button, you should use that function instead and provide it with a
  /// [class@Gio.Cancellable] and callback respectively.
  static final _gtkAlertDialogShow =
      gtk4Lookup<
            ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)
            >
          >('gtk_alert_dialog_show')
          .asFunction<
            void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)
          >();
  void show_([GtkWindow? parent]) {
    _gtkAlertDialogShow(this.handle, parent?.handle ?? ffi.nullptr);
  }

  /// The notify signal is emitted on an object when one of its properties has
  /// its value set through g_object_set_property(), g_object_set(), et al.
  ///
  /// Note that getting this signal doesn’t itself guarantee that the value of
  /// the property has actually changed. When it is emitted is determined by the
  /// derived GObject class. If the implementor did not create the property with
  /// %G_PARAM_EXPLICIT_NOTIFY, then any call to g_object_set_property() results
  /// in ::notify being emitted, even if the new value is the same as the old.
  /// If they did pass %G_PARAM_EXPLICIT_NOTIFY, then this signal is emitted only
  /// when they explicitly call g_object_notify() or g_object_notify_by_pspec(),
  /// and common practice is to do that only when the value has actually changed.
  ///
  /// This signal is typically used to obtain change notification for a
  /// single property, by specifying the property name as a detail in the
  /// g_signal_connect() call, like this:
  ///
  /// |[<!-- language="C" -->
  /// g_signal_connect (text_view->buffer, "notify::paste-target-list",
  /// G_CALLBACK (gtk_text_view_target_list_notify),
  /// text_view)
  /// ]|
  ///
  /// It is important to note that you must use
  /// [canonical parameter names][class@GObject.ParamSpec#parameter-names] as
  /// detail strings for the notify signal.
  int onNotify(void Function(GParamSpec pspec) callback) {
    return _connectSignal_v_1_o_gparamspec(this.handle, 'notify', callback);
  }
}

/// Combines two shortcut triggers.
///
/// The `GtkAlternativeTrigger` triggers when either of the two trigger.
///
/// This can be cascaded to combine more than two triggers.
class GtkAlternativeTrigger extends GtkShortcutTrigger {
  GtkAlternativeTrigger.fromPointer(super.handle, {super.owned})
    : super.fromPointer();

  /// Creates a `GtkShortcutTrigger` that will trigger whenever
  /// either of the two given triggers gets triggered.
  ///
  /// Note that nesting is allowed, so if you want more than two
  /// alternative, create a new alternative trigger for each option.
  static final _gtkAlternativeTriggerNew =
      gtk4Lookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<ffi.Void>,
              )
            >
          >('gtk_alternative_trigger_new')
          .asFunction<
            ffi.Pointer<ffi.Void> Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Void>,
            )
          >();
  factory GtkAlternativeTrigger(
    GtkShortcutTrigger first,
    GtkShortcutTrigger second,
  ) {
    return GtkAlternativeTrigger.fromPointer(
      _gtkAlternativeTriggerNew(first.handle, second.handle),
      owned: true,
    );
  }

  /// Gets the first of the two alternative triggers that may
  /// trigger @self.
  ///
  /// [method@Gtk.AlternativeTrigger.get_second] will return
  /// the other one.
  static final _gtkAlternativeTriggerGetFirst =
      gtk4Lookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)
            >
          >('gtk_alternative_trigger_get_first')
          .asFunction<ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)>();
  GtkShortcutTrigger getFirst() {
    return GtkShortcutTrigger.fromPointer(
      _gtkAlternativeTriggerGetFirst(this.handle),
    );
  }

  /// Gets the second of the two alternative triggers that may
  /// trigger @self.
  ///
  /// [method@Gtk.AlternativeTrigger.get_first] will return
  /// the other one.
  static final _gtkAlternativeTriggerGetSecond =
      gtk4Lookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)
            >
          >('gtk_alternative_trigger_get_second')
          .asFunction<ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)>();
  GtkShortcutTrigger getSecond() {
    return GtkShortcutTrigger.fromPointer(
      _gtkAlternativeTriggerGetSecond(this.handle),
    );
  }

  /// The notify signal is emitted on an object when one of its properties has
  /// its value set through g_object_set_property(), g_object_set(), et al.
  ///
  /// Note that getting this signal doesn’t itself guarantee that the value of
  /// the property has actually changed. When it is emitted is determined by the
  /// derived GObject class. If the implementor did not create the property with
  /// %G_PARAM_EXPLICIT_NOTIFY, then any call to g_object_set_property() results
  /// in ::notify being emitted, even if the new value is the same as the old.
  /// If they did pass %G_PARAM_EXPLICIT_NOTIFY, then this signal is emitted only
  /// when they explicitly call g_object_notify() or g_object_notify_by_pspec(),
  /// and common practice is to do that only when the value has actually changed.
  ///
  /// This signal is typically used to obtain change notification for a
  /// single property, by specifying the property name as a detail in the
  /// g_signal_connect() call, like this:
  ///
  /// |[<!-- language="C" -->
  /// g_signal_connect (text_view->buffer, "notify::paste-target-list",
  /// G_CALLBACK (gtk_text_view_target_list_notify),
  /// text_view)
  /// ]|
  ///
  /// It is important to note that you must use
  /// [canonical parameter names][class@GObject.ParamSpec#parameter-names] as
  /// detail strings for the notify signal.
  int onNotify(void Function(GParamSpec pspec) callback) {
    return _connectSignal_v_1_o_gparamspec(this.handle, 'notify', callback);
  }
}

/// Matches an item when at least one of its filters matches.
///
/// To add filters to a `GtkAnyFilter`, use [method@Gtk.MultiFilter.append].
class GtkAnyFilter extends GtkMultiFilter {
  GtkAnyFilter.fromPointer(super.handle, {super.owned}) : super.fromPointer();

  /// Creates a new empty "any" filter.
  ///
  /// Use [method@Gtk.MultiFilter.append] to add filters to it.
  ///
  /// This filter matches an item if any of the filters added to it
  /// matches the item. In particular, this means that if no filter
  /// has been added to it, the filter matches no item.
  static final _gtkAnyFilterNew =
      gtk4Lookup<ffi.NativeFunction<ffi.Pointer<ffi.Void> Function()>>(
        'gtk_any_filter_new',
      ).asFunction<ffi.Pointer<ffi.Void> Function()>();
  factory GtkAnyFilter() {
    return GtkAnyFilter.fromPointer(_gtkAnyFilterNew(), owned: true);
  }

  /// Emitted whenever the filter changed.
  ///
  /// Users of the filter should then check items again via
  /// [method@Gtk.Filter.match].
  ///
  /// `GtkFilterListModel` handles this signal automatically.
  ///
  /// Depending on the @change parameter, not all items need
  /// to be checked, but only some. Refer to the [enum@Gtk.FilterChange]
  /// documentation for details.
  int onChanged(void Function(GtkFilterChange change) callback) {
    return _connectSignal_v_1_i_gtkfilterchange(
      this.handle,
      'changed',
      callback,
    );
  }

  /// The notify signal is emitted on an object when one of its properties has
  /// its value set through g_object_set_property(), g_object_set(), et al.
  ///
  /// Note that getting this signal doesn’t itself guarantee that the value of
  /// the property has actually changed. When it is emitted is determined by the
  /// derived GObject class. If the implementor did not create the property with
  /// %G_PARAM_EXPLICIT_NOTIFY, then any call to g_object_set_property() results
  /// in ::notify being emitted, even if the new value is the same as the old.
  /// If they did pass %G_PARAM_EXPLICIT_NOTIFY, then this signal is emitted only
  /// when they explicitly call g_object_notify() or g_object_notify_by_pspec(),
  /// and common practice is to do that only when the value has actually changed.
  ///
  /// This signal is typically used to obtain change notification for a
  /// single property, by specifying the property name as a detail in the
  /// g_signal_connect() call, like this:
  ///
  /// |[<!-- language="C" -->
  /// g_signal_connect (text_view->buffer, "notify::paste-target-list",
  /// G_CALLBACK (gtk_text_view_target_list_notify),
  /// text_view)
  /// ]|
  ///
  /// It is important to note that you must use
  /// [canonical parameter names][class@GObject.ParamSpec#parameter-names] as
  /// detail strings for the notify signal.
  int onNotify(void Function(GParamSpec pspec) callback) {
    return _connectSignal_v_1_o_gparamspec(this.handle, 'notify', callback);
  }

  /// Gets the type of the items in @list.
  ///
  /// All items returned from g_list_model_get_item() are of the type
  /// returned by this function, or a subtype, or if the type is an
  /// interface, they are an implementation of that interface.
  ///
  /// The item type of a #GListModel can not change during the life of the
  /// model.
  static final _gListModelGetItemType =
      gtk4Lookup<ffi.NativeFunction<ffi.Size Function(ffi.Pointer<ffi.Void>)>>(
        'g_list_model_get_item_type',
      ).asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  int getItemType() {
    return _gListModelGetItemType(this.handle);
  }

  /// Gets the number of items in @list.
  ///
  /// Depending on the model implementation, calling this function may be
  /// less efficient than iterating the list with increasing values for
  /// @position until g_list_model_get_item() returns %NULL.
  static final _gListModelGetNItems =
      gtk4Lookup<
            ffi.NativeFunction<ffi.Uint32 Function(ffi.Pointer<ffi.Void>)>
          >('g_list_model_get_n_items')
          .asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  int getNItems() {
    return _gListModelGetNItems(this.handle);
  }

  /// Get the item at @position.
  ///
  /// If @position is greater than the number of items in @list, %NULL is
  /// returned.
  ///
  /// %NULL is never returned for an index that is smaller than the length
  /// of the list.
  ///
  /// This function is meant to be used by language bindings in place
  /// of g_list_model_get_item().
  ///
  /// See also: g_list_model_get_n_items()
  static final _gListModelGetObject =
      gtk4Lookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>, ffi.Uint32)
            >
          >('g_list_model_get_object')
          .asFunction<
            ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>, int)
          >();
  GObject? getObject(int position) {
    return (_gListModelGetObject(this.handle, position)) == ffi.nullptr
        ? null
        : GObject.fromPointer(_gListModelGetObject(this.handle, position));
  }

  /// Emits the #GListModel::items-changed signal on @list.
  ///
  /// This function should only be called by classes implementing
  /// #GListModel. It has to be called after the internal representation
  /// of @list has been updated, because handlers connected to this signal
  /// might query the new state of the list.
  ///
  /// Implementations must only make changes to the model (as visible to
  /// its consumer) in places that will not cause problems for that
  /// consumer.  For models that are driven directly by a write API (such
  /// as #GListStore), changes can be reported in response to uses of that
  /// API.  For models that represent remote data, changes should only be
  /// made from a fresh mainloop dispatch.  It is particularly not
  /// permitted to make changes in response to a call to the #GListModel
  /// consumer API.
  ///
  /// Stated another way: in general, it is assumed that code making a
  /// series of accesses to the model via the API, without returning to the
  /// mainloop, and without calling other code, will continue to view the
  /// same contents of the model.
  static final _gListModelItemsChanged =
      gtk4Lookup<
            ffi.NativeFunction<
              ffi.Void Function(
                ffi.Pointer<ffi.Void>,
                ffi.Uint32,
                ffi.Uint32,
                ffi.Uint32,
              )
            >
          >('g_list_model_items_changed')
          .asFunction<void Function(ffi.Pointer<ffi.Void>, int, int, int)>();
  void itemsChanged(int position, int removed, int added) {
    _gListModelItemsChanged(this.handle, position, removed, added);
  }

  /// Gets the ID of the @buildable object.
  ///
  /// `GtkBuilder` sets the name based on the ID attribute
  /// of the `<object>` tag used to construct the @buildable.
  static final _gtkBuildableGetBuildableId =
      gtk4Lookup<
            ffi.NativeFunction<
              ffi.Pointer<Utf8> Function(ffi.Pointer<ffi.Void>)
            >
          >('gtk_buildable_get_buildable_id')
          .asFunction<ffi.Pointer<Utf8> Function(ffi.Pointer<ffi.Void>)>();
  String? getBuildableId() {
    return stringFromNative(
      (_gtkBuildableGetBuildableId(this.handle)).cast(),
      free: false,
    );
  }
}
