// Generated by gir_generator. Do not edit.
part of '../gtk4.dart';

/// Shows window frame controls.
///
/// Typical window frame controls are minimize, maximize and close buttons,
/// and the window icon.
///
/// <picture>
/// <source srcset="windowcontrols-dark.png" media="(prefers-color-scheme: dark)">
/// <img alt="An example GtkWindowControls" src="windowcontrols.png">
/// </picture>
///
/// `GtkWindowControls` only displays start or end side of the controls (see
/// [property@Gtk.WindowControls:side]), so it's intended to be always used
/// in pair with another `GtkWindowControls` for the opposite side, for example:
///
/// ```xml
/// <object class="GtkBox">
/// <child>
/// <object class="GtkWindowControls">
/// <property name="side">start</property>
/// </object>
/// </child>
///
/// ...
///
/// <child>
/// <object class="GtkWindowControls">
/// <property name="side">end</property>
/// </object>
/// </child>
/// </object>
/// ```
///
/// # CSS nodes
///
/// ```
/// windowcontrols
/// ├── [image.icon]
/// ├── [button.minimize]
/// ├── [button.maximize]
/// ╰── [button.close]
/// ```
///
/// A `GtkWindowControls`' CSS node is called windowcontrols. It contains
/// subnodes corresponding to each title button. Which of the title buttons
/// exist and where they are placed exactly depends on the desktop environment
/// and [property@Gtk.WindowControls:decoration-layout] value.
///
/// When [property@Gtk.WindowControls:empty] is true, it gets the .empty
/// style class.
///
/// # Accessibility
///
/// `GtkWindowControls` uses the [enum@Gtk.AccessibleRole.group] role.
class GtkWindowControls extends GtkWidget {
  GtkWindowControls.fromPointer(super.handle, {super.owned})
    : super.fromPointer();

  /// Creates a new `GtkWindowControls`.
  static final _gtkWindowControlsNew =
      gtk4Lookup<ffi.NativeFunction<ffi.Pointer<ffi.Void> Function(ffi.Int32)>>(
        'gtk_window_controls_new',
      ).asFunction<ffi.Pointer<ffi.Void> Function(int)>();
  factory GtkWindowControls(GtkPackType side) {
    return GtkWindowControls.fromPointer(
      gObjectRefSink(_gtkWindowControlsNew(side.value)),
      owned: true,
    );
  }

  /// Gets the decoration layout of this window controls widget
  static final _gtkWindowControlsGetDecorationLayout =
      gtk4Lookup<
            ffi.NativeFunction<
              ffi.Pointer<Utf8> Function(ffi.Pointer<ffi.Void>)
            >
          >('gtk_window_controls_get_decoration_layout')
          .asFunction<ffi.Pointer<Utf8> Function(ffi.Pointer<ffi.Void>)>();
  String? getDecorationLayout() {
    return stringFromNative(
      (_gtkWindowControlsGetDecorationLayout(this.handle)).cast(),
      free: false,
    );
  }

  /// Gets whether the widget has any window buttons.
  static final _gtkWindowControlsGetEmpty =
      gtk4Lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Void>)>>(
        'gtk_window_controls_get_empty',
      ).asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  bool getEmpty() {
    return (_gtkWindowControlsGetEmpty(this.handle)) != 0;
  }

  /// Gets the side to which this window controls widget belongs.
  static final _gtkWindowControlsGetSide =
      gtk4Lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Void>)>>(
        'gtk_window_controls_get_side',
      ).asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  GtkPackType getSide() {
    return GtkPackType.fromValue(_gtkWindowControlsGetSide(this.handle));
  }

  /// Returns whether platform native window controls are shown.
  static final _gtkWindowControlsGetUseNativeControls =
      gtk4Lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Void>)>>(
        'gtk_window_controls_get_use_native_controls',
      ).asFunction<int Function(ffi.Pointer<ffi.Void>)>();
  bool getUseNativeControls() {
    return (_gtkWindowControlsGetUseNativeControls(this.handle)) != 0;
  }

  /// Sets the decoration layout for the title buttons.
  ///
  /// This overrides the [property@Gtk.Settings:gtk-decoration-layout]
  /// setting.
  ///
  /// The format of the string is button names, separated by commas.
  /// A colon separates the buttons that should appear on the left
  /// from those on the right. Recognized button names are minimize,
  /// maximize, close and icon (the window icon).
  ///
  /// For example, “icon:minimize,maximize,close” specifies a icon
  /// on the left, and minimize, maximize and close buttons on the right.
  ///
  /// If [property@Gtk.WindowControls:side] value is [enum@Gtk.PackType.start],
  /// @self will display the part before the colon, otherwise after that.
  static final _gtkWindowControlsSetDecorationLayout =
      gtk4Lookup<
            ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<Utf8>)
            >
          >('gtk_window_controls_set_decoration_layout')
          .asFunction<
            void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<Utf8>)
          >();
  void setDecorationLayout([String? layout]) {
    withNativeString(layout, (nativeLayout) {
      _gtkWindowControlsSetDecorationLayout(
        this.handle,
        nativeLayout.cast<Utf8>(),
      );
    });
  }

  /// Determines which part of decoration layout
  /// the window controls widget uses.
  ///
  /// See [property@Gtk.WindowControls:decoration-layout].
  static final _gtkWindowControlsSetSide =
      gtk4Lookup<
            ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Int32)
            >
          >('gtk_window_controls_set_side')
          .asFunction<void Function(ffi.Pointer<ffi.Void>, int)>();
  void setSide(GtkPackType side) {
    _gtkWindowControlsSetSide(this.handle, side.value);
  }

  /// Sets whether platform native window controls are used.
  ///
  /// This option shows the "stoplight" buttons on macOS.
  /// For Linux, this option has no effect.
  ///
  /// See also [Using GTK on Apple macOS](osx.html?native-window-controls).
  static final _gtkWindowControlsSetUseNativeControls =
      gtk4Lookup<
            ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Int32)
            >
          >('gtk_window_controls_set_use_native_controls')
          .asFunction<void Function(ffi.Pointer<ffi.Void>, int)>();
  void setUseNativeControls(bool setting) {
    _gtkWindowControlsSetUseNativeControls(this.handle, setting ? 1 : 0);
  }
}

/// Creates groups of windows that behave like separate applications.
///
/// It achieves this by limiting the effect of GTK grabs and modality
/// to windows in the same group.
///
/// A window can be a member in at most one window group at a time.
/// Windows that have not been explicitly assigned to a group are
/// implicitly treated like windows of the default window group.
///
/// `GtkWindowGroup` objects are referenced by each window in the group,
/// so once you have added all windows to a `GtkWindowGroup`, you can drop
/// the initial reference to the window group with g_object_unref(). If the
/// windows in the window group are subsequently destroyed, then they will
/// be removed from the window group and drop their references on the window
/// group; when all window have been removed, the window group will be
/// freed.
class GtkWindowGroup implements ffi.Finalizable {
  GtkWindowGroup.fromPointer(this.handle, {this.owned = false}) {
    if (owned) {
      _attachFinalizer();
    }
  }
  final ffi.Pointer<ffi.Void> handle;
  final bool owned;
  void _attachFinalizer() =>
      gobjectFinalizer.attach(this, handle, detach: this);

  /// Creates a new `GtkWindowGroup` object.
  ///
  /// Modality of windows only affects windows
  /// within the same `GtkWindowGroup`.
  static final _gtkWindowGroupNew =
      gtk4Lookup<ffi.NativeFunction<ffi.Pointer<ffi.Void> Function()>>(
        'gtk_window_group_new',
      ).asFunction<ffi.Pointer<ffi.Void> Function()>();
  factory GtkWindowGroup() {
    return GtkWindowGroup.fromPointer(_gtkWindowGroupNew(), owned: true);
  }

  /// Adds a window to a `GtkWindowGroup`.
  static final _gtkWindowGroupAddWindow =
      gtk4Lookup<
            ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)
            >
          >('gtk_window_group_add_window')
          .asFunction<
            void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)
          >();
  void addWindow(GtkWindow window) {
    _gtkWindowGroupAddWindow(this.handle, window.handle);
  }

  /// Removes a window from a `GtkWindowGroup`.
  static final _gtkWindowGroupRemoveWindow =
      gtk4Lookup<
            ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)
            >
          >('gtk_window_group_remove_window')
          .asFunction<
            void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)
          >();
  void removeWindow(GtkWindow window) {
    _gtkWindowGroupRemoveWindow(this.handle, window.handle);
  }
}

/// Implements titlebar functionality for a window.
///
/// When added into a window, it can be dragged to move the window,
/// and it implements the right click, double click and middle click
/// behaviors that are expected of a titlebar.
///
/// # CSS nodes
///
/// `GtkWindowHandle` has a single CSS node with the name `windowhandle`.
///
/// # Accessibility
///
/// Until GTK 4.10, `GtkWindowHandle` used the [enum@Gtk.AccessibleRole.group] role.
///
/// Starting from GTK 4.12, `GtkWindowHandle` uses the [enum@Gtk.AccessibleRole.generic]
/// role.
class GtkWindowHandle extends GtkWidget {
  GtkWindowHandle.fromPointer(super.handle, {super.owned})
    : super.fromPointer();

  /// Creates a new `GtkWindowHandle`.
  static final _gtkWindowHandleNew =
      gtk4Lookup<ffi.NativeFunction<ffi.Pointer<ffi.Void> Function()>>(
        'gtk_window_handle_new',
      ).asFunction<ffi.Pointer<ffi.Void> Function()>();
  factory GtkWindowHandle() {
    return GtkWindowHandle.fromPointer(
      gObjectRefSink(_gtkWindowHandleNew()),
      owned: true,
    );
  }

  /// Gets the child widget of @self.
  static final _gtkWindowHandleGetChild =
      gtk4Lookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)
            >
          >('gtk_window_handle_get_child')
          .asFunction<ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)>();
  GtkWidget? getChild() {
    return (_gtkWindowHandleGetChild(this.handle)) == ffi.nullptr
        ? null
        : GtkWidget.fromPointer(_gtkWindowHandleGetChild(this.handle));
  }

  /// Sets the child widget of @self.
  static final _gtkWindowHandleSetChild =
      gtk4Lookup<
            ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)
            >
          >('gtk_window_handle_set_child')
          .asFunction<
            void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)
          >();
  void setChild([GtkWidget? child]) {
    _gtkWindowHandleSetChild(this.handle, child?.handle ?? ffi.nullptr);
  }
}
