// Generated by gir_generator. Do not edit.
part of '../gtk4.dart';

/// A list model that concatenates other list models.
///
/// `GtkFlattenListModel` takes a list model containing list models, and flattens
/// it into a single model. Each list model becomes a section in the single model.
class GtkFlattenListModel extends GObject {
  GtkFlattenListModel.fromPointer(super.handle, {super.owned})
    : super.fromPointer();

  /// Creates a new `GtkFlattenListModel` that flattens @list.
  static final _gtkFlattenListModelNew =
      gtk4Lookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)
            >
          >('gtk_flatten_list_model_new')
          .asFunction<ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)>();
  factory GtkFlattenListModel([GListModel? model]) {
    return GtkFlattenListModel.fromPointer(
      _gtkFlattenListModelNew(model?.handle ?? ffi.nullptr),
      owned: true,
    );
  }

  /// Gets the model set via gtk_flatten_list_model_set_model().
  static final _gtkFlattenListModelGetModel =
      gtk4Lookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)
            >
          >('gtk_flatten_list_model_get_model')
          .asFunction<ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)>();
  GListModel? getModel() {
    return (_gtkFlattenListModelGetModel(this.handle)) == ffi.nullptr
        ? null
        : GListModel.fromPointer(_gtkFlattenListModelGetModel(this.handle));
  }

  /// Returns the model containing the item at the given position.
  static final _gtkFlattenListModelGetModelForItem =
      gtk4Lookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>, ffi.Uint32)
            >
          >('gtk_flatten_list_model_get_model_for_item')
          .asFunction<
            ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>, int)
          >();
  GListModel? getModelForItem(int position) {
    return (_gtkFlattenListModelGetModelForItem(this.handle, position)) ==
            ffi.nullptr
        ? null
        : GListModel.fromPointer(
            _gtkFlattenListModelGetModelForItem(this.handle, position),
          );
  }

  /// Sets a new model to be flattened.
  static final _gtkFlattenListModelSetModel =
      gtk4Lookup<
            ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)
            >
          >('gtk_flatten_list_model_set_model')
          .asFunction<
            void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)
          >();
  void setModel([GListModel? model]) {
    _gtkFlattenListModelSetModel(this.handle, model?.handle ?? ffi.nullptr);
  }

  /// The notify signal is emitted on an object when one of its properties has
  /// its value set through g_object_set_property(), g_object_set(), et al.
  ///
  /// Note that getting this signal doesn’t itself guarantee that the value of
  /// the property has actually changed. When it is emitted is determined by the
  /// derived GObject class. If the implementor did not create the property with
  /// %G_PARAM_EXPLICIT_NOTIFY, then any call to g_object_set_property() results
  /// in ::notify being emitted, even if the new value is the same as the old.
  /// If they did pass %G_PARAM_EXPLICIT_NOTIFY, then this signal is emitted only
  /// when they explicitly call g_object_notify() or g_object_notify_by_pspec(),
  /// and common practice is to do that only when the value has actually changed.
  ///
  /// This signal is typically used to obtain change notification for a
  /// single property, by specifying the property name as a detail in the
  /// g_signal_connect() call, like this:
  ///
  /// |[<!-- language="C" -->
  /// g_signal_connect (text_view->buffer, "notify::paste-target-list",
  /// G_CALLBACK (gtk_text_view_target_list_notify),
  /// text_view)
  /// ]|
  ///
  /// It is important to note that you must use
  /// [canonical parameter names][class@GObject.ParamSpec#parameter-names] as
  /// detail strings for the notify signal.
  int onNotify(void Function(GParamSpec pspec) callback) {
    return _connectSignal_v_1_o_gparamspec(this.handle, 'notify', callback);
  }
}
