// Generated by gir_generator. Do not edit.
part of '../gtk4.dart';

/// PyGObject-style typed property accessor. Each getter
/// and setter delegates to the existing typed
/// `get<Name>` / `set<Name>` methods on [GtkBuilderListItemFactory].
///
/// Skipped properties (unsupported type, missing getter
/// or setter) are recorded in the generation report.
class GtkBuilderListItemFactoryProps {
  GtkBuilderListItemFactoryProps(this._self);
  final GtkBuilderListItemFactory _self;

  GBytes get bytes => _self.getBytes();

  String? get resource => _self.getResource();

  GtkBuilderScope? get scope => _self.getScope();
}
