// Generated by gir_generator. Do not edit.
part of '../gtk4.dart';

/// PyGObject-style typed property accessor. Each getter
/// and setter delegates to the existing typed
/// `get<Name>` / `set<Name>` methods on [GtkComboBoxText].
///
/// Skipped properties (unsupported type, missing getter
/// or setter) are recorded in the generation report.
class GtkComboBoxTextProps extends GtkComboBoxProps {
  GtkComboBoxTextProps(GtkComboBoxText $self) : _self = $self, super($self);
  final GtkComboBoxText _self;

  int get active => _self.getActive();
  set active(int value) {
    _self.setActive(value);
  }

  String? get activeId => _self.getActiveId();
  set activeId(String? value) {
    _self.setActiveId(value);
  }

  GtkSensitivityType get buttonSensitivity => _self.getButtonSensitivity();
  set buttonSensitivity(GtkSensitivityType value) {
    _self.setButtonSensitivity(value);
  }

  GtkWidget? get child => _self.getChild();
  set child(GtkWidget? value) {
    _self.setChild(value);
  }

  int get entryTextColumn => _self.getEntryTextColumn();
  set entryTextColumn(int value) {
    _self.setEntryTextColumn(value);
  }

  bool get hasEntry => _self.getHasEntry();

  int get idColumn => _self.getIdColumn();
  set idColumn(int value) {
    _self.setIdColumn(value);
  }

  GtkTreeModel? get model => _self.getModel();
  set model(GtkTreeModel? value) {
    _self.setModel(value);
  }

  bool get popupFixedWidth => _self.getPopupFixedWidth();
  set popupFixedWidth(bool value) {
    _self.setPopupFixedWidth(value);
  }

  bool get canFocus => _self.getCanFocus();
  set canFocus(bool value) {
    _self.setCanFocus(value);
  }

  bool get canTarget => _self.getCanTarget();
  set canTarget(bool value) {
    _self.setCanTarget(value);
  }

  String get cssName => _self.getCssName();

  GdkCursor? get cursor => _self.getCursor();
  set cursor(GdkCursor? value) {
    _self.setCursor(value);
  }

  bool get focusOnClick => _self.getFocusOnClick();
  set focusOnClick(bool value) {
    _self.setFocusOnClick(value);
  }

  bool get focusable => _self.getFocusable();
  set focusable(bool value) {
    _self.setFocusable(value);
  }

  GtkAlign get halign => _self.getHalign();
  set halign(GtkAlign value) {
    _self.setHalign(value);
  }

  bool get hasDefault => _self.hasDefault();

  bool get hasFocus => _self.hasFocus();

  bool get hasTooltip => _self.getHasTooltip();
  set hasTooltip(bool value) {
    _self.setHasTooltip(value);
  }

  bool get hexpand => _self.getHexpand();
  set hexpand(bool value) {
    _self.setHexpand(value);
  }

  bool get hexpandSet => _self.getHexpandSet();
  set hexpandSet(bool value) {
    _self.setHexpandSet(value);
  }

  GtkLayoutManager? get layoutManager => _self.getLayoutManager();
  set layoutManager(GtkLayoutManager? value) {
    _self.setLayoutManager(value);
  }

  bool get limitEvents => _self.getLimitEvents();
  set limitEvents(bool value) {
    _self.setLimitEvents(value);
  }

  int get marginBottom => _self.getMarginBottom();
  set marginBottom(int value) {
    _self.setMarginBottom(value);
  }

  int get marginEnd => _self.getMarginEnd();
  set marginEnd(int value) {
    _self.setMarginEnd(value);
  }

  int get marginStart => _self.getMarginStart();
  set marginStart(int value) {
    _self.setMarginStart(value);
  }

  int get marginTop => _self.getMarginTop();
  set marginTop(int value) {
    _self.setMarginTop(value);
  }

  String get name => _self.getName();
  set name(String value) {
    _self.setName(value);
  }

  double get opacity => _self.getOpacity();
  set opacity(double value) {
    _self.setOpacity(value);
  }

  GtkOverflow get overflow => _self.getOverflow();
  set overflow(GtkOverflow value) {
    _self.setOverflow(value);
  }

  GtkWidget? get parent => _self.getParent();

  bool get receivesDefault => _self.getReceivesDefault();
  set receivesDefault(bool value) {
    _self.setReceivesDefault(value);
  }

  GtkRoot? get root => _self.getRoot();

  int get scaleFactor => _self.getScaleFactor();

  bool get sensitive => _self.getSensitive();
  set sensitive(bool value) {
    _self.setSensitive(value);
  }

  String? get tooltipMarkup => _self.getTooltipMarkup();
  set tooltipMarkup(String? value) {
    _self.setTooltipMarkup(value);
  }

  String? get tooltipText => _self.getTooltipText();
  set tooltipText(String? value) {
    _self.setTooltipText(value);
  }

  GtkAlign get valign => _self.getValign();
  set valign(GtkAlign value) {
    _self.setValign(value);
  }

  bool get vexpand => _self.getVexpand();
  set vexpand(bool value) {
    _self.setVexpand(value);
  }

  bool get vexpandSet => _self.getVexpandSet();
  set vexpandSet(bool value) {
    _self.setVexpandSet(value);
  }

  bool get visible => _self.getVisible();
  set visible(bool value) {
    _self.setVisible(value);
  }
}
