// Generated by gir_generator. Do not edit.
part of '../gtk4.dart';

/// Invokes a callback.
class GtkCallbackAction extends GtkShortcutAction {
  GtkCallbackAction.fromPointer(super.handle, {super.owned})
    : super.fromPointer();

  /// Re-wraps this wrapper's [handle] as [T] via [factory].
  ///
  /// Use this when another wrapper returns this class's
  /// instance but the caller needs the destination class's
  /// methods. Pass the destination class's `fromPointer` as
  /// the callback, e.g. `wrapper.cast<GFile>(GFile.fromPointer)`.
  /// The handle is forwarded as-is; the original wrapper
  /// (which produced this object) remains the owner.
  T cast<T extends Object>(T Function(ffi.Pointer<ffi.Void>) factory) {
    return factory(handle);
  }

  /// Create a custom action that calls the given @callback when
  /// activated.
  static final _gtkCallbackActionNew =
      gtk4Lookup<
            ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(
                ffi.Pointer<
                  ffi.NativeFunction<
                    ffi.Int32 Function(
                      ffi.Pointer<ffi.Void>,
                      ffi.Pointer<ffi.Void>,
                      ffi.Pointer<ffi.Void>,
                    )
                  >
                >,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<
                  ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>
                >,
              )
            >
          >('gtk_callback_action_new')
          .asFunction<
            ffi.Pointer<ffi.Void> Function(
              ffi.Pointer<
                ffi.NativeFunction<
                  ffi.Int32 Function(
                    ffi.Pointer<ffi.Void>,
                    ffi.Pointer<ffi.Void>,
                    ffi.Pointer<ffi.Void>,
                  )
                >
              >,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<
                ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>
              >,
            )
          >();
  factory GtkCallbackAction(
    int Function(
      ffi.Pointer<ffi.Void>,
      ffi.Pointer<ffi.Void>,
      ffi.Pointer<ffi.Void>,
    )
    callback,
    ffi.Pointer<ffi.Void>? data,
    void Function(ffi.Pointer<ffi.Void>) destroy,
  ) {
    final _nc1 =
        ffi.NativeCallable<
          ffi.Int32 Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Void>,
          )
        >.isolateLocal(callback, exceptionalReturn: 0);
    final _nc3 =
        ffi.NativeCallable<
          ffi.Void Function(ffi.Pointer<ffi.Void>)
        >.isolateLocal(destroy);
    try {
      final _ret = _gtkCallbackActionNew(
        _nc1.nativeFunction,
        data ?? ffi.nullptr,
        _nc3.nativeFunction,
      );
      return GtkCallbackAction.fromPointer(_ret, owned: true);
    } finally {
      _nc1.close();
      _nc3.close();
    }
  }

  /// The notify signal is emitted on an object when one of its properties has
  /// its value set through g_object_set_property(), g_object_set(), et al.
  ///
  /// Note that getting this signal doesn’t itself guarantee that the value of
  /// the property has actually changed. When it is emitted is determined by the
  /// derived GObject class. If the implementor did not create the property with
  /// %G_PARAM_EXPLICIT_NOTIFY, then any call to g_object_set_property() results
  /// in ::notify being emitted, even if the new value is the same as the old.
  /// If they did pass %G_PARAM_EXPLICIT_NOTIFY, then this signal is emitted only
  /// when they explicitly call g_object_notify() or g_object_notify_by_pspec(),
  /// and common practice is to do that only when the value has actually changed.
  ///
  /// This signal is typically used to obtain change notification for a
  /// single property, by specifying the property name as a detail in the
  /// g_signal_connect() call, like this:
  ///
  /// |[<!-- language="C" -->
  /// g_signal_connect (text_view->buffer, "notify::paste-target-list",
  /// G_CALLBACK (gtk_text_view_target_list_notify),
  /// text_view)
  /// ]|
  ///
  /// It is important to note that you must use
  /// [canonical parameter names][class@GObject.ParamSpec#parameter-names] as
  /// detail strings for the notify signal.
  int onNotify(void Function(GParamSpec pspec) callback) {
    return _connectSignal_v_1_o_gparamspec(this.handle, 'notify', callback);
  }
}
