// Generated by gir_generator. Do not edit.
part of '../gtk4.dart';

/// PyGObject-style typed property accessor. Each getter
/// and setter delegates to the existing typed
/// `get<Name>` / `set<Name>` methods on [GtkFileDialog].
///
/// Skipped properties (unsupported type, missing getter
/// or setter) are recorded in the generation report.
class GtkFileDialogProps {
  GtkFileDialogProps(this._self);
  final GtkFileDialog _self;

  String? get acceptLabel => _self.getAcceptLabel();
  set acceptLabel(String? value) {
    _self.setAcceptLabel(value);
  }

  GtkFileFilter? get defaultFilter => _self.getDefaultFilter();
  set defaultFilter(GtkFileFilter? value) {
    _self.setDefaultFilter(value);
  }

  GListModel? get filters => _self.getFilters();
  set filters(GListModel? value) {
    _self.setFilters(value);
  }

  GFile? get initialFile => _self.getInitialFile();
  set initialFile(GFile? value) {
    _self.setInitialFile(value);
  }

  GFile? get initialFolder => _self.getInitialFolder();
  set initialFolder(GFile? value) {
    _self.setInitialFolder(value);
  }

  String? get initialName => _self.getInitialName();
  set initialName(String? value) {
    _self.setInitialName(value);
  }

  bool get modal => _self.getModal();
  set modal(bool value) {
    _self.setModal(value);
  }

  String get title => _self.getTitle();
  set title(String value) {
    _self.setTitle(value);
  }
}
